/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.InventoryManager;

import Backend.EcoSystem;
import Backend.Enterprise.Enterprise;
import Backend.Organization.InventoryManagerOrganization;
import Backend.Organization.Organization;
import Backend.UserAccount.UserAccount;
import UI.Donor.ManageDonorDetailsJPanel;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author nehar
 */
public class ManageInventoryManagerDetailsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form UserDetailsJPanel
     */
    private EcoSystem system;
      private UserAccount userAccount;
    private InventoryManagerOrganization inventoryManagerOrg;
    private Enterprise enterprise ;
    private byte[] tempdP;
    public ManageInventoryManagerDetailsJPanel(UserAccount userAccount, EcoSystem system,Organization organization,Enterprise enterprise ) {
        initComponents();
        this.system = system;
        this.userAccount = userAccount;
        this.inventoryManagerOrg = (InventoryManagerOrganization)organization;
         this.enterprise = enterprise ;
        populateDefault();
    }

    private void populateDefault() {
        svebtn.setEnabled(false);
        upldbtn.setEnabled(false);
        comboxgend.removeAllItems();
        comboxgend.addItem("Male");
        comboxgend.addItem("Female");
        txtname.setText(userAccount.getEmployee().getName());
        txtaddr.setText(userAccount.getEmployee().getAddr());
        txtcity.setText(userAccount.getEmployee().getUrban());
        txtcont.setText(userAccount.getEmployee().getPhoneNumber());
        picdate1txt.setDate(userAccount.getEmployee().getDOB());
        comboxgend.setSelectedItem(userAccount.getEmployee().getGender());
//        emergencyContactJTextField.setText(userAccount.getEmployee().getEmergencyPhoneNumber());
//        txtorgbank.setText(userAccount.getEmployee().getRelationShip());
        txtstate.setText(userAccount.getEmployee().getState());
        txtzcode.setText(userAccount.getEmployee().getZip());
        txtorginization.setText(inventoryManagerOrg.getOrgName());
//        txtorgbank.setText(enterprise.getName());
         if(userAccount.getEmployee().getdP() !=null){
        //Working line
         byte[] JLabelpictureLabel = userAccount.getEmployee().getdP();
        ImageIcon i = setPicturebyte(JLabelpictureLabel);
        lblphoto.setIcon(i);
        }
        else{
            System.err.println("No Image");
        }
        txtaddr.setEditable(false);
        txtcity.setEditable(false);
        txtcont.setEditable(false);
        picdate1txt.setEditable(false);
        comboxgend.setEnabled(false);
//        emergencyContactJTextField.setEditable(false);
        txtstate.setEditable(false);
//        txtorgbank.setEditable(false);
        txtzcode.setEditable(false); 
    }
private ImageIcon setPicturebyte(byte[] byteArrayImage){

        ImageIcon imageCar;
        imageCar = new ImageIcon(byteArrayImage);
        Image picCar = imageCar.getImage();
        JLabel pictureLabel1 = new JLabel();
        pictureLabel1.setSize(107, 133);
        Image resizedImage = picCar.getScaledInstance(pictureLabel1.getWidth(), pictureLabel1.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon selectedCarPicture = new ImageIcon(resizedImage);
        return selectedCarPicture;  
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelheader = new javax.swing.JLabel();
        addrlabel = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        txtcity = new javax.swing.JTextField();
        citylabel = new javax.swing.JLabel();
        txtaddr = new javax.swing.JTextField();
        labelcont = new javax.swing.JLabel();
        txtcont = new javax.swing.JTextField();
        namlabel = new javax.swing.JLabel();
        txtstate = new javax.swing.JTextField();
        statelabel = new javax.swing.JLabel();
        xcodelabel = new javax.swing.JLabel();
        txtzcode = new javax.swing.JTextField();
        lblphoto = new javax.swing.JLabel();
        genlabel = new javax.swing.JLabel();
        comboxgend = new javax.swing.JComboBox();
        dateofbirthlabel = new javax.swing.JLabel();
        picdate1txt = new org.jdesktop.swingx.JXDatePicker();
        upldbtn = new javax.swing.JButton();
        svebtn = new javax.swing.JButton();
        updbtn = new javax.swing.JButton();
        orgnzlabel = new javax.swing.JLabel();
        txtorginization = new javax.swing.JTextField();
        bgdimg = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(null);
        setMinimumSize(null);
        setPreferredSize(null);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelheader.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        labelheader.setForeground(new java.awt.Color(255, 255, 255));
        labelheader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelheader.setText("Inventory Manager Personal Information");
        add(labelheader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 60));

        addrlabel.setBackground(new java.awt.Color(255, 255, 255));
        addrlabel.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        addrlabel.setForeground(new java.awt.Color(255, 255, 255));
        addrlabel.setText("Address");
        add(addrlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 65, -1));

        txtname.setEditable(false);
        txtname.setBorder(null);
        txtname.setCaretColor(new java.awt.Color(30, 59, 92));
        txtname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtnameFocusGained(evt);
            }
        });
        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });
        add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 140, 20));

        txtcity.setBorder(null);
        txtcity.setCaretColor(new java.awt.Color(30, 59, 92));
        txtcity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtcityFocusGained(evt);
            }
        });
        txtcity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcityActionPerformed(evt);
            }
        });
        add(txtcity, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 140, 20));

        citylabel.setBackground(new java.awt.Color(255, 255, 255));
        citylabel.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        citylabel.setForeground(new java.awt.Color(255, 255, 255));
        citylabel.setText("City");
        add(citylabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, -1, -1));

        txtaddr.setBorder(null);
        txtaddr.setCaretColor(new java.awt.Color(30, 59, 92));
        txtaddr.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtaddrFocusGained(evt);
            }
        });
        txtaddr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtaddrActionPerformed(evt);
            }
        });
        add(txtaddr, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 140, 17));

        labelcont.setBackground(new java.awt.Color(255, 255, 255));
        labelcont.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        labelcont.setForeground(new java.awt.Color(255, 255, 255));
        labelcont.setText("Contact");
        add(labelcont, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, -1, -1));

        txtcont.setBorder(null);
        txtcont.setCaretColor(new java.awt.Color(30, 59, 92));
        txtcont.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtcontFocusGained(evt);
            }
        });
        txtcont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcontActionPerformed(evt);
            }
        });
        add(txtcont, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 140, 19));

        namlabel.setBackground(new java.awt.Color(255, 255, 255));
        namlabel.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        namlabel.setForeground(new java.awt.Color(255, 255, 255));
        namlabel.setText("Name");
        add(namlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        txtstate.setBorder(null);
        txtstate.setCaretColor(new java.awt.Color(30, 59, 92));
        txtstate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtstateFocusGained(evt);
            }
        });
        txtstate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstateActionPerformed(evt);
            }
        });
        add(txtstate, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, 140, 20));

        statelabel.setBackground(new java.awt.Color(255, 255, 255));
        statelabel.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        statelabel.setForeground(new java.awt.Color(255, 255, 255));
        statelabel.setText("State");
        add(statelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, -1, -1));

        xcodelabel.setBackground(new java.awt.Color(255, 255, 255));
        xcodelabel.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        xcodelabel.setForeground(new java.awt.Color(255, 255, 255));
        xcodelabel.setText("Zip Code");
        add(xcodelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 320, -1, -1));

        txtzcode.setBorder(null);
        txtzcode.setCaretColor(new java.awt.Color(30, 59, 92));
        txtzcode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtzcodeFocusGained(evt);
            }
        });
        txtzcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtzcodeActionPerformed(evt);
            }
        });
        add(txtzcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 350, 140, 20));

        lblphoto.setBackground(new java.awt.Color(255, 255, 255));
        lblphoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblphoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        add(lblphoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 100, 107, 133));

        genlabel.setBackground(new java.awt.Color(255, 255, 255));
        genlabel.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        genlabel.setForeground(new java.awt.Color(255, 255, 255));
        genlabel.setText("Gender");
        add(genlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, -1, -1));

        comboxgend.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(comboxgend, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, -1, -1));

        dateofbirthlabel.setBackground(new java.awt.Color(255, 255, 255));
        dateofbirthlabel.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        dateofbirthlabel.setForeground(new java.awt.Color(255, 255, 255));
        dateofbirthlabel.setText("Date of Birth");
        add(dateofbirthlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, -1, -1));

        picdate1txt.setBackground(new java.awt.Color(255, 255, 255));
        add(picdate1txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, -1, -1));

        upldbtn.setBackground(new java.awt.Color(19, 57, 119));
        upldbtn.setFont(new java.awt.Font("Dubai Medium", 0, 13)); // NOI18N
        upldbtn.setForeground(new java.awt.Color(255, 255, 255));
        upldbtn.setText("Upload");
        upldbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upldbtnActionPerformed(evt);
            }
        });
        add(upldbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 250, -1, -1));

        svebtn.setBackground(new java.awt.Color(9, 37, 83));
        svebtn.setFont(new java.awt.Font("Dubai Medium", 0, 13)); // NOI18N
        svebtn.setForeground(new java.awt.Color(255, 255, 255));
        svebtn.setText("Save");
        svebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                svebtnActionPerformed(evt);
            }
        });
        add(svebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 470, 117, -1));

        updbtn.setBackground(new java.awt.Color(9, 37, 83));
        updbtn.setFont(new java.awt.Font("Dubai Medium", 0, 13)); // NOI18N
        updbtn.setForeground(new java.awt.Color(255, 255, 255));
        updbtn.setText("Update");
        updbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updbtnActionPerformed(evt);
            }
        });
        add(updbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 470, 117, 40));

        orgnzlabel.setBackground(new java.awt.Color(255, 255, 255));
        orgnzlabel.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        orgnzlabel.setForeground(new java.awt.Color(255, 255, 255));
        orgnzlabel.setText("Organization");
        add(orgnzlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, -1, -1));

        txtorginization.setBorder(null);
        txtorginization.setCaretColor(new java.awt.Color(30, 59, 92));
        txtorginization.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtorginizationFocusGained(evt);
            }
        });
        txtorginization.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtorginizationActionPerformed(evt);
            }
        });
        add(txtorginization, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 280, 140, 20));

        bgdimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/blue-abstract-wave-flow-minimalist.jpg"))); // NOI18N
        bgdimg.setMaximumSize(null);
        bgdimg.setMinimumSize(null);
        bgdimg.setPreferredSize(null);
        add(bgdimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnameFocusGained
        // TODO add your handling code here:
     
    }//GEN-LAST:event_txtnameFocusGained

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void txtcontFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcontFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcontFocusGained

    private void txtcontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcontActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcontActionPerformed

    private void txtaddrFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtaddrFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaddrFocusGained

    private void txtaddrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtaddrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaddrActionPerformed

    private void txtcityFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcityFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcityFocusGained

    private void txtcityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcityActionPerformed

    private void txtstateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtstateFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstateFocusGained

    private void txtstateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstateActionPerformed

    private void txtzcodeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtzcodeFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtzcodeFocusGained

    private void txtzcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtzcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtzcodeActionPerformed

    private void upldbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upldbtnActionPerformed
        // TODO add your handling code here:
        JFileChooser file = new JFileChooser();
          file.setCurrentDirectory(new File(System.getProperty("user.dir")));
          //filter the files
          FileNameExtensionFilter filter = new FileNameExtensionFilter("*.Images", "jpg","gif","png");
          file.addChoosableFileFilter(filter);
          int result = file.showSaveDialog(null);
           //if the user click on save in Jfilechooser
          if(result == JFileChooser.APPROVE_OPTION){
              File selectedFile = file.getSelectedFile();
              tempdP = new byte[(int) selectedFile.length()]; 
                FileInputStream fis;
             try {
                 fis = new FileInputStream(selectedFile);
                 fis.read(tempdP);
                 fis.close();
             } catch (IOException ex) {
                 Logger.getLogger(ManageDonorDetailsJPanel.class.getName()).log(Level.SEVERE, null, ex);
             }             
              lblphoto.setIcon(ResizeImage(selectedFile.getAbsolutePath()));
              lblphoto.setIcon(setPicture(selectedFile.getAbsolutePath(),lblphoto));
          }

          else if(result == JFileChooser.CANCEL_OPTION){
              System.out.println("No File Select");
          }
    }//GEN-LAST:event_upldbtnActionPerformed
    private ImageIcon setPicture(String carImageLocation, JLabel carImage){

        ImageIcon imageCar;
        imageCar = new ImageIcon(carImageLocation);
        Image picCar = imageCar.getImage();
        Image resizedImage = picCar.getScaledInstance(carImage.getWidth(), carImage.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon selectedCarPicture = new ImageIcon(resizedImage);
        
        return selectedCarPicture;  
}
     
    private void svebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_svebtnActionPerformed
        // TODO add your handling code here:
//        try {
//            Integer.parseInt(zipJTextField.getText());
//            Integer.parseInt(contactJTextField.getText());
//
//        } catch (NumberFormatException e) {
//            JOptionPane.showMessageDialog(null, "Contact Number and Zip code should be numberic", "Error", 0);
//            return;
//        }
         
        if (txtaddr.getText().isEmpty()           || txtcity.getText().isEmpty()     ||
            txtcont.getText().isEmpty()           || txtstate.getText().isEmpty()    ||
            txtzcode.getText().isEmpty()               || txtname.getText().isEmpty() )
            
        { 
    
         JOptionPane.showMessageDialog(null, "All fields are mandatory", "Error", JOptionPane.ERROR_MESSAGE);
         return ;
        }
        
          Date currentDate = new Date();
          
          if (currentDate.equals(picdate1txt.getDate()) || picdate1txt.getDate().after(currentDate)) {
          
             JOptionPane.showMessageDialog(null, "Date should be past date", "Error", JOptionPane.ERROR_MESSAGE);
             return;
          }
          
          if (txtcont.getText().length() != 10 ) {
             JOptionPane.showMessageDialog(null, "Contact information should be 10 number", "Error", JOptionPane.ERROR_MESSAGE);
             return;   
          }
          
          if (txtzcode.getText().length() != 5) {
             JOptionPane.showMessageDialog(null, "Zip code should be 5 digit", "Error", JOptionPane.ERROR_MESSAGE);
             return;   
          }
          
        userAccount.getEmployee().setAddr(txtaddr.getText());
        userAccount.getEmployee().setUrban(txtcity.getText());
        userAccount.getEmployee().setPhoneNumber(txtcont.getText());
        userAccount.getEmployee().setDOB(picdate1txt.getDate());
        userAccount.getEmployee().setGender((String) comboxgend.getSelectedItem());
//        userAccount.getEmployee().setEmergencyPhoneNumber(emergencyContactJTextField.getText());
//        userAccount.getEmployee().setRelationShip(txtorgbank.getText());
        userAccount.getEmployee().setState(txtstate.getText());
        userAccount.getEmployee().setZip(txtzcode.getText());
         userAccount.getEmployee().setdP(tempdP);
        JOptionPane.showMessageDialog(null, "Profile Updated Sucessfully");   
        txtaddr.setEditable(false);
        txtcity.setEditable(false);
        txtcont.setEditable(false);
        picdate1txt.setEnabled(false);
        comboxgend.setEnabled(false);
//        emergencyContactJTextField.setEditable(false);
        txtstate.setEditable(false);
//        txtorgbank.setEditable(false);
        txtzcode.setEditable(false);      
        updbtn.setEnabled(true);
        svebtn.setEnabled(false);
        upldbtn.setEnabled(false);
        
        
    }//GEN-LAST:event_svebtnActionPerformed

    private void updbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updbtnActionPerformed
        // TODO add your handling code here:
        updbtn.setEnabled(false);
        svebtn.setEnabled(true);
        upldbtn.setEnabled(true);
        txtaddr.setEditable(true);
        txtcity.setEditable(true);
        txtcont.setEditable(true);
        picdate1txt.setEditable(true);
        comboxgend.setEnabled(true);
//        emergencyContactJTextField.setEditable(true);
        txtstate.setEditable(true);
//        txtorgbank.setEditable(true);
        txtzcode.setEditable(true); 
    }//GEN-LAST:event_updbtnActionPerformed

    private void txtorginizationFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtorginizationFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtorginizationFocusGained

    private void txtorginizationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtorginizationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtorginizationActionPerformed
    
    public ImageIcon ResizeImage(String ImagePath)
    {
        ImageIcon MyImage = new ImageIcon(ImagePath);
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(lblphoto.getWidth(), lblphoto.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addrlabel;
    private javax.swing.JLabel bgdimg;
    private javax.swing.JLabel citylabel;
    private javax.swing.JComboBox comboxgend;
    private javax.swing.JLabel dateofbirthlabel;
    private javax.swing.JLabel genlabel;
    private javax.swing.JLabel labelcont;
    private javax.swing.JLabel labelheader;
    private javax.swing.JLabel lblphoto;
    private javax.swing.JLabel namlabel;
    private javax.swing.JLabel orgnzlabel;
    private org.jdesktop.swingx.JXDatePicker picdate1txt;
    private javax.swing.JLabel statelabel;
    private javax.swing.JButton svebtn;
    private javax.swing.JTextField txtaddr;
    private javax.swing.JTextField txtcity;
    private javax.swing.JTextField txtcont;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtorginization;
    private javax.swing.JTextField txtstate;
    private javax.swing.JTextField txtzcode;
    private javax.swing.JButton updbtn;
    private javax.swing.JButton upldbtn;
    private javax.swing.JLabel xcodelabel;
    // End of variables declaration//GEN-END:variables

}
