/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Doctor;

import Backend.EcoSystem;
import Backend.Enterprise.Enterprise;
import Backend.Organization.DoctorOrganization;
import Backend.UserAccount.UserAccount;
import UI.Donor.ManageDonorDetailsJPanel;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author harish
 */
public class ManageDoctorDetailsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form UserDetailsJPanel
     */
    private EcoSystem system;
     private UserAccount userAccount;
     private Enterprise enterprise ;
 private DoctorOrganization docOrganization;
  private byte[] tempdP;
    public ManageDoctorDetailsJPanel(UserAccount userAccount, EcoSystem system,DoctorOrganization docOrganization,Enterprise enterprise) {
        initComponents();
        this.system = system;
        this.userAccount = userAccount;
        this.enterprise = enterprise ;
        this.docOrganization = (DoctorOrganization)docOrganization;
        populateDefault();
    }

    private void populateDefault() {
        btnsve.setEnabled(false);
        uplbtn.setEnabled(false);
        cmboxgend.removeAllItems();
        cmboxgend.addItem("Male");
        cmboxgend.addItem("Female");
        txtname.setText(userAccount.getEmployee().getName());
        txtaddr.setText(userAccount.getEmployee().getAddr());
        txtcity.setText(userAccount.getEmployee().getUrban());
        txtcont.setText(userAccount.getEmployee().getPhoneNumber());
        datepik1txt.setDate(userAccount.getEmployee().getDOB());
        cmboxgend.setSelectedItem(userAccount.getEmployee().getGender());
//        emergencyContactJTextField.setText(userAccount.getEmployee().getEmergencyPhoneNumber());
//        ornbnktxt.setText(userAccount.getEmployee().getRelationShip());
        txtstate.setText(userAccount.getEmployee().getState());
        txtzipcode.setText(userAccount.getEmployee().getZip());
         orgTextField.setText(docOrganization.getOrgName());
//        ornbnktxt.setText(enterprise.getName());
        if(userAccount.getEmployee().getdP() !=null){
        //Working line
         byte[] JLabelpictureLabel = userAccount.getEmployee().getdP();
        ImageIcon i = setPicturebyte(JLabelpictureLabel);
        photolbl.setIcon(i);
        }
        else{
            System.err.println("No Image");
        }
        txtaddr.setEditable(false);
        txtcity.setEditable(false);
        txtcont.setEditable(false);
        datepik1txt.setEditable(false);
        cmboxgend.setEnabled(false);
//        emergencyContactJTextField.setEditable(false);
        txtstate.setEditable(false);
//        ornbnktxt.setEditable(false);
        txtzipcode.setEditable(false); 
    }
private ImageIcon setPicturebyte(byte[] byteArrayImage){

        ImageIcon imageCar;
        imageCar = new ImageIcon(byteArrayImage);
        Image picCar = imageCar.getImage();
        JLabel pictureLabel1 = new JLabel();
        pictureLabel1.setSize(107, 133);
        Image resizedImage = picCar.getScaledInstance(pictureLabel1.getWidth(), pictureLabel1.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon selectedCarPicture = new ImageIcon(resizedImage);
        return selectedCarPicture;  
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addrlabel = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        txtcity = new javax.swing.JTextField();
        citylabel = new javax.swing.JLabel();
        txtaddr = new javax.swing.JTextField();
        cntlabel = new javax.swing.JLabel();
        txtcont = new javax.swing.JTextField();
        namelabel = new javax.swing.JLabel();
        txtstate = new javax.swing.JTextField();
        stlabel = new javax.swing.JLabel();
        zpcodelabel = new javax.swing.JLabel();
        txtzipcode = new javax.swing.JTextField();
        photolbl = new javax.swing.JLabel();
        genlabel = new javax.swing.JLabel();
        cmboxgend = new javax.swing.JComboBox();
        dateofbirthlabel = new javax.swing.JLabel();
        datepik1txt = new org.jdesktop.swingx.JXDatePicker();
        uplbtn = new javax.swing.JButton();
        btnsve = new javax.swing.JButton();
        btnupd = new javax.swing.JButton();
        organizationlabel = new javax.swing.JLabel();
        orgTextField = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();
        bgdimg = new javax.swing.JLabel();

        setBackground(new java.awt.Color(3, 15, 41));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setForeground(new java.awt.Color(255, 255, 255));
        setMaximumSize(null);
        setMinimumSize(null);
        setPreferredSize(null);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addrlabel.setBackground(new java.awt.Color(255, 255, 255));
        addrlabel.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        addrlabel.setForeground(new java.awt.Color(255, 255, 255));
        addrlabel.setText("Address");
        add(addrlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 65, -1));

        txtname.setEditable(false);
        txtname.setBorder(null);
        txtname.setCaretColor(new java.awt.Color(30, 59, 92));
        txtname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtnameFocusGained(evt);
            }
        });
        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });
        add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 140, 22));

        txtcity.setBorder(null);
        txtcity.setCaretColor(new java.awt.Color(30, 59, 92));
        txtcity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtcityFocusGained(evt);
            }
        });
        txtcity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcityActionPerformed(evt);
            }
        });
        add(txtcity, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 140, 20));

        citylabel.setBackground(new java.awt.Color(255, 255, 255));
        citylabel.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        citylabel.setForeground(new java.awt.Color(255, 255, 255));
        citylabel.setText("City");
        add(citylabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, -1, -1));

        txtaddr.setBorder(null);
        txtaddr.setCaretColor(new java.awt.Color(30, 59, 92));
        txtaddr.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtaddrFocusGained(evt);
            }
        });
        txtaddr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtaddrActionPerformed(evt);
            }
        });
        add(txtaddr, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 140, 20));

        cntlabel.setBackground(new java.awt.Color(255, 255, 255));
        cntlabel.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        cntlabel.setForeground(new java.awt.Color(255, 255, 255));
        cntlabel.setText("Contact");
        add(cntlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, -1, -1));

        txtcont.setBorder(null);
        txtcont.setCaretColor(new java.awt.Color(30, 59, 92));
        txtcont.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtcontFocusGained(evt);
            }
        });
        txtcont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcontActionPerformed(evt);
            }
        });
        add(txtcont, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 140, 19));

        namelabel.setBackground(new java.awt.Color(255, 255, 255));
        namelabel.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        namelabel.setForeground(new java.awt.Color(255, 255, 255));
        namelabel.setText("Name");
        add(namelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        txtstate.setBorder(null);
        txtstate.setCaretColor(new java.awt.Color(30, 59, 92));
        txtstate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtstateFocusGained(evt);
            }
        });
        txtstate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstateActionPerformed(evt);
            }
        });
        add(txtstate, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, 140, 20));

        stlabel.setBackground(new java.awt.Color(255, 255, 255));
        stlabel.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        stlabel.setForeground(new java.awt.Color(255, 255, 255));
        stlabel.setText("State");
        add(stlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, -1, -1));

        zpcodelabel.setBackground(new java.awt.Color(255, 255, 255));
        zpcodelabel.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        zpcodelabel.setForeground(new java.awt.Color(255, 255, 255));
        zpcodelabel.setText("Zip Code");
        add(zpcodelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 370, -1, -1));

        txtzipcode.setBorder(null);
        txtzipcode.setCaretColor(new java.awt.Color(30, 59, 92));
        txtzipcode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtzipcodeFocusGained(evt);
            }
        });
        txtzipcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtzipcodeActionPerformed(evt);
            }
        });
        add(txtzipcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, 140, 20));

        photolbl.setBackground(new java.awt.Color(255, 255, 255));
        photolbl.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        photolbl.setForeground(new java.awt.Color(255, 255, 255));
        photolbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        photolbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        add(photolbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, 107, 133));

        genlabel.setBackground(new java.awt.Color(255, 255, 255));
        genlabel.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        genlabel.setForeground(new java.awt.Color(255, 255, 255));
        genlabel.setText("Gender");
        add(genlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, -1, -1));

        cmboxgend.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(cmboxgend, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 60, -1));

        dateofbirthlabel.setBackground(new java.awt.Color(255, 255, 255));
        dateofbirthlabel.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        dateofbirthlabel.setForeground(new java.awt.Color(255, 255, 255));
        dateofbirthlabel.setText("Date of Birth");
        add(dateofbirthlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, -1, -1));

        datepik1txt.setBackground(new java.awt.Color(255, 255, 255));
        datepik1txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datepik1txtActionPerformed(evt);
            }
        });
        add(datepik1txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 160, -1));

        uplbtn.setBackground(new java.awt.Color(0, 0, 0));
        uplbtn.setFont(new java.awt.Font("Dubai Medium", 0, 13)); // NOI18N
        uplbtn.setForeground(new java.awt.Color(255, 255, 255));
        uplbtn.setText("Upload");
        uplbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uplbtnActionPerformed(evt);
            }
        });
        add(uplbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, -1, 30));

        btnsve.setBackground(new java.awt.Color(0, 0, 0));
        btnsve.setFont(new java.awt.Font("Dubai Medium", 0, 13)); // NOI18N
        btnsve.setForeground(new java.awt.Color(255, 255, 255));
        btnsve.setText("Save");
        btnsve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsveActionPerformed(evt);
            }
        });
        add(btnsve, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 570, 117, -1));

        btnupd.setBackground(new java.awt.Color(0, 0, 0));
        btnupd.setFont(new java.awt.Font("Dubai Medium", 0, 13)); // NOI18N
        btnupd.setForeground(new java.awt.Color(255, 255, 255));
        btnupd.setText("Update");
        btnupd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdActionPerformed(evt);
            }
        });
        add(btnupd, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 570, 117, -1));

        organizationlabel.setBackground(new java.awt.Color(255, 255, 255));
        organizationlabel.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        organizationlabel.setForeground(new java.awt.Color(255, 255, 255));
        organizationlabel.setText("Organization");
        add(organizationlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, -1, -1));

        orgTextField.setBorder(null);
        orgTextField.setCaretColor(new java.awt.Color(30, 59, 92));
        orgTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                orgTextFieldFocusGained(evt);
            }
        });
        orgTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orgTextFieldActionPerformed(evt);
            }
        });
        add(orgTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, 140, 20));

        lblTitle.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 0, 51));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Doctor Information");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 70));

        bgdimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/doctor.jpg"))); // NOI18N
        bgdimg.setMaximumSize(null);
        bgdimg.setMinimumSize(null);
        bgdimg.setPreferredSize(null);
        add(bgdimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void txtnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnameFocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtnameFocusGained

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void txtcontFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcontFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcontFocusGained

    private void txtcontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcontActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcontActionPerformed

    private void txtaddrFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtaddrFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaddrFocusGained

    private void txtaddrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtaddrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaddrActionPerformed

    private void txtcityFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcityFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcityFocusGained

    private void txtcityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcityActionPerformed

    private void txtstateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtstateFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstateFocusGained

    private void txtstateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstateActionPerformed

    private void txtzipcodeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtzipcodeFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtzipcodeFocusGained

    private void txtzipcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtzipcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtzipcodeActionPerformed
    
    public byte[] extractBytes (String ImageName) throws IOException {
     // open image
        BufferedImage bImage = ImageIO.read(new File("organ_Agreement.jpg"));
        ByteArrayOutputStream bos = new ByteArrayOutputStream();
        ImageIO.write(bImage, "jpg", bos );
        byte [] data = bos.toByteArray();
        return data;
    }
    
    private void uplbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uplbtnActionPerformed
        // TODO add your handling code here:
       JFileChooser file = new JFileChooser();
          file.setCurrentDirectory(new File(System.getProperty("user.dir")));
          //filter the files
          FileNameExtensionFilter filter = new FileNameExtensionFilter("*.Images", "jpg","gif","png");
          file.addChoosableFileFilter(filter);
          int result = file.showSaveDialog(null);
           //if the user click on save in Jfilechooser
          if(result == JFileChooser.APPROVE_OPTION){
              File selectedFile = file.getSelectedFile();
              tempdP = new byte[(int) selectedFile.length()]; 
                FileInputStream fis;
             try {
                 fis = new FileInputStream(selectedFile);
                 fis.read(tempdP);
                 fis.close();
             } catch (IOException ex) {
                 Logger.getLogger(ManageDonorDetailsJPanel.class.getName()).log(Level.SEVERE, null, ex);
             }             
              photolbl.setIcon(ResizeImage(selectedFile.getAbsolutePath()));
              photolbl.setIcon(setPicture(selectedFile.getAbsolutePath(),photolbl));
          }

          else if(result == JFileChooser.CANCEL_OPTION){
              System.out.println("No File Select");
          }
          
    }//GEN-LAST:event_uplbtnActionPerformed

    private ImageIcon setPicture(String carImageLocation, JLabel carImage){

        ImageIcon imageCar;
        imageCar = new ImageIcon(carImageLocation);
        Image picCar = imageCar.getImage();
        Image resizedImage = picCar.getScaledInstance(carImage.getWidth(), carImage.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon selectedCarPicture = new ImageIcon(resizedImage);
        
        return selectedCarPicture;  
}
     
    private void btnsveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsveActionPerformed
        // TODO add your handling code here:
           if (txtaddr.getText().isEmpty()           || txtcity.getText().isEmpty()     ||
            txtcont.getText().isEmpty()           || txtstate.getText().isEmpty()    ||
            txtzipcode.getText().isEmpty()               || txtname.getText().isEmpty() )
            
        { 
    
         JOptionPane.showMessageDialog(null, "All fields are mandatory", "Error", JOptionPane.ERROR_MESSAGE);
         return ;
        }
        
          Date currentDate = new Date();
          
          if (currentDate.equals(datepik1txt.getDate()) || datepik1txt.getDate().after(currentDate)) {
          
             JOptionPane.showMessageDialog(null, "Date should be past date", "Error", JOptionPane.ERROR_MESSAGE);
             return;
          }
          
          if (txtcont.getText().length() != 10 ) {
             JOptionPane.showMessageDialog(null, "Contact information should be 10 number", "Error", JOptionPane.ERROR_MESSAGE);
             return;   
          }
          
          if (txtzipcode.getText().length() != 5) {
             JOptionPane.showMessageDialog(null, "Zip code should be 5 digit", "Error", JOptionPane.ERROR_MESSAGE);
             return;   
          }
        userAccount.getEmployee().setAddr(txtaddr.getText());
        userAccount.getEmployee().setUrban(txtcity.getText());
        userAccount.getEmployee().setPhoneNumber(txtcont.getText());
        userAccount.getEmployee().setDOB(datepik1txt.getDate());
        userAccount.getEmployee().setGender((String) cmboxgend.getSelectedItem());
//        userAccount.getEmployee().setEmergencyPhoneNumber(emergencyContactJTextField.getText());
//        userAccount.getEmployee().setRelationShip(ornbnktxt.getText());
        userAccount.getEmployee().setState(txtstate.getText());
        userAccount.getEmployee().setZip(txtzipcode.getText());
        userAccount.getEmployee().setdP(tempdP);
        JOptionPane.showMessageDialog(null, "Profile Updated Sucessfully");   
        txtaddr.setEditable(false);
        txtcity.setEditable(false);
        txtcont.setEditable(false);
        datepik1txt.setEnabled(false);
        cmboxgend.setEnabled(false);
//        emergencyContactJTextField.setEditable(false);
        txtstate.setEditable(false);
//        ornbnktxt.setEditable(false);
        txtzipcode.setEditable(false);      
        btnupd.setEnabled(true);
        btnsve.setEnabled(false);
        uplbtn.setEnabled(false);
        
    }//GEN-LAST:event_btnsveActionPerformed

    private void btnupdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdActionPerformed
        // TODO add your handling code here:
        btnupd.setEnabled(false);
        btnsve.setEnabled(true);
        uplbtn.setEnabled(true);
        txtaddr.setEditable(true);
        txtcity.setEditable(true);
        txtcont.setEditable(true);
        datepik1txt.setEditable(true);
        cmboxgend.setEnabled(true);
//        emergencyContactJTextField.setEditable(true);
        txtstate.setEditable(true);
//        ornbnktxt.setEditable(true);
        txtzipcode.setEditable(true); 
    }//GEN-LAST:event_btnupdActionPerformed

    private void orgTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_orgTextFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_orgTextFieldFocusGained

    private void orgTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orgTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_orgTextFieldActionPerformed

    private void datepik1txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datepik1txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_datepik1txtActionPerformed
    
    public ImageIcon ResizeImage(String ImagePath)
    {
        ImageIcon MyImage = new ImageIcon(ImagePath);
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(photolbl.getWidth(), photolbl.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addrlabel;
    private javax.swing.JLabel bgdimg;
    private javax.swing.JButton btnsve;
    private javax.swing.JButton btnupd;
    private javax.swing.JLabel citylabel;
    private javax.swing.JComboBox cmboxgend;
    private javax.swing.JLabel cntlabel;
    private javax.swing.JLabel dateofbirthlabel;
    private org.jdesktop.swingx.JXDatePicker datepik1txt;
    private javax.swing.JLabel genlabel;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel namelabel;
    private javax.swing.JTextField orgTextField;
    private javax.swing.JLabel organizationlabel;
    private javax.swing.JLabel photolbl;
    private javax.swing.JLabel stlabel;
    private javax.swing.JTextField txtaddr;
    private javax.swing.JTextField txtcity;
    private javax.swing.JTextField txtcont;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtstate;
    private javax.swing.JTextField txtzipcode;
    private javax.swing.JButton uplbtn;
    private javax.swing.JLabel zpcodelabel;
    // End of variables declaration//GEN-END:variables

}
