/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainPages;

//import javafx.scene.paint.Color;
import Backend.DB4OUtil.DB4OUtil;
import Backend.EcoSystem;
import Backend.Employee.Employee;
import Backend.Enterprise.Enterprise;
import Backend.NGO.NGO;
import Backend.Organization.Organization;
import Backend.Role.SystemAdminRole;
import Backend.User.User;

import Backend.UserAccount.UserAccount;

import UI.Donor.DonorDashBoardJPanel;
import UI.Receiver.ReceiverDashBoardJPanel;
import java.awt.CardLayout;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import Backend.JavaMailUtil;
import org.jdesktop.swingx.JXFrame;

/**
 *
 * @author harish
 */
public class LoginPage extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    private EcoSystem system;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    private String verificationCode = JavaMailUtil.getRandomCode();
    private Boolean check = false;
    public LoginPage() {
        initComponents();
        system = dB4OUtil.retrieveSystem();
        ButtonsignUp.setVisible(false);
        btnverifyEmail.setVisible(false);
        //signUpBottomTextBox.setVisible(false);
        TextFieldemailId.setVisible(false);
        emailIdJlabel.setVisible(false);
        txtVerifyCode.setVisible(false);
        jButton1.setVisible(false);
        verifyButton.setVisible(false);
        NGOCbx.setVisible(false);
   //     emailIdSeparator.setVisible(false);
        JTextFieldname.setVisible(false);
   //     nameSeparator.setVisible(false);
        nameLabel.setVisible(false);
        RadioButtonDonor.setVisible(false);
        RadioButtonreceiver.setVisible(false);
        ButtonsignIn.setVisible(true);
        LabelerrorthrownForEmailId.setVisible(false);
        LabelerrorthrownforerrorPassword.setVisible(false);
        //signInBottomTextBox.setVisible(true);
        ButtonGroup group = new ButtonGroup();
        group.add(RadioButtonDonor);
        group.add(RadioButtonreceiver);
        this.setExtendedState(JXFrame.MAXIMIZED_BOTH);

        
    }

    public LoginPage(boolean sysAdminPressed, boolean employee) {
        initComponents();        
         system = dB4OUtil.retrieveSystem();
        TextFieldemailId.setVisible(false);
        emailIdJlabel.setVisible(false);
        txtVerifyCode.setVisible(false);
        verifyButton.setVisible(false);
        //emailIdSeparator.setVisible(false);
        JTextFieldname.setVisible(false);
        //nameSeparator.setVisible(false);
        nameLabel.setVisible(false);
        RadioButtonDonor.setVisible(false);
        RadioButtonreceiver.setVisible(false);
        ButtonsignIn.setVisible(true);
        LabelerrorthrownForEmailId.setVisible(false);
        LabelerrorthrownforerrorPassword.setVisible(false);
        
        //signInBottomTextBox.setVisible(true);
        ButtonGroup group = new ButtonGroup();
        group.add(RadioButtonDonor);
        group.add(RadioButtonreceiver);
        if(sysAdminPressed==true){
            ButtonsignUp.setVisible(false);
            LabelTopsignUp.setVisible(false);
            LabeTopsignIn.setVisible(false);
        } //To change body of generated methods, choose Tools | Templates.
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblbgd = new javax.swing.JLabel();
        userProcessContainer = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        panel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        passwordlabel6 = new javax.swing.JLabel();
        ButtonsignIn = new javax.swing.JLabel();
        LabelerrorthrownforerrorPassword = new javax.swing.JLabel();
        JTextFieldname = new javax.swing.JTextField();
        Fieldpassword = new javax.swing.JPasswordField();
        JTextFielduserName = new javax.swing.JTextField();
        emailIdJlabel = new javax.swing.JLabel();
        ButtonsignUp = new javax.swing.JLabel();
        RadioButtonreceiver = new javax.swing.JRadioButton();
        LabelerrorthrownForEmailId = new javax.swing.JLabel();
        TextFieldemailId = new javax.swing.JTextField();
        RadioButtonDonor = new javax.swing.JRadioButton();
        nameLabel = new javax.swing.JLabel();
        buttonsexit = new javax.swing.JLabel();
        Usernamelabel = new javax.swing.JLabel();
        Titlelabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        LabelTopsignUp = new javax.swing.JLabel();
        LabeTopsignIn = new javax.swing.JLabel();
        NGOCbx = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        btnverifyEmail = new javax.swing.JButton();
        txtVerifyCode = new javax.swing.JTextField();
        verifyButton = new javax.swing.JButton();
        lblBgd = new javax.swing.JLabel();

        lblbgd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/WorkTIme.png"))); // NOI18N

        javax.swing.GroupLayout userProcessContainerLayout = new javax.swing.GroupLayout(userProcessContainer);
        userProcessContainer.setLayout(userProcessContainerLayout);
        userProcessContainerLayout.setHorizontalGroup(
            userProcessContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        userProcessContainerLayout.setVerticalGroup(
            userProcessContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new java.awt.GridLayout(1, 1));

        panel.setBackground(new java.awt.Color(51, 204, 255));
        panel.setOpaque(false);
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 255));
        jPanel1.setMaximumSize(null);
        jPanel1.setOpaque(false);

        passwordlabel6.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        passwordlabel6.setForeground(new java.awt.Color(255, 255, 255));
        passwordlabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        passwordlabel6.setText("Password");

        ButtonsignIn.setBackground(new java.awt.Color(30, 59, 91));
        ButtonsignIn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ButtonsignIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sign in.png"))); // NOI18N
        ButtonsignIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ButtonsignInMousePressed(evt);
            }
        });

        LabelerrorthrownforerrorPassword.setBackground(new java.awt.Color(204, 204, 204));
        LabelerrorthrownforerrorPassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LabelerrorthrownforerrorPassword.setForeground(new java.awt.Color(255, 51, 51));
        LabelerrorthrownforerrorPassword.setText("!");
        LabelerrorthrownforerrorPassword.setToolTipText("Password Should be more than 6 character");

        JTextFieldname.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        JTextFieldname.setAlignmentX(0.0F);
        JTextFieldname.setAlignmentY(0.0F);
        JTextFieldname.setBorder(null);
        JTextFieldname.setCaretColor(new java.awt.Color(30, 59, 92));
        JTextFieldname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                JTextFieldnameFocusGained(evt);
            }
        });
        JTextFieldname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextFieldnameActionPerformed(evt);
            }
        });

        Fieldpassword.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        Fieldpassword.setBorder(null);
        Fieldpassword.setCaretColor(new java.awt.Color(30, 59, 92));
        Fieldpassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                FieldpasswordFocusGained(evt);
            }
        });
        Fieldpassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                FieldpasswordKeyReleased(evt);
            }
        });

        JTextFielduserName.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        JTextFielduserName.setBorder(null);
        JTextFielduserName.setCaretColor(new java.awt.Color(30, 59, 92));
        JTextFielduserName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                JTextFielduserNameFocusGained(evt);
            }
        });
        JTextFielduserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextFielduserNameActionPerformed(evt);
            }
        });

        emailIdJlabel.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        emailIdJlabel.setForeground(new java.awt.Color(255, 255, 255));
        emailIdJlabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        emailIdJlabel.setText("Email Id");

        ButtonsignUp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ButtonsignUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-sign-up-100.png"))); // NOI18N
        ButtonsignUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ButtonsignUpMousePressed(evt);
            }
        });

        RadioButtonreceiver.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        RadioButtonreceiver.setForeground(new java.awt.Color(255, 255, 255));
        RadioButtonreceiver.setText("Receiver");
        RadioButtonreceiver.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        LabelerrorthrownForEmailId.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LabelerrorthrownForEmailId.setForeground(new java.awt.Color(255, 0, 0));
        LabelerrorthrownForEmailId.setText("!");
        LabelerrorthrownForEmailId.setToolTipText("Please enter a valid Email ID");

        TextFieldemailId.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        TextFieldemailId.setBorder(null);
        TextFieldemailId.setCaretColor(new java.awt.Color(30, 59, 92));
        TextFieldemailId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextFieldemailIdFocusGained(evt);
            }
        });
        TextFieldemailId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldemailIdActionPerformed(evt);
            }
        });
        TextFieldemailId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextFieldemailIdKeyReleased(evt);
            }
        });

        RadioButtonDonor.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        RadioButtonDonor.setForeground(new java.awt.Color(255, 255, 255));
        RadioButtonDonor.setText("Donor");
        RadioButtonDonor.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        nameLabel.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(255, 255, 255));
        nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        nameLabel.setText("Name");

        buttonsexit.setBackground(new java.awt.Color(255, 255, 255));
        buttonsexit.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        buttonsexit.setForeground(new java.awt.Color(255, 255, 255));
        buttonsexit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buttonsexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logoutx32.png"))); // NOI18N
        buttonsexit.setText("Logout\n");
        buttonsexit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonsexitMousePressed(evt);
            }
        });

        Usernamelabel.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        Usernamelabel.setForeground(new java.awt.Color(255, 255, 255));
        Usernamelabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        Usernamelabel.setText("Username");

        Titlelabel.setFont(new java.awt.Font("Times New Roman", 1, 40)); // NOI18N
        Titlelabel.setForeground(new java.awt.Color(255, 255, 255));
        Titlelabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titlelabel.setText("Make a Difference");

        jLabel1.setText(" ");

        LabelTopsignUp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelTopsignUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-sign-up-100.png"))); // NOI18N
        LabelTopsignUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LabelTopsignUpMousePressed(evt);
            }
        });

        LabeTopsignIn.setBackground(new java.awt.Color(30, 59, 91));
        LabeTopsignIn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabeTopsignIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sign in.png"))); // NOI18N
        LabeTopsignIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LabeTopsignInMousePressed(evt);
            }
        });

        NGOCbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--select any NGO---", "Liver NGO", "Limp NGO" }));

        jButton1.setText("NGO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnverifyEmail.setText("Send OTP");
        btnverifyEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnverifyEmailActionPerformed(evt);
            }
        });

        txtVerifyCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVerifyCodeActionPerformed(evt);
            }
        });

        verifyButton.setText("Verify");
        verifyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verifyButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Titlelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 1100, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(920, 920, 920)
                .addComponent(buttonsexit, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(600, 600, 600)
                .addComponent(jLabel1))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(LabelTopsignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(LabeTopsignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(290, 290, 290)
                .addComponent(jButton1))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(JTextFieldname, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(Usernamelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(JTextFielduserName, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(passwordlabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(Fieldpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(LabelerrorthrownforerrorPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(emailIdJlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(TextFieldemailId, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelerrorthrownForEmailId, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnverifyEmail))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(txtVerifyCode, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(verifyButton))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(310, 310, 310)
                .addComponent(RadioButtonDonor, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(RadioButtonreceiver, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(NGOCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(290, 290, 290)
                .addComponent(ButtonsignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(ButtonsignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Titlelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(buttonsexit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelTopsignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabeTopsignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addComponent(jButton1)
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTextFieldname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(Usernamelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(JTextFielduserName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passwordlabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Fieldpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelerrorthrownforerrorPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(emailIdJlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextFieldemailId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelerrorthrownForEmailId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnverifyEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtVerifyCode)
                        .addComponent(verifyButton)))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RadioButtonDonor)
                    .addComponent(RadioButtonreceiver, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NGOCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonsignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonsignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        panel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lblBgd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/login_new.jpg"))); // NOI18N
        lblBgd.setMaximumSize(null);
        lblBgd.setMinimumSize(null);
        lblBgd.setOpaque(true);
        lblBgd.setPreferredSize(null);
        panel.add(lblBgd, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3840, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel2);

        pack();
    }// </editor-fold>//GEN-END:initComponents
   int xx,xy; 
    private void buttonsexitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonsexitMousePressed
        // TODO add your handling code here:
        LoginPage.super.dispose();
    }//GEN-LAST:event_buttonsexitMousePressed

    private void TextFieldemailIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldemailIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldemailIdActionPerformed

    private void FieldpasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FieldpasswordFocusGained
        // TODO add your handling code here:
       Fieldpassword.setText("");
    }//GEN-LAST:event_FieldpasswordFocusGained

    private void JTextFielduserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextFielduserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextFielduserNameActionPerformed

    private void JTextFielduserNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTextFielduserNameFocusGained
        // TODO add your handling code here:
       JTextFielduserName.setText("");
    }//GEN-LAST:event_JTextFielduserNameFocusGained

    private void TextFieldemailIdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextFieldemailIdFocusGained
        // TODO add your handling code here:
     TextFieldemailId.setText("");
    }//GEN-LAST:event_TextFieldemailIdFocusGained

    private void ButtonsignUpMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonsignUpMousePressed
        // TODO add your handling code here:
           
           try {
//            if (!checkUserIdExists(userNameJTextField.getText())){
//            JOptionPane.showMessageDialog(null, "UserName Already Present","Warning",JOptionPane.WARNING_MESSAGE);
//            return;
//            }
            
            if (Fieldpassword.getText().length() < 6  ){
            
            JOptionPane.showMessageDialog(null, "Plz enter correct password(atleast 1 char and 1 number with 6 digits","Warning",JOptionPane.WARNING_MESSAGE);
            return;
            }
            
            if ( LabelerrorthrownForEmailId.isVisible() == true) {
                
              JOptionPane.showMessageDialog(null, "Email id is wrong","Error",JOptionPane.ERROR_MESSAGE);
              return;   
            
            }
            // RAJA - VALIDATION to select alteast one buttons
            
            if(check){
                if (RadioButtonDonor.isSelected() || RadioButtonreceiver.isSelected() || NGOCbx.isShowing() ) {
            
            
            User user = system.getUserDirectory().addUser();
            user.setUserName(JTextFielduserName.getText());
            user.setEmailId(TextFieldemailId.getText());
            user.setPassword(Fieldpassword.getText());
            user.setName(JTextFieldname.getText());

            if (RadioButtonDonor.isSelected() == true) {
                user.setType('d');
            } 
            else if  (RadioButtonreceiver.isSelected() == true){
                user.setType('r');
            }
            else {   
                
                if(NGOCbx.getSelectedItem() == "Liver NGO"){
                    Employee employee = system.getEmployeeDirectory().createEmployee(JTextFieldname.getText());
        UserAccount ua = system.getUserAccountDirectory().createUserAccount(JTextFielduserName.getText(), Fieldpassword.getText(), employee, new SystemAdminRole());
        
                    }
            
                else{
                    user.setType('a');
                    }
            }
            JOptionPane.showMessageDialog(null, "User Account has been created Successfully");
            TextFieldemailId.setText("");
            Fieldpassword.setText("");
            JTextFielduserName.setText("");
            JTextFieldname.setText("");
            }
            else {
            
            JOptionPane.showMessageDialog(null, "Please select a Donor or Receiver","Error",JOptionPane.ERROR_MESSAGE);
              return; 
            
            }
            }else{
                            JOptionPane.showMessageDialog(null, "pls verify your mail");

            }
            
                    dB4OUtil.storeSystem(system);

            
           }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_ButtonsignUpMousePressed
   
    private boolean checkUserIdExists(String userName) {
        try {
        if (system.getUserDirectory().checkIfUsernameIsUnique(userName)) {
            if (system.getUserAccountDirectory().checkIfUsernameIsUnique(userName)) {
                for (NGO ngo : system.getngoList()) {
                    for (Enterprise enterprise : ngo.getEnterpriseDirectory().getEnterpList()) {
                        if (enterprise.getUserAccountDirectory().checkIfUsernameIsUnique(userName)) {

                            for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                                return organization.getUserAccountDirectory().checkIfUsernameIsUnique(userName);

                            }

                        } else {
                            return false;

                        }
                    }
                }
            } else {
                return false;
            }
        } else {
            return false;
        }
       
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
         return false;
    }
    private void JTextFieldnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTextFieldnameFocusGained
        // TODO add your handling code here:
        JTextFieldname.setText("");
    }//GEN-LAST:event_JTextFieldnameFocusGained

    private void JTextFieldnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextFieldnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextFieldnameActionPerformed

    private void ButtonsignInMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonsignInMousePressed
        // TODO add your handling code here:
        // Get user name
        try {
        User user;
        System.out.println(system.getUserDirectory()+"Hi ra mams" + JTextFielduserName.getText()+" "+Fieldpassword.getText());
        user = system.getUserDirectory().authenticateUser(JTextFielduserName.getText(), Fieldpassword.getText());
        System.out.println(user+"this here");
        boolean close = false;
        if(user!=null){

            if (user.getType() == 'd') {

                DonorDashBoardJPanel donorPanel = new DonorDashBoardJPanel(dB4OUtil,system,user);
                //panel.add("DonorDashBoardJPanel",donorPanel);
                //CardLayout layout = (CardLayout) panel.getLayout();
                //layout.next(panel);
                //donorPanel.setVisible(true);
                donorPanel.show();
                close = true;

            } else if (user.getType() == 'r') {
                ReceiverDashBoardJPanel receiverPanel = new ReceiverDashBoardJPanel(dB4OUtil,system,user);
                receiverPanel.show();
                close = true;
            }
            
                
            
        }
        else{

            String userName = JTextFielduserName.getText();
            // Get Password
            char[] passwordCharArray = Fieldpassword.getPassword();
            String password = String.valueOf(passwordCharArray);
            System.out.println(system.getUserAccountDirectory());
            //Step1: Check in the system admin user account directory if you have the user
            UserAccount userAccount=system.getUserAccountDirectory().authenticateUser(userName, password);
            System.out.println(userAccount);
            System.out.println("nee mama");
            Enterprise inEnterprise=null;
            Organization inOrganization=null;
            NGO inNGO=null;

            if(userAccount==null){
                //Step 2: Go inside each ngo and check each enterprise
                
                for(NGO ngo:system.getngoList()){
                    //Step 2.a: check against each enterprise
                    if(ngo.getEnterpriseDirectory().getEnterpList() != null){
                    for(Enterprise enterprise:ngo.getEnterpriseDirectory().getEnterpList()){
                        userAccount=enterprise.getUserAccountDirectory().authenticateUser(userName, password);
                        if(userAccount==null){
                            //Step 3:check against each organization for each enterprise
                            for(Organization organization:enterprise.getOrganizationDirectory().getOrganizationList()){
                                userAccount=organization.getUserAccountDirectory().authenticateUser(userName, password);
                                if(userAccount!=null){
                                    inEnterprise=enterprise;
                                    inOrganization=organization;
                                    inNGO = ngo;
                                    break;
                                }
                            }

                        }
                        else{
                            inEnterprise=enterprise;
                            break;
                        }
                        if(inOrganization!=null){
                            break;
                        }
                    }
                    }
                    if(inEnterprise!=null){
                        break;
                    }
                }
            }

            if(userAccount==null){
                JOptionPane.showMessageDialog(null, "Invalid credentials");
                return;
            }
            else{
                System.out.println(inEnterprise);
                System.out.println("nee mama");
                System.out.println(userAccount.getRole());
                userAccount.getRole().createWorkArea(panel, userAccount, inOrganization, inEnterprise, system,dB4OUtil, inNGO);
                close = true;
            }
            
            if (close) {
                this.dispose();
            }
        }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_ButtonsignInMousePressed

    private void TextFieldemailIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextFieldemailIdKeyReleased
        // TODO add your handling code here:
        
        String patternForEmail = "^[a-zA-Z0-9_+&*-]+(?:\\."
                + "[a-zA-Z0-9_+&*-]+)*@"
                + "(?:[a-zA-Z0-9-]+\\.)+[a-z"
                + "A-Z]{2,7}$";
        String emailID = TextFieldemailId.getText();
        Pattern patternForEmailId = Pattern.compile(patternForEmail);
        Matcher matcherForEmailId = patternForEmailId.matcher(emailID);
        if (matcherForEmailId.matches() == false) {
            LabelerrorthrownForEmailId.setVisible(true);
        } else {
            LabelerrorthrownForEmailId.setVisible(false);
        }
    }//GEN-LAST:event_TextFieldemailIdKeyReleased

    private void FieldpasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FieldpasswordKeyReleased
        // TODO add your handling code here:
        if (Fieldpassword.getText().length() < 6) {
            LabelerrorthrownforerrorPassword.setVisible(true);
        } else {
            LabelerrorthrownforerrorPassword.setVisible(false);
        }
        
    }//GEN-LAST:event_FieldpasswordKeyReleased

    private void LabelTopsignUpMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelTopsignUpMousePressed
        // TODO add your handling code here:
        ButtonsignUp.setVisible(true);
        //signUpBottomTextBox.setVisible(true);
        ButtonsignIn.setVisible(false);
        //signInBottomTextBox.setVisible(false);
        TextFieldemailId.setVisible(true);
        emailIdJlabel.setVisible(true);
        verifyButton.setVisible(true);
        //emailIdSeparator.setVisible(true);
        RadioButtonDonor.setVisible(true);
        RadioButtonreceiver.setVisible(true);
        JTextFieldname.setVisible(true);
        //nameSeparator.setVisible(true);
        nameLabel.setVisible(true);
        LabelerrorthrownForEmailId.setVisible(false);
        LabelerrorthrownforerrorPassword.setVisible(false);
        NGOCbx.setVisible(false);
        btnverifyEmail.setVisible(true);
        txtVerifyCode.setVisible(true);
        jButton1.setVisible(false);
    }//GEN-LAST:event_LabelTopsignUpMousePressed

    private void LabeTopsignInMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabeTopsignInMousePressed
        // TODO add your handling code here:
        ButtonsignUp.setVisible(false);
        //signUpBottomTextBox.setVisible(false);
        TextFieldemailId.setVisible(false);
        emailIdJlabel.setVisible(false);
        // emailIdSeparator.setVisible(false);
        ButtonsignIn.setVisible(true);
        //signInBottomTextBox.setVisible(true);
        RadioButtonDonor.setVisible(false);
        RadioButtonreceiver.setVisible(false);
        JTextFieldname.setVisible(false);
        //nameSeparator.setVisible(false);
        nameLabel.setVisible(false);
        LabelerrorthrownForEmailId.setVisible(false);
        LabelerrorthrownforerrorPassword.setVisible(false);
        NGOCbx.setVisible(false);
        btnverifyEmail.setVisible(false);
        txtVerifyCode.setVisible(false);
        jButton1.setVisible(false);
        verifyButton.setVisible(false);

    }//GEN-LAST:event_LabeTopsignInMousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        RadioButtonDonor.setVisible(false);
        RadioButtonreceiver.setVisible(false);
        NGOCbx.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnverifyEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnverifyEmailActionPerformed
        // TODO add your handling code here:
       try {
           verificationCode = JavaMailUtil.getRandomCode();
//                logger.log(Level.INFO, "Sending email to new user");
                    JavaMailUtil.sendMail(TextFieldemailId.getText(), JTextFieldname.getText(),verificationCode);
//                      System.out.println()
           JOptionPane.showMessageDialog(this, "Verification Email sent");
                    
                } catch (Exception ex) {
                    
                }
    }//GEN-LAST:event_btnverifyEmailActionPerformed

    private void txtVerifyCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVerifyCodeActionPerformed
        if(verificationCode.equals(txtVerifyCode.getText())){
                       JOptionPane.showMessageDialog(this, " Email verified");
                       check=true;
        }else{
                       JOptionPane.showMessageDialog(this, " please enter correct code");
        }
        txtVerifyCode.setText("");
    }//GEN-LAST:event_txtVerifyCodeActionPerformed

    private void verifyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verifyButtonActionPerformed
        // TODO add your handling code here:
        txtVerifyCodeActionPerformed(evt);
    }//GEN-LAST:event_verifyButtonActionPerformed
        
    

public void setColor(JPanel panel)
 {
     panel.setBackground(new java.awt.Color(0, 0, 0));
 }
 
 public void resetColor(JPanel panel)
 {
     panel.setBackground(new java.awt.Color(171,204,61));
 }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ButtonsignIn;
    private javax.swing.JLabel ButtonsignUp;
    private javax.swing.JPasswordField Fieldpassword;
    private javax.swing.JTextField JTextFieldname;
    private javax.swing.JTextField JTextFielduserName;
    private javax.swing.JLabel LabeTopsignIn;
    private javax.swing.JLabel LabelTopsignUp;
    private javax.swing.JLabel LabelerrorthrownForEmailId;
    private javax.swing.JLabel LabelerrorthrownforerrorPassword;
    private javax.swing.JComboBox<String> NGOCbx;
    private javax.swing.JRadioButton RadioButtonDonor;
    private javax.swing.JRadioButton RadioButtonreceiver;
    private javax.swing.JTextField TextFieldemailId;
    private javax.swing.JLabel Titlelabel;
    private javax.swing.JLabel Usernamelabel;
    private javax.swing.JButton btnverifyEmail;
    private javax.swing.JLabel buttonsexit;
    private javax.swing.JLabel emailIdJlabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblBgd;
    private javax.swing.JLabel lblbgd;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JPanel panel;
    private javax.swing.JLabel passwordlabel6;
    private javax.swing.JTextField txtVerifyCode;
    private javax.swing.JPanel userProcessContainer;
    private javax.swing.JButton verifyButton;
    // End of variables declaration//GEN-END:variables

    

    
}
