/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Admin;


import Backend.Enterprise.Enterprise;
import static Backend.Enterprise.Enterprise.EnterpriseType.DeliveryDepartment;
import static Backend.Enterprise.Enterprise.EnterpriseType.HospitalDepartment;
import static Backend.Enterprise.Enterprise.EnterpriseType.LegalDepartment;
import static Backend.Enterprise.Enterprise.EnterpriseType.LimbsBank;
import Backend.Enterprise.LimbsBankEnterprise;
import Backend.Organization.DoctorOrganization;

import Backend.Organization.Organization;
import Backend.Organization.Organization.DeliveryType;
import Backend.Organization.Organization.HospitalType;
import Backend.Organization.Organization.LegalType;
import Backend.Organization.Organization.LimbsManType;
import Backend.Organization.Organization.Type;
import Backend.Organization.OrganizationDirectory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nehar
 */
public class ManageOrgsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageEnterpriseJPanel
     */
    private OrganizationDirectory directory;
    private Enterprise enterprise;
    
    public ManageOrgsJPanel(OrganizationDirectory directory,Enterprise enterprise) {
        initComponents();
       this.directory = directory ;
        this.enterprise = enterprise;
        entNmtxt.setText(enterprise.getName());
        populateCombo();
        populateTable();
    }
    private void populateCombo() {
        
        orgcmbox.removeAllItems();
        System.out.println(enterprise.getEnterpriseType());
        if(enterprise.getEnterpriseType().equals(LegalDepartment)){
        for(Organization.LegalType legalType: Organization.LegalType.values()){
            if (legalType.getValue().equals(Organization.LegalType.Advocate.getValue())){
                orgcmbox.addItem(legalType);
            }
        }
        }
        else if(enterprise.getEnterpriseType().equals(DeliveryDepartment)){
        for(Organization.DeliveryType DeliveryType: Organization.DeliveryType.values()){
            if (DeliveryType.getValue().equals(Organization.DeliveryType.Delivery.getValue())){
                orgcmbox.addItem(DeliveryType);
            }
        }
        }
        else if(enterprise.getEnterpriseType().equals(LimbsBank)){
        for(Organization.Type type : Organization.Type.values()){
            if (type.getValue().equals(Organization.Type.LimbsManufacturer.getValue())
                    || type.getValue().equals(Organization.Type.Coordinator.getValue()) ||
                    type.getValue().equals(Organization.Type.Doctor.getValue()) ||
                    type.getValue().equals(Organization.Type.Delivery.getValue())){
                orgcmbox.addItem(type);
            }
        }
        }
        else if(enterprise.getEnterpriseType().equals(HospitalDepartment)){
        for(Organization.HospitalType HospitalType: Organization.HospitalType.values()){
            if (HospitalType.getValue().equals(Organization.HospitalType.Doctor.getValue())){
                orgcmbox.addItem(HospitalType);
            }
        }
        }else{
        for (Organization.Type type : Organization.Type.values()){            
            if (type.getValue().equals(Organization.Type.Coordinator.getValue())
                    ||type.getValue().equals(Organization.Type.Doctor.getValue())
                    ||type.getValue().equals(Organization.Type.InventoryManager.getValue())
                    ||type.getValue().equals(Organization.Type.Lab.getValue()) || type.getValue().equals(Organization.Type.LimbsManufacturer.getValue()))
                orgcmbox.addItem(type);
        }
    }
    }
private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) organizationJTable.getModel();
        
        model.setRowCount(0);
        
        for (Organization organization : directory.getOrganizationList()){
            Object[] row = new Object[3];
            row[0] = organization.getOrganizationID();
            row[1] = organization.getName();
            row[2] = organization.getOrgName();
            
            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tltlabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        srlpn1 = new javax.swing.JScrollPane();
        organizationJTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        orglabel = new javax.swing.JLabel();
        orgcmbox = new javax.swing.JComboBox();
        NmofOrg = new javax.swing.JLabel();
        organizationnmlbl = new javax.swing.JTextField();
        addOrganizationbtn = new javax.swing.JButton();
        entNmtxt = new javax.swing.JTextField();
        nameentlabel = new javax.swing.JLabel();
        bgdimg = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(null);
        setMinimumSize(null);
        setPreferredSize(null);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tltlabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        tltlabel.setForeground(new java.awt.Color(255, 255, 255));
        tltlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tltlabel.setText("Organization Creation");
        add(tltlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 50));

        jPanel1.setBackground(new java.awt.Color(55, 96, 128));

        organizationJTable.setAutoCreateRowSorter(true);
        organizationJTable.setBackground(new java.awt.Color(204, 204, 204));
        organizationJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Name", "Organization"
            }
        ));
        srlpn1.setViewportView(organizationJTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(srlpn1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 633, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(srlpn1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, -1, 120));

        jPanel2.setBackground(new java.awt.Color(8, 21, 49));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel2.setPreferredSize(new java.awt.Dimension(250, 400));
        jPanel2.setRequestFocusEnabled(false);
        jPanel2.setVerifyInputWhenFocusTarget(false);

        orglabel.setBackground(new java.awt.Color(0, 0, 0));
        orglabel.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        orglabel.setForeground(new java.awt.Color(255, 255, 255));
        orglabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        orglabel.setText("Organization");

        orgcmbox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        orgcmbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orgcmboxActionPerformed(evt);
            }
        });

        NmofOrg.setBackground(new java.awt.Color(255, 255, 255));
        NmofOrg.setFont(new java.awt.Font("Dubai Medium", 0, 12)); // NOI18N
        NmofOrg.setForeground(new java.awt.Color(255, 255, 255));
        NmofOrg.setText("Organization Name");

        organizationnmlbl.setBorder(null);
        organizationnmlbl.setCaretColor(new java.awt.Color(30, 59, 92));
        organizationnmlbl.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                organizationnmlblFocusGained(evt);
            }
        });
        organizationnmlbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                organizationnmlblActionPerformed(evt);
            }
        });

        addOrganizationbtn.setFont(new java.awt.Font("Dubai Medium", 0, 12)); // NOI18N
        addOrganizationbtn.setText("CREATE");
        addOrganizationbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOrganizationbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(orglabel, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(organizationnmlbl)
                    .addComponent(addOrganizationbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                    .addComponent(NmofOrg, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                    .addComponent(orgcmbox, 0, 202, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(orglabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(orgcmbox, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(NmofOrg, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(organizationnmlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addOrganizationbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, 240));

        entNmtxt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        entNmtxt.setBorder(null);
        entNmtxt.setCaretColor(new java.awt.Color(30, 59, 92));
        entNmtxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                entNmtxtFocusGained(evt);
            }
        });
        entNmtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entNmtxtActionPerformed(evt);
            }
        });
        add(entNmtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 140, 30));

        nameentlabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        nameentlabel.setForeground(new java.awt.Color(255, 255, 255));
        nameentlabel.setText("Enterprise Name");
        nameentlabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(nameentlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 110, 30));

        bgdimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/admin_management.jpg"))); // NOI18N
        bgdimg.setMaximumSize(null);
        bgdimg.setMinimumSize(null);
        bgdimg.setPreferredSize(null);
        bgdimg.setRequestFocusEnabled(false);
        add(bgdimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void organizationnmlblFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_organizationnmlblFocusGained
        // TODO add your handling code here:
        organizationnmlbl.setText("");
    }//GEN-LAST:event_organizationnmlblFocusGained

    private void organizationnmlblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_organizationnmlblActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_organizationnmlblActionPerformed

    private void addOrganizationbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOrganizationbtnActionPerformed
        // TODO add your handling code here:
        //directory.createDonorBankOrganization((Type)organizationComboBox.getSelectedItem());
        
        
        if (organizationnmlbl.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Organization name cannot be empty");
            return;
        }

        for (Organization organization : directory.getOrganizationList()) {

            if (organization.getOrgName().equals(organizationnmlbl.getText())) {

                JOptionPane.showMessageDialog(null, "Organization name already Exists");
                return;
            }
            
          

        }

        if(enterprise.getEnterpriseType().equals(LegalDepartment)){
            Organization o = directory.createLegalOrganization((LegalType)orgcmbox.getSelectedItem());
            o.setOrgName(organizationnmlbl.getText());
            populateTable(); 
            JOptionPane.showMessageDialog(null, "Organization created ");
        }
        else if(enterprise.getEnterpriseType().equals(DeliveryDepartment)){
            Organization o = directory.createDeliveryOrganization((DeliveryType)orgcmbox.getSelectedItem());
            
            
            o.setOrgName(organizationnmlbl.getText());
            populateTable(); 
            JOptionPane.showMessageDialog(null, "Organization created ");
        }
        else if(enterprise.getEnterpriseType().equals(HospitalDepartment)){
            Organization o = directory.createHospitalOrganization((HospitalType)orgcmbox.getSelectedItem());
            o.setOrgName(organizationnmlbl.getText());
            populateTable(); 
            JOptionPane.showMessageDialog(null, "Organization created ");
        }
        else if(enterprise.getEnterpriseType().equals(LimbsBank)){
            Organization o = directory.createLimbsManufacturerOrganization((Type)orgcmbox.getSelectedItem());
            System.out.println(organizationnmlbl.getText());
            o.setOrgName(organizationnmlbl.getText());
            populateTable();
            JOptionPane.showMessageDialog(null, "Organization created ");
        }
        else{
            Organization o = directory.createDonorBankOrganization((Type)orgcmbox.getSelectedItem());
            o.setOrgName(organizationnmlbl.getText());
            JOptionPane.showMessageDialog(null, "Organization created ");
            orgcmbox.removeItem(orgcmbox.getSelectedItem());
            populateTable();
        }
        
        organizationnmlbl.setText("");
    }//GEN-LAST:event_addOrganizationbtnActionPerformed

    private void entNmtxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_entNmtxtFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_entNmtxtFocusGained

    private void entNmtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entNmtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entNmtxtActionPerformed

    private void orgcmboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orgcmboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_orgcmboxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NmofOrg;
    private javax.swing.JButton addOrganizationbtn;
    private javax.swing.JLabel bgdimg;
    private javax.swing.JTextField entNmtxt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel nameentlabel;
    private javax.swing.JTable organizationJTable;
    private javax.swing.JTextField organizationnmlbl;
    private javax.swing.JComboBox orgcmbox;
    private javax.swing.JLabel orglabel;
    private javax.swing.JScrollPane srlpn1;
    private javax.swing.JLabel tltlabel;
    // End of variables declaration//GEN-END:variables

   
}
