/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Coordinator;

import Backend.DB4OUtil.DB4OUtil;
import Backend.EcoSystem;
import Backend.Enterprise.Enterprise;
import Backend.Organization.CoordinatorOrganization;
import Backend.Organization.Organization;
import Backend.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JPanel;
import static javax.swing.SwingUtilities.getWindowAncestor;
import org.jdesktop.swingx.JXFrame;

/**
 *
 * @author Arun Balasubramanian
 */
public class CoordinatorDashBoardJPanel extends javax.swing.JFrame {

    /**
     * Creates new form CoordinatorDashBoardJPanel
     */
    private EcoSystem system;
    private Enterprise enterprise ;
    private DB4OUtil dB4OUtil;
    private UserAccount userAccount;
     private CoordinatorOrganization coordinator;

    public CoordinatorDashBoardJPanel(UserAccount account, Organization organization, EcoSystem system,DB4OUtil dB4OUtil , Enterprise enterprise) {
        initComponents();
        this.enterprise = enterprise ;
        this.dB4OUtil = dB4OUtil;
        this.system = system;
        this.userAccount =account;
        this.coordinator = (CoordinatorOrganization)organization;
          setColor(mngprf);
        resetColor(new JPanel[]{reqmng});
        ManageCoordinatorDetailsJPanel coUserPanel = new ManageCoordinatorDetailsJPanel(userAccount,system,coordinator,enterprise);
        userProcessContainer.add("ManageCoordinatorDetailsJPanel",coUserPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer); 
        this.setExtendedState(JXFrame.MAXIMIZED_BOTH);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane4 = new javax.swing.JSplitPane();
        admang = new javax.swing.JPanel();
        reqmng = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        mngprf = new javax.swing.JPanel();
        lbl = new javax.swing.JLabel();
        userProcessContainer = new javax.swing.JPanel();

        setMaximumSize(null);
        setMinimumSize(null);
        setUndecorated(true);
        setPreferredSize(null);
        getContentPane().setLayout(new java.awt.GridLayout(1, 1));

        jSplitPane4.setBackground(new java.awt.Color(55, 96, 128));
        jSplitPane4.setDividerSize(0);

        admang.setBackground(new java.awt.Color(3, 15, 43));
        admang.setForeground(new java.awt.Color(255, 255, 255));
        admang.setPreferredSize(new java.awt.Dimension(157, 680));

        reqmng.setBackground(new java.awt.Color(3, 15, 43));
        reqmng.setForeground(new java.awt.Color(255, 255, 255));
        reqmng.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                reqmngMousePressed(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(3, 15, 43));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/request x 32.png"))); // NOI18N
        jLabel10.setText(" Requests");

        javax.swing.GroupLayout reqmngLayout = new javax.swing.GroupLayout(reqmng);
        reqmng.setLayout(reqmngLayout);
        reqmngLayout.setHorizontalGroup(
            reqmngLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reqmngLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        reqmngLayout.setVerticalGroup(
            reqmngLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reqmngLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        back.setBackground(new java.awt.Color(3, 15, 43));
        back.setFont(new java.awt.Font("Dubai Medium", 0, 12)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logoutx32.png"))); // NOI18N
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                backMousePressed(evt);
            }
        });

        mngprf.setBackground(new java.awt.Color(3, 15, 43));
        mngprf.setForeground(new java.awt.Color(255, 255, 255));
        mngprf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mngprfMousePressed(evt);
            }
        });

        lbl.setBackground(new java.awt.Color(3, 15, 43));
        lbl.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl.setForeground(new java.awt.Color(255, 255, 255));
        lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/account x 32.png"))); // NOI18N
        lbl.setText("Profile");

        javax.swing.GroupLayout mngprfLayout = new javax.swing.GroupLayout(mngprf);
        mngprf.setLayout(mngprfLayout);
        mngprfLayout.setHorizontalGroup(
            mngprfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mngprfLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        mngprfLayout.setVerticalGroup(
            mngprfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mngprfLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout admangLayout = new javax.swing.GroupLayout(admang);
        admang.setLayout(admangLayout);
        admangLayout.setHorizontalGroup(
            admangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(reqmng, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mngprf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        admangLayout.setVerticalGroup(
            admangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(admangLayout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(mngprf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addComponent(reqmng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95)
                .addComponent(back)
                .addContainerGap(306, Short.MAX_VALUE))
        );

        jSplitPane4.setLeftComponent(admang);

        userProcessContainer.setBackground(new java.awt.Color(3, 15, 43));
        userProcessContainer.setLayout(new java.awt.CardLayout());
        jSplitPane4.setRightComponent(userProcessContainer);

        getContentPane().add(jSplitPane4);
    }// </editor-fold>//GEN-END:initComponents

    private void reqmngMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reqmngMousePressed
        // TODO add your handling code here:
        setColor(reqmng);
        resetColor(new JPanel[]{mngprf});
        CoordinatorManageRequestsJPanel coUserPanel = new CoordinatorManageRequestsJPanel(userProcessContainer,userAccount,coordinator,system,enterprise);
        userProcessContainer.add("CoordinatorAssistantWorkAreaJPanel",coUserPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_reqmngMousePressed

    private void backMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMousePressed
        // TODO add your handling code here:
        this.dispose();
        dB4OUtil.storeSystem(system);
    }//GEN-LAST:event_backMousePressed

    private void mngprfMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mngprfMousePressed
        // TODO add your handling code here:
        setColor(mngprf);
        resetColor(new JPanel[]{reqmng});
        ManageCoordinatorDetailsJPanel coUserPanel = new ManageCoordinatorDetailsJPanel(userAccount,system,coordinator,enterprise);
        userProcessContainer.add("ManageCoordinatorDetailsJPanel",coUserPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_mngprfMousePressed

 private void setColor(JPanel pane)
    {
        pane.setBackground(new Color(50, 62, 168));
    }
    private void resetColor(JPanel [] pane)
    {
        for(int i=0;i<pane.length;i++){
           pane[i].setBackground(new Color(23,35,51));
           
        } 
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel admang;
    private javax.swing.JLabel back;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JSplitPane jSplitPane4;
    private javax.swing.JLabel lbl;
    private javax.swing.JPanel mngprf;
    private javax.swing.JPanel reqmng;
    private javax.swing.JPanel userProcessContainer;
    // End of variables declaration//GEN-END:variables
}
