/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.LabAssistant;

import Backend.Enterprise.Enterprise;
import Backend.Organization.InventoryManagerOrganization;
import Backend.Organization.Organization;
import Backend.UserAccount.UserAccount;
import Backend.WorkQueue.CoordinatorTestWorkRequest;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Date;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author harish
 */
public class AnalyseRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageUsersJPanel
     */
     private CoordinatorTestWorkRequest request ;
    private Enterprise enterprise ;
    private UserAccount userAccount;
    public AnalyseRequestJPanel(CoordinatorTestWorkRequest request , Enterprise enterprise,UserAccount userAccount) {
        initComponents();
        this.request = request ; 
        this.enterprise = enterprise ;
        this.userAccount = userAccount;
        btnaprv.setEnabled(false);
        btnrejt.setEnabled(false);
        ButtonGroup bloodTest = new ButtonGroup();
        bloodTest.add(rbtnbldtestfail);
        bloodTest.add(rbtnbldtstpas);
        
        
        ButtonGroup tissueTest = new ButtonGroup();
        tissueTest.add(rbtntissuepas);
        tissueTest.add(rbtntissuefail);
        
        ButtonGroup psychiatricTest = new ButtonGroup();
        psychiatricTest.add(rbtnpsychfail);
        psychiatricTest.add(rbtnpsychpas);
        
        ButtonGroup xrayTest = new ButtonGroup();
        xrayTest.add(rbtntissuepas);
        xrayTest.add(rbtnxrayfail);
        
        ButtonGroup antiBodyTest = new ButtonGroup();
        antiBodyTest.add(rbtnantibdfail);
        antiBodyTest.add(rbtnantibdpas);
        
        ButtonGroup ArteriogramTest = new ButtonGroup();
        ArteriogramTest.add(rbtnarteriogfail);
        ArteriogramTest.add(rbtnarteriogenpas);
        
            
        ButtonGroup urineTest = new ButtonGroup();
        urineTest.add(rbtnurinefail);
        urineTest.add(rbtnurinepas);
        
        populateDefault();
    }
    

    private void populateDefault() {
      nametext.setText(userAccount.getEmployee().getName());
      conttext.setText(userAccount.getEmployee().getPhoneNumber()+"");
      dateobtext.setText(userAccount.getEmployee().getDOB().toString());
      txtgend.setText(userAccount.getEmployee().getGender());      
      txtemercont.setText(userAccount.getEmployee().getEmergencyPhoneNumber()+ "");
      btnaprv.setEnabled(false);
      btnrejt.setEnabled(false);
    if(userAccount.getEmployee().getdP() !=null){
        //Working line
         byte[] JLabelpictureLabel = userAccount.getEmployee().getdP();
        ImageIcon i = setPicturebyte(JLabelpictureLabel);
        lblphoto.setIcon(i);
        }
        else{
            System.err.println("No Image");
        }
    }
  private ImageIcon setPicturebyte(byte[] byteArrayImage){

        ImageIcon imageCar;
        imageCar = new ImageIcon(byteArrayImage);
        Image picCar = imageCar.getImage();
        JLabel pictureLabel1 = new JLabel();
        pictureLabel1.setSize(107, 133);
        Image resizedImage = picCar.getScaledInstance(pictureLabel1.getWidth(), pictureLabel1.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon selectedCarPicture = new ImageIcon(resizedImage);
        return selectedCarPicture;  
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mandtestslabel = new javax.swing.JLabel();
        rbtnbldtestfail = new javax.swing.JRadioButton();
        rbtntissuepas = new javax.swing.JRadioButton();
        rbtntissuefail = new javax.swing.JRadioButton();
        rbtnpsychpas = new javax.swing.JRadioButton();
        rbtnpsychfail = new javax.swing.JRadioButton();
        rbtnxraypas = new javax.swing.JRadioButton();
        rbtnxrayfail = new javax.swing.JRadioButton();
        rbtnantibdpas = new javax.swing.JRadioButton();
        rbtnantibdfail = new javax.swing.JRadioButton();
        rbtnarteriogenpas = new javax.swing.JRadioButton();
        lblbldtest = new javax.swing.JLabel();
        lbltissue = new javax.swing.JLabel();
        lblpsych = new javax.swing.JLabel();
        rbtnarteriogfail = new javax.swing.JRadioButton();
        lblxray = new javax.swing.JLabel();
        lblantibdy = new javax.swing.JLabel();
        lblarteriogy = new javax.swing.JLabel();
        rbtnbldtstpas = new javax.swing.JRadioButton();
        lblurine = new javax.swing.JLabel();
        rbtnurinepas = new javax.swing.JRadioButton();
        rbtnurinefail = new javax.swing.JRadioButton();
        btnrejt = new javax.swing.JButton();
        btnaprv = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblgend = new javax.swing.JLabel();
        nametext = new javax.swing.JTextField();
        doblabel = new javax.swing.JLabel();
        lblname = new javax.swing.JLabel();
        conttext = new javax.swing.JTextField();
        contlabel = new javax.swing.JLabel();
        emercontlabel = new javax.swing.JLabel();
        txtemercont = new javax.swing.JTextField();
        lblphoto = new javax.swing.JLabel();
        dateobtext = new javax.swing.JTextField();
        txtgend = new javax.swing.JTextField();
        btnsubt = new javax.swing.JButton();
        headerlabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt = new javax.swing.JTextArea();
        bgdImg = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(890, 539));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 8, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        mandtestslabel.setFont(new java.awt.Font("Dubai Medium", 1, 13)); // NOI18N
        mandtestslabel.setForeground(new java.awt.Color(255, 255, 255));
        mandtestslabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mandtestslabel.setText("Mandatory Tests");

        rbtnbldtestfail.setBackground(new java.awt.Color(55, 96, 128));
        rbtnbldtestfail.setForeground(new java.awt.Color(255, 255, 255));
        rbtnbldtestfail.setText("No");
        rbtnbldtestfail.setBorder(null);

        rbtntissuepas.setBackground(new java.awt.Color(55, 96, 128));
        rbtntissuepas.setForeground(new java.awt.Color(255, 255, 255));
        rbtntissuepas.setText("Pass");
        rbtntissuepas.setBorder(null);

        rbtntissuefail.setBackground(new java.awt.Color(55, 96, 128));
        rbtntissuefail.setForeground(new java.awt.Color(255, 255, 255));
        rbtntissuefail.setText("No");
        rbtntissuefail.setBorder(null);

        rbtnpsychpas.setBackground(new java.awt.Color(55, 96, 128));
        rbtnpsychpas.setForeground(new java.awt.Color(255, 255, 255));
        rbtnpsychpas.setText("Pass");
        rbtnpsychpas.setBorder(null);

        rbtnpsychfail.setBackground(new java.awt.Color(55, 96, 128));
        rbtnpsychfail.setForeground(new java.awt.Color(255, 255, 255));
        rbtnpsychfail.setText("No");
        rbtnpsychfail.setBorder(null);

        rbtnxraypas.setBackground(new java.awt.Color(55, 96, 128));
        rbtnxraypas.setForeground(new java.awt.Color(255, 255, 255));
        rbtnxraypas.setText("Pass");
        rbtnxraypas.setBorder(null);

        rbtnxrayfail.setBackground(new java.awt.Color(55, 96, 128));
        rbtnxrayfail.setForeground(new java.awt.Color(255, 255, 255));
        rbtnxrayfail.setText("No");
        rbtnxrayfail.setBorder(null);

        rbtnantibdpas.setBackground(new java.awt.Color(55, 96, 128));
        rbtnantibdpas.setForeground(new java.awt.Color(255, 255, 255));
        rbtnantibdpas.setText("Pass");
        rbtnantibdpas.setBorder(null);

        rbtnantibdfail.setBackground(new java.awt.Color(55, 96, 128));
        rbtnantibdfail.setForeground(new java.awt.Color(255, 255, 255));
        rbtnantibdfail.setText("No");
        rbtnantibdfail.setBorder(null);

        rbtnarteriogenpas.setBackground(new java.awt.Color(55, 96, 128));
        rbtnarteriogenpas.setForeground(new java.awt.Color(255, 255, 255));
        rbtnarteriogenpas.setText("Pass");
        rbtnarteriogenpas.setBorder(null);

        lblbldtest.setFont(new java.awt.Font("Dubai Medium", 0, 13)); // NOI18N
        lblbldtest.setForeground(new java.awt.Color(255, 255, 255));
        lblbldtest.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblbldtest.setText("Blood Test");

        lbltissue.setFont(new java.awt.Font("Dubai Medium", 0, 13)); // NOI18N
        lbltissue.setForeground(new java.awt.Color(255, 255, 255));
        lbltissue.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbltissue.setText("Tissue ");

        lblpsych.setFont(new java.awt.Font("Dubai Medium", 0, 13)); // NOI18N
        lblpsych.setForeground(new java.awt.Color(255, 255, 255));
        lblpsych.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblpsych.setText("Psychiatric");

        rbtnarteriogfail.setBackground(new java.awt.Color(55, 96, 128));
        rbtnarteriogfail.setForeground(new java.awt.Color(255, 255, 255));
        rbtnarteriogfail.setText("No");
        rbtnarteriogfail.setBorder(null);

        lblxray.setFont(new java.awt.Font("Dubai Medium", 0, 13)); // NOI18N
        lblxray.setForeground(new java.awt.Color(255, 255, 255));
        lblxray.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblxray.setText("Xray ");

        lblantibdy.setFont(new java.awt.Font("Dubai Medium", 0, 13)); // NOI18N
        lblantibdy.setForeground(new java.awt.Color(255, 255, 255));
        lblantibdy.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblantibdy.setText("Anti Body");

        lblarteriogy.setFont(new java.awt.Font("Dubai Medium", 0, 13)); // NOI18N
        lblarteriogy.setForeground(new java.awt.Color(255, 255, 255));
        lblarteriogy.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblarteriogy.setText("Arteriogram");

        rbtnbldtstpas.setBackground(new java.awt.Color(55, 96, 128));
        rbtnbldtstpas.setForeground(new java.awt.Color(255, 255, 255));
        rbtnbldtstpas.setText("Pass");
        rbtnbldtstpas.setBorder(null);
        rbtnbldtstpas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnbldtstpasActionPerformed(evt);
            }
        });

        lblurine.setFont(new java.awt.Font("Dubai Medium", 0, 13)); // NOI18N
        lblurine.setForeground(new java.awt.Color(255, 255, 255));
        lblurine.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblurine.setText("Urine");

        rbtnurinepas.setBackground(new java.awt.Color(55, 96, 128));
        rbtnurinepas.setForeground(new java.awt.Color(255, 255, 255));
        rbtnurinepas.setText("Pass");
        rbtnurinepas.setBorder(null);

        rbtnurinefail.setBackground(new java.awt.Color(55, 96, 128));
        rbtnurinefail.setForeground(new java.awt.Color(255, 255, 255));
        rbtnurinefail.setText("No");
        rbtnurinefail.setBorder(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblbldtest, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(rbtnbldtstpas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17)
                                .addComponent(rbtnbldtestfail, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblxray, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(rbtnxraypas)
                                .addGap(18, 18, 18)
                                .addComponent(rbtnxrayfail))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblantibdy, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(rbtnantibdpas)
                                .addGap(18, 18, 18)
                                .addComponent(rbtnantibdfail))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblarteriogy, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(rbtnarteriogenpas)
                                .addGap(18, 18, 18)
                                .addComponent(rbtnarteriogfail))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblurine, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(rbtnurinepas)
                                .addGap(18, 18, 18)
                                .addComponent(rbtnurinefail))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbltissue, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblpsych, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(45, 45, 45)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(rbtnpsychpas)
                                        .addGap(18, 18, 18)
                                        .addComponent(rbtnpsychfail))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(rbtntissuepas)
                                        .addGap(18, 18, 18)
                                        .addComponent(rbtntissuefail))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(mandtestslabel, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {rbtnantibdfail, rbtnantibdpas, rbtnarteriogenpas, rbtnarteriogfail, rbtnbldtestfail, rbtnbldtstpas, rbtnpsychfail, rbtnpsychpas, rbtntissuefail, rbtntissuepas, rbtnurinefail, rbtnurinepas, rbtnxrayfail, rbtnxraypas});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblantibdy, lblarteriogy, lblbldtest, lblpsych, lbltissue, lblurine, lblxray});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mandtestslabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblbldtest, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtnbldtstpas, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbtnbldtestfail, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbltissue, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtntissuepas)
                            .addComponent(rbtntissuefail))))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblpsych, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtnpsychpas)
                            .addComponent(rbtnpsychfail))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblxray, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtnxraypas)
                            .addComponent(rbtnxrayfail))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblantibdy, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtnantibdpas)
                            .addComponent(rbtnantibdfail))))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblarteriogy, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtnarteriogenpas)
                            .addComponent(rbtnarteriogfail))))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblurine, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtnurinepas)
                            .addComponent(rbtnurinefail))))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {rbtnantibdfail, rbtnantibdpas, rbtnarteriogenpas, rbtnarteriogfail, rbtnbldtestfail, rbtnbldtstpas, rbtnpsychfail, rbtnpsychpas, rbtntissuefail, rbtntissuepas, rbtnurinefail, rbtnurinepas, rbtnxrayfail, rbtnxraypas});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblantibdy, lblarteriogy, lblbldtest, lblpsych, lbltissue, lblurine, lblxray});

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, -1, -1));

        btnrejt.setBackground(new java.awt.Color(0, 8, 51));
        btnrejt.setFont(new java.awt.Font("Dubai Medium", 0, 13)); // NOI18N
        btnrejt.setForeground(new java.awt.Color(255, 255, 255));
        btnrejt.setText("Reject");
        btnrejt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrejtActionPerformed(evt);
            }
        });
        add(btnrejt, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 500, 93, -1));

        btnaprv.setBackground(new java.awt.Color(0, 8, 51));
        btnaprv.setFont(new java.awt.Font("Dubai Medium", 0, 13)); // NOI18N
        btnaprv.setForeground(new java.awt.Color(255, 255, 255));
        btnaprv.setText("Approve");
        btnaprv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaprvActionPerformed(evt);
            }
        });
        add(btnaprv, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 500, 93, -1));

        jPanel2.setBackground(new java.awt.Color(0, 8, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        lblgend.setBackground(new java.awt.Color(255, 255, 255));
        lblgend.setFont(new java.awt.Font("Dubai Medium", 0, 13)); // NOI18N
        lblgend.setForeground(new java.awt.Color(255, 255, 255));
        lblgend.setText("Gender");

        nametext.setBorder(null);
        nametext.setCaretColor(new java.awt.Color(30, 59, 92));
        nametext.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nametextFocusGained(evt);
            }
        });
        nametext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nametextActionPerformed(evt);
            }
        });

        doblabel.setBackground(new java.awt.Color(255, 255, 255));
        doblabel.setFont(new java.awt.Font("Dubai Medium", 0, 13)); // NOI18N
        doblabel.setForeground(new java.awt.Color(255, 255, 255));
        doblabel.setText("Date of Birth");

        lblname.setBackground(new java.awt.Color(255, 255, 255));
        lblname.setFont(new java.awt.Font("Dubai Medium", 0, 13)); // NOI18N
        lblname.setForeground(new java.awt.Color(255, 255, 255));
        lblname.setText("Name");

        conttext.setBorder(null);
        conttext.setCaretColor(new java.awt.Color(30, 59, 92));
        conttext.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                conttextFocusGained(evt);
            }
        });
        conttext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conttextActionPerformed(evt);
            }
        });

        contlabel.setBackground(new java.awt.Color(255, 255, 255));
        contlabel.setFont(new java.awt.Font("Dubai Medium", 0, 13)); // NOI18N
        contlabel.setForeground(new java.awt.Color(255, 255, 255));
        contlabel.setText("Contact");

        emercontlabel.setBackground(new java.awt.Color(255, 255, 255));
        emercontlabel.setFont(new java.awt.Font("Dubai Medium", 0, 13)); // NOI18N
        emercontlabel.setForeground(new java.awt.Color(255, 255, 255));
        emercontlabel.setText("Emergency Contact");

        txtemercont.setBorder(null);
        txtemercont.setCaretColor(new java.awt.Color(30, 59, 92));
        txtemercont.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtemercontFocusGained(evt);
            }
        });
        txtemercont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemercontActionPerformed(evt);
            }
        });

        lblphoto.setBackground(new java.awt.Color(255, 255, 255));
        lblphoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblphoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        dateobtext.setBorder(null);

        txtgend.setBorder(null);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contlabel)
                    .addComponent(conttext, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblname)
                    .addComponent(nametext, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doblabel, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblgend, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(emercontlabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtemercont, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblphoto, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateobtext, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtgend, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblphoto, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(lblname)
                .addGap(6, 6, 6)
                .addComponent(nametext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(contlabel)
                .addGap(6, 6, 6)
                .addComponent(conttext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(doblabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dateobtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(lblgend)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtgend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(emercontlabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtemercont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 60, -1, -1));

        btnsubt.setBackground(new java.awt.Color(0, 8, 51));
        btnsubt.setFont(new java.awt.Font("Dubai Medium", 0, 13)); // NOI18N
        btnsubt.setForeground(new java.awt.Color(255, 255, 255));
        btnsubt.setText("Submit ");
        btnsubt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubtActionPerformed(evt);
            }
        });
        add(btnsubt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 560, 450, 30));

        headerlabel.setBackground(new java.awt.Color(0, 0, 0));
        headerlabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        headerlabel.setForeground(new java.awt.Color(255, 255, 255));
        headerlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerlabel.setText("Analyse Requests");
        add(headerlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 50));

        txt.setBackground(new java.awt.Color(0, 8, 51));
        txt.setColumns(20);
        txt.setForeground(new java.awt.Color(255, 255, 255));
        txt.setRows(5);
        txt.setAutoscrolls(false);
        jScrollPane1.setViewportView(txt);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 600, 450, 180));

        bgdImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/drug_assistant.png"))); // NOI18N
        add(bgdImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 800));
    }// </editor-fold>//GEN-END:initComponents

    private void btnaprvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaprvActionPerformed
        // TODO add your handling code here:
        btnaprv.setEnabled(false);
        btnsubt.setEnabled(true);
        Organization org = null;
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
            if (organization instanceof InventoryManagerOrganization) {
                org = organization;
                break;
            }
        }
        
        if (org != null) {
            request.setLabStatus("Completed");
            org.getWorkQueue().getWorkRequestList().add(request);
            request.setActionDate(new Date());
            JOptionPane.showMessageDialog(null, "Request Approved", "Info", JOptionPane.INFORMATION_MESSAGE);
            
            if (request.getUser().getType() == 'd') {
                request.setOverallStatus("Request Approved by Lab Assistant , Waiting for potential Receiver");
                request.setInventStatus("in inventory");
            }
            else {
                 request.setOverallStatus("Request Approved by Lab Assistant , Waiting for potential Donor");
                 request.setInventStatus("in inventory");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Organization not present", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        
        
        
    }//GEN-LAST:event_btnaprvActionPerformed

    private void nametextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nametextFocusGained
        // TODO add your handling code here:
        nametext.setText("");
    }//GEN-LAST:event_nametextFocusGained

    private void nametextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nametextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nametextActionPerformed

    private void conttextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_conttextFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_conttextFocusGained

    private void conttextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conttextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_conttextActionPerformed

    private void txtemercontFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtemercontFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemercontFocusGained

    private void txtemercontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemercontActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemercontActionPerformed

    private void btnsubtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubtActionPerformed
        // TODO add your handling code here:

         javax.swing.Timer timer3 = new javax.swing.Timer(0, new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    String text = "\nStarting a new Process............................";
                    txt.append(text);
                    txt.setCaretPosition(txt.getText().length());
                        ((javax.swing.Timer)e.getSource()).stop();
                }
            });
            timer3.start();  
        javax.swing.Timer timer = new javax.swing.Timer(1000, new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    String text = "\nProcessing the Tests ...............";
                    txt.append(text);
                    txt.setCaretPosition(txt.getText().length());
                        ((javax.swing.Timer)e.getSource()).stop();
                }
            });
            timer.start();  
            
             javax.swing.Timer timer1 = new javax.swing.Timer(4000, new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    String text = "\nValidating the Tests .............";
                    txt.append(text);
                    txt.setCaretPosition(txt.getText().length());
                        ((javax.swing.Timer)e.getSource()).stop();
                }
            });
            timer1.start();    
        if (rbtnbldtstpas.isSelected() && rbtntissuepas.isSelected() && rbtnpsychpas.isSelected()
            && rbtnantibdpas.isSelected() && rbtnarteriogenpas.isSelected()
            && rbtnurinepas.isSelected()&&rbtnxraypas.isSelected()) { 
          javax.swing.Timer timer2 = new javax.swing.Timer(6000, new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    String text = "\nYou can approve the request!";
                    txt.append(text);
                    txt.setCaretPosition(txt.getText().length());
                        ((javax.swing.Timer)e.getSource()).stop();
                        btnaprv.setEnabled(true);
                }
            });
            timer2.start();    
     
        
        }
        else {
        
              javax.swing.Timer timer2 = new javax.swing.Timer(6000, new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    String text = "\nReject the Request!";
                    txt.append(text);
                    txt.setCaretPosition(txt.getText().length());
                    ((javax.swing.Timer)e.getSource()).stop();
                    btnrejt.setEnabled(true);
                }
            });
            timer2.start();
            
        }
    }//GEN-LAST:event_btnsubtActionPerformed

    private void btnrejtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrejtActionPerformed
        // TODO add your handling code here:
         btnrejt.setEnabled(false);
         btnsubt.setEnabled(true);
         request.setLabStatus("Rejected");
         request.setOverallStatus("Requestis Rejected by Lab Assistant");
         request.setActionDate(new Date());
         JOptionPane.showMessageDialog(null, "Request Rejected" ,"Info" , JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnrejtActionPerformed

    private void rbtnbldtstpasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnbldtstpasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnbldtstpasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgdImg;
    private javax.swing.JButton btnaprv;
    private javax.swing.JButton btnrejt;
    private javax.swing.JButton btnsubt;
    private javax.swing.JLabel contlabel;
    private javax.swing.JTextField conttext;
    private javax.swing.JTextField dateobtext;
    private javax.swing.JLabel doblabel;
    private javax.swing.JLabel emercontlabel;
    private javax.swing.JLabel headerlabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblantibdy;
    private javax.swing.JLabel lblarteriogy;
    private javax.swing.JLabel lblbldtest;
    private javax.swing.JLabel lblgend;
    private javax.swing.JLabel lblname;
    private javax.swing.JLabel lblphoto;
    private javax.swing.JLabel lblpsych;
    private javax.swing.JLabel lbltissue;
    private javax.swing.JLabel lblurine;
    private javax.swing.JLabel lblxray;
    private javax.swing.JLabel mandtestslabel;
    private javax.swing.JTextField nametext;
    private javax.swing.JRadioButton rbtnantibdfail;
    private javax.swing.JRadioButton rbtnantibdpas;
    private javax.swing.JRadioButton rbtnarteriogenpas;
    private javax.swing.JRadioButton rbtnarteriogfail;
    private javax.swing.JRadioButton rbtnbldtestfail;
    private javax.swing.JRadioButton rbtnbldtstpas;
    private javax.swing.JRadioButton rbtnpsychfail;
    private javax.swing.JRadioButton rbtnpsychpas;
    private javax.swing.JRadioButton rbtntissuefail;
    private javax.swing.JRadioButton rbtntissuepas;
    private javax.swing.JRadioButton rbtnurinefail;
    private javax.swing.JRadioButton rbtnurinepas;
    private javax.swing.JRadioButton rbtnxrayfail;
    private javax.swing.JRadioButton rbtnxraypas;
    private javax.swing.JTextArea txt;
    private javax.swing.JTextField txtemercont;
    private javax.swing.JTextField txtgend;
    // End of variables declaration//GEN-END:variables
}
