/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.LabAssistant;

import Backend.DB4OUtil.DB4OUtil;
import Backend.EcoSystem;
import Backend.Enterprise.Enterprise;
import Backend.Organization.LabOrganization;
import Backend.Organization.Organization;
import Backend.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JPanel;
import static javax.swing.SwingUtilities.getWindowAncestor;
import org.jdesktop.swingx.JXFrame;

/**
 *
 * @author harish
 */
public class LabAssistantDashBoardJPanel extends javax.swing.JFrame {

    /**
     * Creates new form UserDashBoardJPanel
     */

    private EcoSystem system;
    private Enterprise enterprise ;
    private DB4OUtil dB4OUtil;
    private UserAccount userAccount;
    private LabOrganization labOrganization;
    public LabAssistantDashBoardJPanel(UserAccount account, Organization organization, EcoSystem system,DB4OUtil dB4OUtil,Enterprise enterprise) {
        initComponents();
        this.dB4OUtil = dB4OUtil;
        this.system = system;
         this.enterprise = enterprise ;
        this.dB4OUtil = dB4OUtil;
        this.system = system;
        this.userAccount =account;
        this.labOrganization = (LabOrganization)organization;
        setColor(lbassnprof);
        resetColor(new JPanel[]{lbassnmngreq});
        ManageLabAssistantDetailsJPanel jpanel = new ManageLabAssistantDetailsJPanel(userAccount,system,labOrganization,enterprise);
        userProcessContainer.add("ManageLabAssistantDetailsJPanel",jpanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
                 this.setExtendedState(JXFrame.MAXIMIZED_BOTH);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane4 = new javax.swing.JSplitPane();
        admnmng = new javax.swing.JPanel();
        lbassnmngreq = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        lbassnprof = new javax.swing.JPanel();
        proflbl = new javax.swing.JLabel();
        userProcessContainer = new javax.swing.JPanel();

        setBackground(new java.awt.Color(55, 96, 128));
        setMaximumSize(null);
        setUndecorated(true);
        getContentPane().setLayout(new java.awt.GridLayout(1, 1));

        jSplitPane4.setBackground(new java.awt.Color(55, 96, 128));
        jSplitPane4.setDividerSize(0);
        jSplitPane4.setMaximumSize(null);

        admnmng.setBackground(new java.awt.Color(8, 21, 49));
        admnmng.setForeground(new java.awt.Color(8, 21, 49));
        admnmng.setMaximumSize(null);
        admnmng.setName(""); // NOI18N

        lbassnmngreq.setBackground(new java.awt.Color(8, 21, 49));
        lbassnmngreq.setForeground(new java.awt.Color(8, 21, 49));
        lbassnmngreq.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbassnmngreqMousePressed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/request x 32.png"))); // NOI18N
        jLabel10.setText("Requests");

        javax.swing.GroupLayout lbassnmngreqLayout = new javax.swing.GroupLayout(lbassnmngreq);
        lbassnmngreq.setLayout(lbassnmngreqLayout);
        lbassnmngreqLayout.setHorizontalGroup(
            lbassnmngreqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbassnmngreqLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                .addContainerGap())
        );
        lbassnmngreqLayout.setVerticalGroup(
            lbassnmngreqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbassnmngreqLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        back.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logoutx32.png"))); // NOI18N
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                backMousePressed(evt);
            }
        });

        lbassnprof.setBackground(new java.awt.Color(8, 21, 49));
        lbassnprof.setForeground(new java.awt.Color(8, 21, 49));
        lbassnprof.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbassnprofMousePressed(evt);
            }
        });

        proflbl.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        proflbl.setForeground(new java.awt.Color(255, 255, 255));
        proflbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        proflbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/account x 32.png"))); // NOI18N
        proflbl.setText("Profile");

        javax.swing.GroupLayout lbassnprofLayout = new javax.swing.GroupLayout(lbassnprof);
        lbassnprof.setLayout(lbassnprofLayout);
        lbassnprofLayout.setHorizontalGroup(
            lbassnprofLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbassnprofLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(proflbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        lbassnprofLayout.setVerticalGroup(
            lbassnprofLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbassnprofLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(proflbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout admnmngLayout = new javax.swing.GroupLayout(admnmng);
        admnmng.setLayout(admnmngLayout);
        admnmngLayout.setHorizontalGroup(
            admnmngLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbassnmngreq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbassnprof, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        admnmngLayout.setVerticalGroup(
            admnmngLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(admnmngLayout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(lbassnprof, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(lbassnmngreq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPane4.setLeftComponent(admnmng);

        userProcessContainer.setBackground(new java.awt.Color(8, 21, 49));
        userProcessContainer.setName(""); // NOI18N
        userProcessContainer.setRequestFocusEnabled(false);
        userProcessContainer.setLayout(new java.awt.CardLayout());
        jSplitPane4.setRightComponent(userProcessContainer);

        getContentPane().add(jSplitPane4);
    }// </editor-fold>//GEN-END:initComponents

    private void lbassnmngreqMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbassnmngreqMousePressed
        // TODO add your handling code here:
        setColor(lbassnmngreq);
        resetColor(new JPanel[]{lbassnprof});
        LabAssistantManageRequestsJPanel jpanel = new LabAssistantManageRequestsJPanel(userProcessContainer,userAccount,labOrganization , system,  enterprise);
        userProcessContainer.add("ManageRequestsJPanel",jpanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_lbassnmngreqMousePressed

    private void backMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMousePressed
        // TODO add your handling code here:
        this.dispose();
        dB4OUtil.storeSystem(system);
    }//GEN-LAST:event_backMousePressed

    private void lbassnprofMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbassnprofMousePressed
        // TODO add your handling code here:
        setColor(lbassnprof);
        resetColor(new JPanel[]{lbassnmngreq});
        ManageLabAssistantDetailsJPanel jpanel = new ManageLabAssistantDetailsJPanel(userAccount,system,labOrganization,enterprise);
        userProcessContainer.add("ManageLabAssistantDetailsJPanel",jpanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_lbassnprofMousePressed

 private void setColor(JPanel pane)
    {
        pane.setBackground(new Color(50, 62, 168));
    }
    
    private void resetColor(JPanel [] pane)
    {
        for(int i=0;i<pane.length;i++){
           pane[i].setBackground(new Color(23,35,51));
           
        } 
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel admnmng;
    private javax.swing.JLabel back;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JSplitPane jSplitPane4;
    private javax.swing.JPanel lbassnmngreq;
    private javax.swing.JPanel lbassnprof;
    private javax.swing.JLabel proflbl;
    private javax.swing.JPanel userProcessContainer;
    // End of variables declaration//GEN-END:variables
}
