/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.LabAssistant;

import Backend.EcoSystem;
import Backend.Enterprise.Enterprise;
import Backend.Organization.LabOrganization;
import Backend.Organization.Organization;
import Backend.UserAccount.UserAccount;
import UI.Donor.ManageDonorDetailsJPanel;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author harish
 */
public class ManageLabAssistantDetailsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form UserDetailsJPanel
     */
    private EcoSystem system;
      private UserAccount userAccount;
private LabOrganization labOrganization;
private Enterprise enterprise ;
  private byte[] tempdP;
    public ManageLabAssistantDetailsJPanel(UserAccount userAccount, EcoSystem system,Organization organization,Enterprise enterprise ) {
        initComponents();
        this.system = system;
        this.userAccount = userAccount;
        this.labOrganization = (LabOrganization)organization;
         this.enterprise = enterprise ;
        populateDefault();
    }

    private void populateDefault() {
        svebtn.setEnabled(false);
        btnupld.setEnabled(false);
        gendcobox.removeAllItems();
        dtpicktxt.setEnabled(false);
        gendcobox.addItem("Male");
        gendcobox.addItem("Female");
        nametxt.setText(userAccount.getEmployee().getName());
        addrtxt.setText(userAccount.getEmployee().getAddr());
        txtcity.setText(userAccount.getEmployee().getUrban());
        txrzcode.setText(userAccount.getEmployee().getZip());        
        txtcont.setText(userAccount.getEmployee().getPhoneNumber());
        dtpicktxt.setDate(userAccount.getEmployee().getDOB());
        gendcobox.setSelectedItem(userAccount.getEmployee().getGender());
//        emergencyContactJTextField.setText(userAccount.getEmployee().getEmergencyPhoneNumber());
//        orgnbnktxt.setText(userAccount.getEmployee().getRelationShip());
        txtstate.setText(userAccount.getEmployee().getState());        
        if(userAccount.getEmployee().getdP() !=null){
        //Working line
         byte[] JLabelpictureLabel = userAccount.getEmployee().getdP();
        ImageIcon i = setPicturebyte(JLabelpictureLabel);
        lblphoto.setIcon(i);
        }
        else{
            System.err.println("No Image");
        }
        txtorgn.setText(labOrganization.getOrgName());
//        orgnbnktxt.setText(enterprise.getName());
        addrtxt.setEditable(false);
        txtcity.setEditable(false);
        txtcont.setEditable(false);
        dtpicktxt.setEditable(false);
        gendcobox.setEnabled(false);
//        emergencyContactJTextField.setEditable(false);
        txtstate.setEditable(false);
//        orgnbnktxt.setEditable(false);
        txrzcode.setEditable(false); 
    }
private ImageIcon setPicturebyte(byte[] byteArrayImage){

        ImageIcon imageCar;
        imageCar = new ImageIcon(byteArrayImage);
        Image picCar = imageCar.getImage();
        JLabel pictureLabel1 = new JLabel();
        pictureLabel1.setSize(107, 133);
        Image resizedImage = picCar.getScaledInstance(pictureLabel1.getWidth(), pictureLabel1.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon selectedCarPicture = new ImageIcon(resizedImage);
        return selectedCarPicture;  
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        addrlabel = new javax.swing.JLabel();
        nametxt = new javax.swing.JTextField();
        txtcity = new javax.swing.JTextField();
        lblcity = new javax.swing.JLabel();
        addrtxt = new javax.swing.JTextField();
        lblcont = new javax.swing.JLabel();
        txtcont = new javax.swing.JTextField();
        lblname = new javax.swing.JLabel();
        txtstate = new javax.swing.JTextField();
        lblstate = new javax.swing.JLabel();
        lblacode = new javax.swing.JLabel();
        txrzcode = new javax.swing.JTextField();
        lblphoto = new javax.swing.JLabel();
        lblgend = new javax.swing.JLabel();
        gendcobox = new javax.swing.JComboBox();
        lbldateob = new javax.swing.JLabel();
        dtpicktxt = new org.jdesktop.swingx.JXDatePicker();
        btnupld = new javax.swing.JButton();
        svebtn = new javax.swing.JButton();
        updtbtn = new javax.swing.JButton();
        orgnlabel = new javax.swing.JLabel();
        txtorgn = new javax.swing.JTextField();
        headerlabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1100, 800));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 8, 59));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.setForeground(new java.awt.Color(0, 8, 59));
        jPanel1.setPreferredSize(new java.awt.Dimension(947, 700));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addrlabel.setBackground(new java.awt.Color(255, 255, 255));
        addrlabel.setFont(new java.awt.Font("Dubai Medium", 0, 12)); // NOI18N
        addrlabel.setForeground(new java.awt.Color(255, 255, 255));
        addrlabel.setText("Address");
        jPanel1.add(addrlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 65, -1));

        nametxt.setEditable(false);
        nametxt.setBorder(null);
        nametxt.setCaretColor(new java.awt.Color(30, 59, 92));
        nametxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nametxtFocusGained(evt);
            }
        });
        nametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nametxtActionPerformed(evt);
            }
        });
        jPanel1.add(nametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 140, 22));

        txtcity.setBorder(null);
        txtcity.setCaretColor(new java.awt.Color(30, 59, 92));
        txtcity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtcityFocusGained(evt);
            }
        });
        txtcity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcityActionPerformed(evt);
            }
        });
        jPanel1.add(txtcity, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 140, -1));

        lblcity.setBackground(new java.awt.Color(255, 255, 255));
        lblcity.setFont(new java.awt.Font("Dubai Medium", 0, 12)); // NOI18N
        lblcity.setForeground(new java.awt.Color(255, 255, 255));
        lblcity.setText("City");
        jPanel1.add(lblcity, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, -1));

        addrtxt.setBorder(null);
        addrtxt.setCaretColor(new java.awt.Color(30, 59, 92));
        addrtxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                addrtxtFocusGained(evt);
            }
        });
        addrtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addrtxtActionPerformed(evt);
            }
        });
        jPanel1.add(addrtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 140, 17));

        lblcont.setBackground(new java.awt.Color(255, 255, 255));
        lblcont.setFont(new java.awt.Font("Dubai Medium", 0, 12)); // NOI18N
        lblcont.setForeground(new java.awt.Color(255, 255, 255));
        lblcont.setText("Contact");
        jPanel1.add(lblcont, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        txtcont.setBorder(null);
        txtcont.setCaretColor(new java.awt.Color(30, 59, 92));
        txtcont.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtcontFocusGained(evt);
            }
        });
        txtcont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcontActionPerformed(evt);
            }
        });
        jPanel1.add(txtcont, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 140, 19));

        lblname.setBackground(new java.awt.Color(255, 255, 255));
        lblname.setFont(new java.awt.Font("Dubai Medium", 0, 12)); // NOI18N
        lblname.setForeground(new java.awt.Color(255, 255, 255));
        lblname.setText("Name");
        jPanel1.add(lblname, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        txtstate.setBorder(null);
        txtstate.setCaretColor(new java.awt.Color(30, 59, 92));
        txtstate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtstateFocusGained(evt);
            }
        });
        txtstate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstateActionPerformed(evt);
            }
        });
        jPanel1.add(txtstate, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, 140, -1));

        lblstate.setBackground(new java.awt.Color(255, 255, 255));
        lblstate.setFont(new java.awt.Font("Dubai Medium", 0, 12)); // NOI18N
        lblstate.setForeground(new java.awt.Color(255, 255, 255));
        lblstate.setText("State");
        jPanel1.add(lblstate, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, -1, -1));

        lblacode.setBackground(new java.awt.Color(255, 255, 255));
        lblacode.setFont(new java.awt.Font("Dubai Medium", 0, 12)); // NOI18N
        lblacode.setForeground(new java.awt.Color(255, 255, 255));
        lblacode.setText("Zip Code");
        jPanel1.add(lblacode, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, -1, -1));

        txrzcode.setBorder(null);
        txrzcode.setCaretColor(new java.awt.Color(30, 59, 92));
        txrzcode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txrzcodeFocusGained(evt);
            }
        });
        txrzcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txrzcodeActionPerformed(evt);
            }
        });
        jPanel1.add(txrzcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 400, 140, -1));

        lblphoto.setBackground(new java.awt.Color(255, 255, 255));
        lblphoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblphoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(lblphoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 107, 133));

        lblgend.setBackground(new java.awt.Color(255, 255, 255));
        lblgend.setFont(new java.awt.Font("Dubai Medium", 0, 12)); // NOI18N
        lblgend.setForeground(new java.awt.Color(255, 255, 255));
        lblgend.setText("Gender");
        jPanel1.add(lblgend, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, -1, -1));

        gendcobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(gendcobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, -1, -1));

        lbldateob.setBackground(new java.awt.Color(255, 255, 255));
        lbldateob.setFont(new java.awt.Font("Dubai Medium", 0, 12)); // NOI18N
        lbldateob.setForeground(new java.awt.Color(255, 255, 255));
        lbldateob.setText("Date of Birth");
        jPanel1.add(lbldateob, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, -1, -1));

        dtpicktxt.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(dtpicktxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, -1, -1));

        btnupld.setBackground(new java.awt.Color(0, 8, 59));
        btnupld.setFont(new java.awt.Font("Dubai Medium", 0, 12)); // NOI18N
        btnupld.setForeground(new java.awt.Color(255, 255, 255));
        btnupld.setText("Upload");
        btnupld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupldActionPerformed(evt);
            }
        });
        jPanel1.add(btnupld, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, -1, -1));

        svebtn.setBackground(new java.awt.Color(0, 8, 59));
        svebtn.setFont(new java.awt.Font("Dubai Medium", 0, 12)); // NOI18N
        svebtn.setForeground(new java.awt.Color(255, 255, 255));
        svebtn.setText("Save");
        svebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                svebtnActionPerformed(evt);
            }
        });
        jPanel1.add(svebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 117, -1));

        updtbtn.setBackground(new java.awt.Color(0, 8, 59));
        updtbtn.setFont(new java.awt.Font("Dubai Medium", 0, 12)); // NOI18N
        updtbtn.setForeground(new java.awt.Color(255, 255, 255));
        updtbtn.setText("Update");
        updtbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updtbtnActionPerformed(evt);
            }
        });
        jPanel1.add(updtbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 117, -1));

        orgnlabel.setBackground(new java.awt.Color(255, 255, 255));
        orgnlabel.setFont(new java.awt.Font("Dubai Medium", 0, 12)); // NOI18N
        orgnlabel.setForeground(new java.awt.Color(255, 255, 255));
        orgnlabel.setText("Organization");
        jPanel1.add(orgnlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, -1, -1));

        txtorgn.setEditable(false);
        txtorgn.setBorder(null);
        txtorgn.setCaretColor(new java.awt.Color(30, 59, 92));
        txtorgn.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtorgnFocusGained(evt);
            }
        });
        txtorgn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtorgnActionPerformed(evt);
            }
        });
        jPanel1.add(txtorgn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 140, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 530, 430));

        headerlabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        headerlabel.setForeground(new java.awt.Color(255, 255, 255));
        headerlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerlabel.setText("LabAssistant Details");
        add(headerlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lab_assistant.jpg"))); // NOI18N
        jLabel1.setMaximumSize(null);
        jLabel1.setMinimumSize(null);
        jLabel1.setPreferredSize(null);
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void nametxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nametxtFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_nametxtFocusGained

    private void nametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nametxtActionPerformed

    private void txtcontFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcontFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcontFocusGained

    private void txtcontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcontActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcontActionPerformed

    private void addrtxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addrtxtFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_addrtxtFocusGained

    private void addrtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addrtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addrtxtActionPerformed

    private void txtcityFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcityFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcityFocusGained

    private void txtcityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcityActionPerformed

    private void txtstateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtstateFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstateFocusGained

    private void txtstateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstateActionPerformed

    private void txrzcodeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txrzcodeFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txrzcodeFocusGained

    private void txrzcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txrzcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txrzcodeActionPerformed

    private void btnupldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupldActionPerformed
        // TODO add your handling code here:
         JFileChooser file = new JFileChooser();
          file.setCurrentDirectory(new File(System.getProperty("user.dir")));
          //filter the files
          FileNameExtensionFilter filter = new FileNameExtensionFilter("*.Images", "jpg","gif","png");
          file.addChoosableFileFilter(filter);
          int result = file.showSaveDialog(null);
           //if the user click on save in Jfilechooser
          if(result == JFileChooser.APPROVE_OPTION){
              File selectedFile = file.getSelectedFile();
              tempdP = new byte[(int) selectedFile.length()]; 
                FileInputStream fis;
             try {
                 fis = new FileInputStream(selectedFile);
                 fis.read(tempdP);
                 fis.close();
             } catch (IOException ex) {
                 Logger.getLogger(ManageDonorDetailsJPanel.class.getName()).log(Level.SEVERE, null, ex);
             }             
              lblphoto.setIcon(ResizeImage(selectedFile.getAbsolutePath()));
              lblphoto.setIcon(setPicture(selectedFile.getAbsolutePath(),lblphoto));
          }

          else if(result == JFileChooser.CANCEL_OPTION){
              System.out.println("No File Select");
          }
    }//GEN-LAST:event_btnupldActionPerformed

         private ImageIcon setPicture(String carImageLocation, JLabel carImage){

        ImageIcon imageCar;
        imageCar = new ImageIcon(carImageLocation);
        Image picCar = imageCar.getImage();
        Image resizedImage = picCar.getScaledInstance(carImage.getWidth(), carImage.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon selectedCarPicture = new ImageIcon(resizedImage);
        
        return selectedCarPicture;  
}
    private void svebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_svebtnActionPerformed
        // TODO add your handling code here:
//        try {
//            Integer.parseInt(zipJTextField.getText());
//            Integer.parseInt(contactJTextField.getText());
//
//        } catch (NumberFormatException e) {
//            JOptionPane.showMessageDialog(null, "Contact Number and Zip code should be numberic", "Error", 0);
//            return;
//        }
         
        if (addrtxt.getText().isEmpty()           || txtcity.getText().isEmpty()     ||
            txtcont.getText().isEmpty()           || txtstate.getText().isEmpty()    ||
            txrzcode.getText().isEmpty()               || nametxt.getText().isEmpty() )
            
        { 
    
         JOptionPane.showMessageDialog(null, "All fields are mandatory", "Error", JOptionPane.ERROR_MESSAGE);
         return ;
        }
        
          Date currentDate = new Date();
          
          if (currentDate.equals(dtpicktxt.getDate()) || dtpicktxt.getDate().after(currentDate)) {
          
             JOptionPane.showMessageDialog(null, "Date should be past date", "Error", JOptionPane.ERROR_MESSAGE);
             return;
          }
          
          if (txtcont.getText().length() != 10 ) {
             JOptionPane.showMessageDialog(null, "Contact information should be 10 number", "Error", JOptionPane.ERROR_MESSAGE);
             return;   
          }
          
          if (txrzcode.getText().length() != 5) {
             JOptionPane.showMessageDialog(null, "Zip code should be 5 digit", "Error", JOptionPane.ERROR_MESSAGE);
             return;   
          }
          
        userAccount.getEmployee().setAddr(addrtxt.getText());
        userAccount.getEmployee().setUrban(txtcity.getText());
        userAccount.getEmployee().setPhoneNumber(txtcont.getText());
        userAccount.getEmployee().setDOB(dtpicktxt.getDate());
        userAccount.getEmployee().setGender((String) gendcobox.getSelectedItem());
//        userAccount.getEmployee().setEmergencyPhoneNumber(emergencyContactJTextField.getText());
//        userAccount.getEmployee().setRelationShip(orgnbnktxt.getText());
        userAccount.getEmployee().setState(txtstate.getText());
        userAccount.getEmployee().setZip(txrzcode.getText());
         userAccount.getEmployee().setdP(tempdP);
        JOptionPane.showMessageDialog(null, "Profile Updated Sucessfully");   
        addrtxt.setEditable(false);
        txtcity.setEditable(false);
        txtcont.setEditable(false);
        dtpicktxt.setEnabled(false);
        gendcobox.setEnabled(false);
//        emergencyContactJTextField.setEditable(false);
        txtstate.setEditable(false);
//        orgnbnktxt.setEditable(false);
        txrzcode.setEditable(false);      
        updtbtn.setEnabled(true);
        svebtn.setEnabled(false);
        btnupld.setEnabled(false);
        
        
    }//GEN-LAST:event_svebtnActionPerformed

    private void updtbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updtbtnActionPerformed
        // TODO add your handling code here:
        updtbtn.setEnabled(false);
        svebtn.setEnabled(true);
        btnupld.setEnabled(true);
        addrtxt.setEditable(true);
        txtcity.setEditable(true);
        txtcont.setEditable(true);
        dtpicktxt.setEditable(true);
        gendcobox.setEnabled(true);
        dtpicktxt.setEnabled(true);
//        emergencyContactJTextField.setEditable(true);
        txtstate.setEditable(true);
//        orgnbnktxt.setEditable(true);
        txrzcode.setEditable(true); 
    }//GEN-LAST:event_updtbtnActionPerformed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        // TODO add your handling code here:
 
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseClicked

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MousePressed

    private void txtorgnFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtorgnFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtorgnFocusGained

    private void txtorgnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtorgnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtorgnActionPerformed
    
    public ImageIcon ResizeImage(String ImagePath)
    {
        ImageIcon MyImage = new ImageIcon(ImagePath);
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(lblphoto.getWidth(), lblphoto.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addrlabel;
    private javax.swing.JTextField addrtxt;
    private javax.swing.JButton btnupld;
    private org.jdesktop.swingx.JXDatePicker dtpicktxt;
    private javax.swing.JComboBox gendcobox;
    private javax.swing.JLabel headerlabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblacode;
    private javax.swing.JLabel lblcity;
    private javax.swing.JLabel lblcont;
    private javax.swing.JLabel lbldateob;
    private javax.swing.JLabel lblgend;
    private javax.swing.JLabel lblname;
    private javax.swing.JLabel lblphoto;
    private javax.swing.JLabel lblstate;
    private javax.swing.JTextField nametxt;
    private javax.swing.JLabel orgnlabel;
    private javax.swing.JButton svebtn;
    private javax.swing.JTextField txrzcode;
    private javax.swing.JTextField txtcity;
    private javax.swing.JTextField txtcont;
    private javax.swing.JTextField txtorgn;
    private javax.swing.JTextField txtstate;
    private javax.swing.JButton updtbtn;
    // End of variables declaration//GEN-END:variables

}
