/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Donor;

import Backend.EcoSystem;
import Backend.User.User;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
 
/**
 *
 * @author Arun Balasubramanian
 */
public class ManageDonorDetailsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form UserDetailsJPanel
     */
    private EcoSystem system;
    private User user;
    private byte[] tempdP;

    public ManageDonorDetailsJPanel(User user, EcoSystem system) {
        initComponents();
        this.system = system;
        this.user = user;
        ButtonGroup buttongroup = new ButtonGroup();
        buttongroup.add(chkboxlivr);
        buttongroup.add(chkboxlimbs);
        populateDefault();
    }

    private void populateDefault() {
        btnsve.setEnabled(false);
        btnupld.setEnabled(false);
        cmboxgend.removeAllItems();
        cmboxgend.addItem("Male");
        cmboxgend.addItem("Female");
        txtnameadd.setText(user.getName());
        txtaddr.setText(user.getAddr());
        txtcity.setText(user.getUrban());
        txtcont.setText(user.getPhoneNumber());
        dtpik1.setDate(user.getDOB());
        cmboxgend.setSelectedItem(user.getGender());
        //emergencyContactJTextField.setText(user.getEmergencyPhoneNumber()+ "");
            txtemercont.setText(user.getEmergencyPhoneNumber());
        txtrel.setText(user.getRelationShip());
        txtstat.setText(user.getState());
        //zipJTextField.setText(user.getZip()+ "");
            txtzipcode.setText(user.getZip());
        chkboxlivr.setSelected(user.isLiver());
        chkboxlimbs.setSelected(user.isLungs());
        txtaddr.setEditable(false);
        txtcity.setEditable(false);
        txtcont.setEditable(false);
        dtpik1.setEditable(false);
        cmboxgend.setEnabled(false);
        txtemercont.setEditable(false);
        txtstat.setEditable(false);
        txtrel.setEditable(false);
        txtzipcode.setEditable(false);
        chkboxlivr.setEnabled(false);
        chkboxlimbs.setEnabled(false);
       
        if(user.getdP() !=null){
        //Working line
         byte[] JLabelpictureLabel = user.getdP();
        ImageIcon i = setPicturebyte(JLabelpictureLabel);
        lblphoto.setIcon(i);
        }
        else{
            System.err.println("No Image");
        }
    }
private ImageIcon setPicturebyte(byte[] byteArrayImage){

        ImageIcon imageCar;
        imageCar = new ImageIcon(byteArrayImage);
        Image picCar = imageCar.getImage();
        JLabel pictureLabel1 = new JLabel();
        pictureLabel1.setSize(107, 133);
        Image resizedImage = picCar.getScaledInstance(pictureLabel1.getWidth(), pictureLabel1.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon selectedCarPicture = new ImageIcon(resizedImage);
        return selectedCarPicture;  
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        lbladdr = new javax.swing.JLabel();
        txtnameadd = new javax.swing.JTextField();
        txtcity = new javax.swing.JTextField();
        labelcity = new javax.swing.JLabel();
        txtaddr = new javax.swing.JTextField();
        labelcont = new javax.swing.JLabel();
        txtcont = new javax.swing.JTextField();
        lblname = new javax.swing.JLabel();
        txtstat = new javax.swing.JTextField();
        lblstat = new javax.swing.JLabel();
        lblzipcode = new javax.swing.JLabel();
        txtzipcode = new javax.swing.JTextField();
        lblphoto = new javax.swing.JLabel();
        lblgend = new javax.swing.JLabel();
        cmboxgend = new javax.swing.JComboBox();
        lbldob = new javax.swing.JLabel();
        dtpik1 = new org.jdesktop.swingx.JXDatePicker();
        txtrel = new javax.swing.JTextField();
        rellabel = new javax.swing.JLabel();
        txtemercont = new javax.swing.JTextField();
        emercontlabel = new javax.swing.JLabel();
        txtcontname = new javax.swing.JTextField();
        contnamelabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        orgndonatelabel = new javax.swing.JLabel();
        chkboxlivr = new javax.swing.JCheckBox();
        chkboxlimbs = new javax.swing.JCheckBox();
        btnupld = new javax.swing.JButton();
        btnsve = new javax.swing.JButton();
        btnupdt = new javax.swing.JButton();
        titlelabel = new javax.swing.JLabel();
        bgdimg = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(890, 539));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 9, 21));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.setPreferredSize(new java.awt.Dimension(947, 700));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        lbladdr.setBackground(new java.awt.Color(255, 255, 255));
        lbladdr.setFont(new java.awt.Font("Dubai Medium", 0, 13)); // NOI18N
        lbladdr.setForeground(new java.awt.Color(255, 255, 255));
        lbladdr.setText("Address");

        txtnameadd.setEditable(false);
        txtnameadd.setBorder(null);
        txtnameadd.setCaretColor(new java.awt.Color(30, 59, 92));
        txtnameadd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtnameaddFocusGained(evt);
            }
        });
        txtnameadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameaddActionPerformed(evt);
            }
        });

        txtcity.setBorder(null);
        txtcity.setCaretColor(new java.awt.Color(30, 59, 92));
        txtcity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtcityFocusGained(evt);
            }
        });
        txtcity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcityActionPerformed(evt);
            }
        });

        labelcity.setBackground(new java.awt.Color(255, 255, 255));
        labelcity.setFont(new java.awt.Font("Dubai Medium", 0, 13)); // NOI18N
        labelcity.setForeground(new java.awt.Color(255, 255, 255));
        labelcity.setText("City");

        txtaddr.setBorder(null);
        txtaddr.setCaretColor(new java.awt.Color(30, 59, 92));
        txtaddr.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtaddrFocusGained(evt);
            }
        });
        txtaddr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtaddrActionPerformed(evt);
            }
        });

        labelcont.setBackground(new java.awt.Color(255, 255, 255));
        labelcont.setFont(new java.awt.Font("Dubai Medium", 0, 13)); // NOI18N
        labelcont.setForeground(new java.awt.Color(255, 255, 255));
        labelcont.setText("Contact");

        txtcont.setBorder(null);
        txtcont.setCaretColor(new java.awt.Color(30, 59, 92));
        txtcont.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtcontFocusGained(evt);
            }
        });
        txtcont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcontActionPerformed(evt);
            }
        });

        lblname.setBackground(new java.awt.Color(255, 255, 255));
        lblname.setFont(new java.awt.Font("Dubai Medium", 0, 13)); // NOI18N
        lblname.setForeground(new java.awt.Color(255, 255, 255));
        lblname.setText("Name");

        txtstat.setBorder(null);
        txtstat.setCaretColor(new java.awt.Color(30, 59, 92));
        txtstat.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtstatFocusGained(evt);
            }
        });
        txtstat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstatActionPerformed(evt);
            }
        });

        lblstat.setBackground(new java.awt.Color(255, 255, 255));
        lblstat.setFont(new java.awt.Font("Dubai Medium", 0, 13)); // NOI18N
        lblstat.setForeground(new java.awt.Color(255, 255, 255));
        lblstat.setText("State");

        lblzipcode.setBackground(new java.awt.Color(255, 255, 255));
        lblzipcode.setFont(new java.awt.Font("Dubai Medium", 0, 13)); // NOI18N
        lblzipcode.setForeground(new java.awt.Color(255, 255, 255));
        lblzipcode.setText("Zip Code");

        txtzipcode.setBorder(null);
        txtzipcode.setCaretColor(new java.awt.Color(30, 59, 92));
        txtzipcode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtzipcodeFocusGained(evt);
            }
        });
        txtzipcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtzipcodeActionPerformed(evt);
            }
        });

        lblphoto.setBackground(new java.awt.Color(255, 255, 255));
        lblphoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblphoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        lblgend.setBackground(new java.awt.Color(255, 255, 255));
        lblgend.setFont(new java.awt.Font("Dubai Medium", 0, 13)); // NOI18N
        lblgend.setForeground(new java.awt.Color(255, 255, 255));
        lblgend.setText("Gender");

        cmboxgend.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lbldob.setBackground(new java.awt.Color(255, 255, 255));
        lbldob.setFont(new java.awt.Font("Dubai Medium", 0, 13)); // NOI18N
        lbldob.setForeground(new java.awt.Color(255, 255, 255));
        lbldob.setText("Date of Birth");

        dtpik1.setBackground(new java.awt.Color(255, 255, 255));

        txtrel.setBorder(null);
        txtrel.setCaretColor(new java.awt.Color(30, 59, 92));
        txtrel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtrelFocusGained(evt);
            }
        });
        txtrel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrelActionPerformed(evt);
            }
        });

        rellabel.setBackground(new java.awt.Color(255, 255, 255));
        rellabel.setFont(new java.awt.Font("Dubai Medium", 0, 13)); // NOI18N
        rellabel.setForeground(new java.awt.Color(255, 255, 255));
        rellabel.setText("Relation");

        txtemercont.setBorder(null);
        txtemercont.setCaretColor(new java.awt.Color(30, 59, 92));
        txtemercont.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtemercontFocusGained(evt);
            }
        });
        txtemercont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemercontActionPerformed(evt);
            }
        });

        emercontlabel.setBackground(new java.awt.Color(255, 255, 255));
        emercontlabel.setFont(new java.awt.Font("Dubai Medium", 0, 13)); // NOI18N
        emercontlabel.setForeground(new java.awt.Color(255, 255, 255));
        emercontlabel.setText("Emergency Contact");

        txtcontname.setBorder(null);
        txtcontname.setCaretColor(new java.awt.Color(30, 59, 92));
        txtcontname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtcontnameFocusGained(evt);
            }
        });
        txtcontname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcontnameActionPerformed(evt);
            }
        });

        contnamelabel.setBackground(new java.awt.Color(255, 255, 255));
        contnamelabel.setFont(new java.awt.Font("Dubai Medium", 0, 13)); // NOI18N
        contnamelabel.setForeground(new java.awt.Color(255, 255, 255));
        contnamelabel.setText("Name of Contact");

        jPanel2.setBackground(new java.awt.Color(0, 9, 21));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        orgndonatelabel.setBackground(new java.awt.Color(255, 255, 255));
        orgndonatelabel.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        orgndonatelabel.setForeground(new java.awt.Color(255, 255, 255));
        orgndonatelabel.setText("Select one option below");

        chkboxlivr.setBackground(new java.awt.Color(0, 9, 21));
        chkboxlivr.setForeground(new java.awt.Color(255, 255, 255));
        chkboxlivr.setText("Liver");
        chkboxlivr.setBorder(null);

        chkboxlimbs.setBackground(new java.awt.Color(0, 9, 21));
        chkboxlimbs.setForeground(new java.awt.Color(255, 255, 255));
        chkboxlimbs.setText("Limbs");
        chkboxlimbs.setBorder(null);
        chkboxlimbs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkboxlimbsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(orgndonatelabel))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkboxlimbs)
                            .addComponent(chkboxlivr))))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(orgndonatelabel)
                .addGap(18, 18, 18)
                .addComponent(chkboxlivr)
                .addGap(28, 28, 28)
                .addComponent(chkboxlimbs)
                .addGap(69, 69, 69))
        );

        btnupld.setBackground(new java.awt.Color(0, 9, 21));
        btnupld.setFont(new java.awt.Font("Dubai Medium", 0, 13)); // NOI18N
        btnupld.setForeground(new java.awt.Color(255, 255, 255));
        btnupld.setText("Upload");
        btnupld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupldActionPerformed(evt);
            }
        });

        btnsve.setBackground(new java.awt.Color(0, 9, 21));
        btnsve.setFont(new java.awt.Font("Dubai Medium", 0, 13)); // NOI18N
        btnsve.setForeground(new java.awt.Color(255, 255, 255));
        btnsve.setText("Save");
        btnsve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsveActionPerformed(evt);
            }
        });

        btnupdt.setBackground(new java.awt.Color(0, 9, 21));
        btnupdt.setFont(new java.awt.Font("Dubai Medium", 0, 13)); // NOI18N
        btnupdt.setForeground(new java.awt.Color(255, 255, 255));
        btnupdt.setText("Update");
        btnupdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelcont)
                            .addComponent(txtcont, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblname)
                            .addComponent(txtnameadd, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelcity)
                            .addComponent(txtcity, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtaddr, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblstat)
                            .addComponent(txtstat, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbladdr, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emercontlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtemercont, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rellabel)
                            .addComponent(txtrel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(contnamelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcontname, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmboxgend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dtpik1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblgend)
                            .addComponent(lbldob))
                        .addGap(60, 60, 60))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblphoto, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(btnupld)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblzipcode)
                            .addComponent(txtzipcode, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnupdt, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnsve, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(154, 154, 154))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblphoto, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(btnupld)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblname)
                            .addComponent(lblgend))
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtnameadd, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmboxgend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbldob)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dtpik1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelcont)
                                .addGap(3, 3, 3)
                                .addComponent(txtcont, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)))
                        .addComponent(lbladdr)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtaddr, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblstat)
                                .addGap(6, 6, 6)
                                .addComponent(txtstat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(295, 295, 295))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(labelcity)
                                .addGap(6, 6, 6)
                                .addComponent(txtcity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(347, 347, 347))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(emercontlabel)
                                .addGap(6, 6, 6)
                                .addComponent(txtemercont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnsve)
                                .addGap(30, 30, 30)
                                .addComponent(btnupdt)))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rellabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtrel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addComponent(contnamelabel)
                                .addGap(6, 6, 6)
                                .addComponent(txtcontname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblzipcode)
                                .addGap(6, 6, 6)
                                .addComponent(txtzipcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(295, 295, 295))))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 770, 510));

        titlelabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        titlelabel.setForeground(new java.awt.Color(255, 255, 255));
        titlelabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlelabel.setText("Donor Requested Details");
        add(titlelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 40));

        bgdimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/donor.png"))); // NOI18N
        add(bgdimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 800));
    }// </editor-fold>//GEN-END:initComponents

    private void txtnameaddFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnameaddFocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_txtnameaddFocusGained

    private void txtnameaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameaddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameaddActionPerformed

    private void txtcontFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcontFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcontFocusGained

    private void txtcontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcontActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcontActionPerformed

    private void txtaddrFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtaddrFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaddrFocusGained

    private void txtaddrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtaddrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaddrActionPerformed

    private void txtcityFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcityFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcityFocusGained

    private void txtcityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcityActionPerformed

    private void txtstatFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtstatFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstatFocusGained

    private void txtstatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstatActionPerformed

    private void txtzipcodeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtzipcodeFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtzipcodeFocusGained

    private void txtzipcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtzipcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtzipcodeActionPerformed

    private void txtemercontFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtemercontFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemercontFocusGained

    private void txtemercontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemercontActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemercontActionPerformed

    private void txtrelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtrelFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrelFocusGained

    private void txtrelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrelActionPerformed

    private void txtcontnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcontnameFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcontnameFocusGained

    private void txtcontnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcontnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcontnameActionPerformed

    private void btnupldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupldActionPerformed
        // TODO add your handling code here:
         JFileChooser file = new JFileChooser();
          file.setCurrentDirectory(new File(System.getProperty("user.dir")));
          //filter the files
          FileNameExtensionFilter filter = new FileNameExtensionFilter("*.Images", "jpg","gif","png");
          file.addChoosableFileFilter(filter);
          int result = file.showSaveDialog(null);
           //if the user click on save in Jfilechooser
          if(result == JFileChooser.APPROVE_OPTION){
              File selectedFile = file.getSelectedFile();
              tempdP = new byte[(int) selectedFile.length()]; 
                FileInputStream fis;
             try {
                 fis = new FileInputStream(selectedFile);
                 fis.read(tempdP);
                 fis.close();
             } catch (IOException ex) {
                 Logger.getLogger(ManageDonorDetailsJPanel.class.getName()).log(Level.SEVERE, null, ex);
             }             
              lblphoto.setIcon(ResizeImage(selectedFile.getAbsolutePath()));
              lblphoto.setIcon(setPicture(selectedFile.getAbsolutePath(),lblphoto));
          }

          else if(result == JFileChooser.CANCEL_OPTION){
              System.out.println("No File Select");
          }
    }//GEN-LAST:event_btnupldActionPerformed

    private ImageIcon setPicture(String carImageLocation, JLabel carImage){

        ImageIcon imageCar;
        imageCar = new ImageIcon(carImageLocation);
        Image picCar = imageCar.getImage();
        Image resizedImage = picCar.getScaledInstance(carImage.getWidth(), carImage.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon selectedCarPicture = new ImageIcon(resizedImage);
        return selectedCarPicture;  
}
   

    private void btnsveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsveActionPerformed
        // TODO add your handling code here:
        String pattern = ".*\\D.*";
        Pattern patternForZip = Pattern.compile(pattern);
        String zipCode1 = txtzipcode.getText();
        String emergencyContact = txtemercont.getText();
        String contact = txtcont.getText();
        Matcher matcherForZip = patternForZip.matcher(zipCode1);
         Matcher matcherForContact = patternForZip.matcher(contact);
           Matcher matcherForEContact = patternForZip.matcher(emergencyContact);
        if (matcherForZip.matches() == true || matcherForContact.matches() == true|| matcherForEContact.matches() == true) {
            JOptionPane.showMessageDialog(null, "Contact Number and Zip code should be numeric", "Error", 0);
			return;
        }
         
        if (txtaddr.getText().isEmpty()           || txtcity.getText().isEmpty()     ||
            txtcont.getText().isEmpty()           || txtrel.getText().isEmpty() ||
            txtemercont.getText().isEmpty()  || txtstat.getText().isEmpty()    ||
            txtzipcode.getText().isEmpty()               || txtnameadd.getText().isEmpty() ||
            txtcontname.getText().isEmpty() )
        { 
    
         JOptionPane.showMessageDialog(null, "All fields are mandatory", "Error", JOptionPane.ERROR_MESSAGE);
         return ;
        }
        
          Date currentDate = new Date();
          
          if (currentDate.equals(dtpik1.getDate()) || dtpik1.getDate().after(currentDate)) {
          
             JOptionPane.showMessageDialog(null, "Date should be past date", "Error", JOptionPane.ERROR_MESSAGE);
             return;
          }
          
          if (txtcont.getText().length() != 10 || txtemercont.getText().length() != 10) {
             JOptionPane.showMessageDialog(null, "Contact information should be 10 number", "Error", JOptionPane.ERROR_MESSAGE);
             return;   
          }
          
          if (txtzipcode.getText().length() != 5) {
             JOptionPane.showMessageDialog(null, "Zip code should be 5 digit", "Error", JOptionPane.ERROR_MESSAGE);
             return;   
          }
          
          if (chkboxlivr.isSelected() || chkboxlimbs.isSelected()) {
          user.setAddr(txtaddr.getText());
        user.setUrban(txtcity.getText());
        user.setPhoneNumber(txtcont.getText());
        user.setDOB(dtpik1.getDate());
        user.setGender((String) cmboxgend.getSelectedItem());
        user.setEmergencyPhoneNumber(txtemercont.getText());
        user.setRelationShip(txtcontname.getText());
        user.setState(txtstat.getText());
        user.setZip(txtzipcode.getText());
        user.setLiver(chkboxlivr.isSelected());
        user.setLimbs(chkboxlimbs.isSelected());
        user.setPhotoLabel(lblphoto);
        user.setdP(tempdP);
        JOptionPane.showMessageDialog(null, "Profile Updated Sucessfully");
        user.setCompleteProfile(true);
        txtaddr.setEditable(false);
        txtcity.setEditable(false);
        txtcont.setEditable(false);
        dtpik1.setEnabled(false);
        cmboxgend.setEnabled(false);
        txtemercont.setEditable(false);
        txtstat.setEditable(false);
        txtcontname.setEditable(false);
        txtzipcode.setEditable(false); 
        chkboxlivr.setEnabled(false);
        chkboxlimbs.setEnabled(false);
        btnupdt.setEnabled(true);
        btnsve.setEnabled(false);
        btnupld.setEnabled(false);
            
          }
          else{
          JOptionPane.showMessageDialog(null, "Please select organ to donate", "Error", JOptionPane.ERROR_MESSAGE);
             return;
          }
    }//GEN-LAST:event_btnsveActionPerformed

    private void btnupdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdtActionPerformed
        // TODO add your handling code here:
        btnupdt.setEnabled(false);
        btnsve.setEnabled(true);
        btnupld.setEnabled(true);
        txtaddr.setEditable(true);
        txtcity.setEditable(true);
        txtcont.setEditable(true);
        dtpik1.setEditable(true);
        cmboxgend.setEnabled(true);
        txtemercont.setEditable(true);
        txtstat.setEditable(true);
        txtrel.setEditable(true);
        txtzipcode.setEditable(true); 
        chkboxlivr.setEnabled(true);
        chkboxlimbs.setEnabled(true);
    }//GEN-LAST:event_btnupdtActionPerformed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        // TODO add your handling code here:
 
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseClicked

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MousePressed

    private void chkboxlimbsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkboxlimbsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkboxlimbsActionPerformed
    
    public ImageIcon ResizeImage(String ImagePath)
    {
        ImageIcon MyImage = new ImageIcon(ImagePath);
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(lblphoto.getWidth(), lblphoto.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgdimg;
    private javax.swing.JButton btnsve;
    private javax.swing.JButton btnupdt;
    private javax.swing.JButton btnupld;
    private javax.swing.JCheckBox chkboxlimbs;
    private javax.swing.JCheckBox chkboxlivr;
    private javax.swing.JComboBox cmboxgend;
    private javax.swing.JLabel contnamelabel;
    private org.jdesktop.swingx.JXDatePicker dtpik1;
    private javax.swing.JLabel emercontlabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JLabel labelcity;
    private javax.swing.JLabel labelcont;
    private javax.swing.JLabel lbladdr;
    private javax.swing.JLabel lbldob;
    private javax.swing.JLabel lblgend;
    private javax.swing.JLabel lblname;
    private javax.swing.JLabel lblphoto;
    private javax.swing.JLabel lblstat;
    private javax.swing.JLabel lblzipcode;
    private javax.swing.JLabel orgndonatelabel;
    private javax.swing.JLabel rellabel;
    private javax.swing.JLabel titlelabel;
    private javax.swing.JTextField txtaddr;
    private javax.swing.JTextField txtcity;
    private javax.swing.JTextField txtcont;
    private javax.swing.JTextField txtcontname;
    private javax.swing.JTextField txtemercont;
    private javax.swing.JTextField txtnameadd;
    private javax.swing.JTextField txtrel;
    private javax.swing.JTextField txtstat;
    private javax.swing.JTextField txtzipcode;
    // End of variables declaration//GEN-END:variables

}
