/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Receiver;

import Backend.EcoSystem;
import Backend.User.User;
import UI.Coordinator.*;
import UI.Donor.ManageDonorDetailsJPanel;
import java.awt.BorderLayout;
import java.awt.Image;
//import Backend.Validations;
//import static Backend.Validations.isAddValid;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.imageio.ImageIO;
import javax.swing.ButtonGroup;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Arun Balasubramanian
 */
public class ManageReceiverDetailsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form UserDetailsJPanel
     */
    private EcoSystem system;
    private User user;
  private byte[] tempdP;
    public ManageReceiverDetailsJPanel(User user, EcoSystem system) {
        initComponents();
        this.system = system;
        this.user = user;
        ButtonGroup buttongroup = new ButtonGroup();
        buttongroup.add(chkbxlimb);
        buttongroup.add(chkbxliv);
        populateDefault();
    }

    private void populateDefault() {
        btnsvc.setEnabled(false);
        btnupld.setEnabled(false);
        comboxgend.removeAllItems();
        comboxgend.addItem("Male");
        comboxgend.addItem("Female");
        txtname.setText(user.getName());
        txtaddr.setText(user.getAddr());
        txtcity.setText(user.getUrban());
        txtcont.setText(user.getPhoneNumber());
        dtpik1txt.setDate(user.getDOB());
        comboxgend.setSelectedItem(user.getGender());
        emerconttxt.setText(user.getEmergencyPhoneNumber());
        namreltxt.setText(user.getRelationShip());
        txtstat.setText(user.getState());
        txtzcode.setText(user.getZip()+ "");
        chkbxlimb.setSelected(user.isLimbs());
        chkbxliv.setSelected(user.isLiver());
        txtaddr.setEditable(false);
        txtcity.setEditable(false);
        txtcont.setEditable(false);
        dtpik1txt.setEditable(false);
        comboxgend.setEnabled(false);
        emerconttxt.setEditable(false);
        txtstat.setEditable(false);
        namreltxt.setEditable(false);
        txtzcode.setEditable(false); 
        chkbxlimb.setEnabled(false);
        chkbxliv.setEnabled(false);
        
        if(user.getdP() !=null){
        //Working line
         byte[] JLabelpictureLabel = user.getdP();
        ImageIcon i = setPicturebyte(JLabelpictureLabel);
        lblpicture.setIcon(i);
        }
        else{
            System.err.println("No Image");
        }
    }
private ImageIcon setPicturebyte(byte[] byteArrayImage){

        ImageIcon imageCar;
        imageCar = new ImageIcon(byteArrayImage);
        Image picCar = imageCar.getImage();
        JLabel pictureLabel1 = new JLabel();
        pictureLabel1.setSize(107, 133);
        Image resizedImage = picCar.getScaledInstance(pictureLabel1.getWidth(), pictureLabel1.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon selectedCarPicture = new ImageIcon(resizedImage);
        return selectedCarPicture;  
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        addrlabel = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        txtcity = new javax.swing.JTextField();
        citylabel = new javax.swing.JLabel();
        txtaddr = new javax.swing.JTextField();
        contlabel = new javax.swing.JLabel();
        txtcont = new javax.swing.JTextField();
        namelabel = new javax.swing.JLabel();
        txtstat = new javax.swing.JTextField();
        labelstat = new javax.swing.JLabel();
        labelzcode = new javax.swing.JLabel();
        txtzcode = new javax.swing.JTextField();
        lblpicture = new javax.swing.JLabel();
        gendlabel = new javax.swing.JLabel();
        comboxgend = new javax.swing.JComboBox();
        doblbl = new javax.swing.JLabel();
        dtpik1txt = new org.jdesktop.swingx.JXDatePicker();
        namreltxt = new javax.swing.JTextField();
        rellabel = new javax.swing.JLabel();
        emerconttxt = new javax.swing.JTextField();
        emercontlabel = new javax.swing.JLabel();
        relnametxt = new javax.swing.JTextField();
        namecontlbl = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        orgnlookinglbl = new javax.swing.JLabel();
        chkbxliv = new javax.swing.JCheckBox();
        chkbxlimb = new javax.swing.JCheckBox();
        btnupld = new javax.swing.JButton();
        btnsvc = new javax.swing.JButton();
        btnupdt = new javax.swing.JButton();
        headerlabel = new javax.swing.JLabel();
        bgdimg = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1100, 800));
        setPreferredSize(new java.awt.Dimension(1100, 800));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.setPreferredSize(new java.awt.Dimension(947, 700));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        addrlabel.setBackground(new java.awt.Color(255, 255, 255));
        addrlabel.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        addrlabel.setForeground(new java.awt.Color(255, 255, 255));
        addrlabel.setText("Address");

        txtname.setEditable(false);
        txtname.setBorder(null);
        txtname.setCaretColor(new java.awt.Color(30, 59, 92));
        txtname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtnameFocusGained(evt);
            }
        });
        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });

        txtcity.setBorder(null);
        txtcity.setCaretColor(new java.awt.Color(30, 59, 92));
        txtcity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtcityFocusGained(evt);
            }
        });
        txtcity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcityActionPerformed(evt);
            }
        });

        citylabel.setBackground(new java.awt.Color(255, 255, 255));
        citylabel.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        citylabel.setForeground(new java.awt.Color(255, 255, 255));
        citylabel.setText("City");

        txtaddr.setBorder(null);
        txtaddr.setCaretColor(new java.awt.Color(30, 59, 92));
        txtaddr.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtaddrFocusGained(evt);
            }
        });
        txtaddr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtaddrActionPerformed(evt);
            }
        });

        contlabel.setBackground(new java.awt.Color(255, 255, 255));
        contlabel.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        contlabel.setForeground(new java.awt.Color(255, 255, 255));
        contlabel.setText("Contact");

        txtcont.setBorder(null);
        txtcont.setCaretColor(new java.awt.Color(30, 59, 92));
        txtcont.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtcontFocusGained(evt);
            }
        });
        txtcont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcontActionPerformed(evt);
            }
        });

        namelabel.setBackground(new java.awt.Color(255, 255, 255));
        namelabel.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        namelabel.setForeground(new java.awt.Color(255, 255, 255));
        namelabel.setText("Name");

        txtstat.setBorder(null);
        txtstat.setCaretColor(new java.awt.Color(30, 59, 92));
        txtstat.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtstatFocusGained(evt);
            }
        });
        txtstat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstatActionPerformed(evt);
            }
        });

        labelstat.setBackground(new java.awt.Color(255, 255, 255));
        labelstat.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        labelstat.setForeground(new java.awt.Color(255, 255, 255));
        labelstat.setText("State");

        labelzcode.setBackground(new java.awt.Color(255, 255, 255));
        labelzcode.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        labelzcode.setForeground(new java.awt.Color(255, 255, 255));
        labelzcode.setText("Zip Code");

        txtzcode.setBorder(null);
        txtzcode.setCaretColor(new java.awt.Color(30, 59, 92));
        txtzcode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtzcodeFocusGained(evt);
            }
        });
        txtzcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtzcodeActionPerformed(evt);
            }
        });

        lblpicture.setBackground(new java.awt.Color(255, 255, 255));
        lblpicture.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblpicture.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        gendlabel.setBackground(new java.awt.Color(255, 255, 255));
        gendlabel.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        gendlabel.setForeground(new java.awt.Color(255, 255, 255));
        gendlabel.setText("Gender");

        comboxgend.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        doblbl.setBackground(new java.awt.Color(255, 255, 255));
        doblbl.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        doblbl.setForeground(new java.awt.Color(255, 255, 255));
        doblbl.setText("Date of Birth");

        dtpik1txt.setBackground(new java.awt.Color(255, 255, 255));

        namreltxt.setBorder(null);
        namreltxt.setCaretColor(new java.awt.Color(30, 59, 92));
        namreltxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                namreltxtFocusGained(evt);
            }
        });
        namreltxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namreltxtActionPerformed(evt);
            }
        });

        rellabel.setBackground(new java.awt.Color(255, 255, 255));
        rellabel.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        rellabel.setForeground(new java.awt.Color(255, 255, 255));
        rellabel.setText("Relation");

        emerconttxt.setBorder(null);
        emerconttxt.setCaretColor(new java.awt.Color(30, 59, 92));
        emerconttxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emerconttxtFocusGained(evt);
            }
        });
        emerconttxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emerconttxtActionPerformed(evt);
            }
        });

        emercontlabel.setBackground(new java.awt.Color(255, 255, 255));
        emercontlabel.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        emercontlabel.setForeground(new java.awt.Color(255, 255, 255));
        emercontlabel.setText("Emergency Contact");

        relnametxt.setBorder(null);
        relnametxt.setCaretColor(new java.awt.Color(30, 59, 92));
        relnametxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                relnametxtFocusGained(evt);
            }
        });
        relnametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relnametxtActionPerformed(evt);
            }
        });

        namecontlbl.setBackground(new java.awt.Color(255, 255, 255));
        namecontlbl.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        namecontlbl.setForeground(new java.awt.Color(255, 255, 255));
        namecontlbl.setText("Name of Contact");

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        orgnlookinglbl.setBackground(new java.awt.Color(255, 255, 255));
        orgnlookinglbl.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        orgnlookinglbl.setForeground(new java.awt.Color(255, 255, 255));
        orgnlookinglbl.setText("Select");

        chkbxliv.setBackground(new java.awt.Color(0, 0, 0));
        chkbxliv.setForeground(new java.awt.Color(255, 255, 255));
        chkbxliv.setText("Liver");
        chkbxliv.setBorder(null);

        chkbxlimb.setBackground(new java.awt.Color(0, 0, 0));
        chkbxlimb.setForeground(new java.awt.Color(255, 255, 255));
        chkbxlimb.setText("Limbs");
        chkbxlimb.setBorder(null);
        chkbxlimb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkbxlimbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(chkbxliv, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(orgnlookinglbl))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(chkbxlimb, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(orgnlookinglbl)
                .addGap(18, 18, 18)
                .addComponent(chkbxliv, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(chkbxlimb, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );

        btnupld.setFont(new java.awt.Font("Dubai Medium", 0, 12)); // NOI18N
        btnupld.setText("Upload");
        btnupld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupldActionPerformed(evt);
            }
        });

        btnsvc.setFont(new java.awt.Font("Dubai Medium", 0, 12)); // NOI18N
        btnsvc.setText("Save");
        btnsvc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsvcActionPerformed(evt);
            }
        });

        btnupdt.setFont(new java.awt.Font("Dubai Medium", 0, 12)); // NOI18N
        btnupdt.setText("Update");
        btnupdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblpicture, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(btnupld))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(contlabel)
                            .addComponent(txtcont, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(namelabel)
                            .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(citylabel)
                            .addComponent(txtcity, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtaddr, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelstat)
                            .addComponent(txtstat, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addrlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(80, 80, 80)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emercontlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emerconttxt, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rellabel)
                            .addComponent(namecontlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(relnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboxgend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gendlabel)
                            .addComponent(doblbl)
                            .addComponent(dtpik1txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(namreltxt, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelzcode)
                            .addComponent(txtzcode, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnsvc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnupdt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(29, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {emerconttxt, txtaddr});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(btnupld)
                                .addGap(82, 82, 82))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblpicture, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(namelabel)
                            .addComponent(gendlabel))
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboxgend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnsvc)
                        .addGap(28, 28, 28)
                        .addComponent(btnupdt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelzcode)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtzcode, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(doblbl)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(dtpik1txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(66, 66, 66))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(emercontlabel)
                                                .addGap(9, 9, 9)
                                                .addComponent(emerconttxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(4, 4, 4)))
                                        .addComponent(rellabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(namreltxt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(contlabel)
                                        .addGap(12, 12, 12)
                                        .addComponent(txtcont, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtcity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(addrlabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtaddr, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(citylabel)
                                                .addGap(40, 40, 40)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(namecontlbl))
                            .addComponent(labelstat))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(relnametxt, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                            .addComponent(txtstat))))
                .addGap(162, 162, 162))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 580, 460));

        headerlabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        headerlabel.setForeground(new java.awt.Color(255, 255, 255));
        headerlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerlabel.setText("Receiver Details");
        add(headerlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 0, 1100, 50));

        bgdimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/receiver1_1100x800.png"))); // NOI18N
        add(bgdimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 800));
    }// </editor-fold>//GEN-END:initComponents

    private void txtnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnameFocusGained
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txtnameFocusGained

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void txtcontFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcontFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcontFocusGained

    private void txtcontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcontActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcontActionPerformed

    private void txtaddrFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtaddrFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaddrFocusGained

    private void txtaddrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtaddrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaddrActionPerformed

    private void txtcityFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcityFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcityFocusGained

    private void txtcityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcityActionPerformed

    private void txtstatFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtstatFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstatFocusGained

    private void txtstatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstatActionPerformed

    private void txtzcodeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtzcodeFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtzcodeFocusGained

    private void txtzcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtzcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtzcodeActionPerformed

    private void emerconttxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emerconttxtFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_emerconttxtFocusGained

    private void emerconttxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emerconttxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emerconttxtActionPerformed

    private void namreltxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_namreltxtFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_namreltxtFocusGained

    private void namreltxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namreltxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namreltxtActionPerformed

    private void relnametxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_relnametxtFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_relnametxtFocusGained

    private void relnametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relnametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_relnametxtActionPerformed

    private void btnupldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupldActionPerformed

          JFileChooser file = new JFileChooser();
          file.setCurrentDirectory(new File(System.getProperty("user.dir")));
          //filter the files
          FileNameExtensionFilter filter = new FileNameExtensionFilter("*.Images", "jpg","gif","png");
          file.addChoosableFileFilter(filter);
          int result = file.showSaveDialog(null);
           //if the user click on save in Jfilechooser
          if(result == JFileChooser.APPROVE_OPTION){
              File selectedFile = file.getSelectedFile();
              tempdP = new byte[(int) selectedFile.length()]; 
                FileInputStream fis;
             try {
                 fis = new FileInputStream(selectedFile);
                 fis.read(tempdP);
                 fis.close();
             } catch (IOException ex) {
                 Logger.getLogger(ManageDonorDetailsJPanel.class.getName()).log(Level.SEVERE, null, ex);
             }             
              lblpicture.setIcon(ResizeImage(selectedFile.getAbsolutePath()));
              lblpicture.setIcon(setPicture(selectedFile.getAbsolutePath(),lblpicture));
          }

          else if(result == JFileChooser.CANCEL_OPTION){
              System.out.println("No File Select");
          }
    }//GEN-LAST:event_btnupldActionPerformed
    
    private ImageIcon setPicture(String carImageLocation, JLabel carImage){

        ImageIcon imageCar;
        imageCar = new ImageIcon(carImageLocation);
        Image picCar = imageCar.getImage();
        Image resizedImage = picCar.getScaledInstance(carImage.getWidth(), carImage.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon selectedCarPicture = new ImageIcon(resizedImage);
        return selectedCarPicture;  
}
     
    private void btnsvcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsvcActionPerformed
        // TODO add your handling code here:
//        try {
//            Integer.parseInt(emergencyContactJTextField.getText());
//            Integer.parseInt(zipJTextField.getText());
//            Integer.parseInt(contactJTextField.getText());
//
//        } catch (NumberFormatException e) {
//            JOptionPane.showMessageDialog(null, "Contact Number and Zip code should be numberic", "Error", 0);
//            return;
//        }
        String pattern = ".*\\D.*";
        Pattern patternForZip = Pattern.compile(pattern);
        String zipCode1 = txtzcode.getText();
        String emergencyContact = emerconttxt.getText();
        String contact = txtcont.getText();
        Matcher matcherForZip = patternForZip.matcher(zipCode1);
         Matcher matcherForContact = patternForZip.matcher(contact);
           Matcher matcherForEContact = patternForZip.matcher(emergencyContact);
        if (matcherForZip.matches() == true || matcherForContact.matches() == true|| matcherForEContact.matches() == true) {
            JOptionPane.showMessageDialog(null, "Contact Number and Zip code should be numeric", "Error", 0);
			return;
        }
         
        if (txtaddr.getText().isEmpty()           || txtcity.getText().isEmpty()     ||
            txtcont.getText().isEmpty()           || namreltxt.getText().isEmpty() ||
            emerconttxt.getText().isEmpty()  || txtstat.getText().isEmpty()    ||
            txtzcode.getText().isEmpty()               || txtname.getText().isEmpty() ||
            namreltxt.getText().isEmpty() )
        { 
    
         JOptionPane.showMessageDialog(null, "All fields are mandatory", "Error", JOptionPane.ERROR_MESSAGE);
         return ;
        }
        
        
          Date currentDate = new Date();
          
          if (currentDate.equals(dtpik1txt.getDate()) || dtpik1txt.getDate().after(currentDate)) {
          
             JOptionPane.showMessageDialog(null, "Date should be past date", "Error", JOptionPane.ERROR_MESSAGE);
             return;
          }
          
          if (txtcont.getText().length() != 10 || emerconttxt.getText().length() != 10) {
             JOptionPane.showMessageDialog(null, "Contact information should be 10 number", "Error", JOptionPane.ERROR_MESSAGE);
             return;   
          }
          
          if (txtzcode.getText().length() != 5) {
             JOptionPane.showMessageDialog(null, "Zip code should be 5 digit", "Error", JOptionPane.ERROR_MESSAGE);
             return;   
          }
//          if(isAddValid(txtaddr.getText())){
//              JOptionPane.showMessageDialog(null, "Enter valid address", "Error", JOptionPane.ERROR_MESSAGE);
//             return;   
//          }
          
          if ( chkbxlimb.isSelected() || chkbxliv.isSelected() ) {
          user.setAddr(txtaddr.getText());
        user.setUrban(txtcity.getText());
        user.setPhoneNumber(txtcont.getText());
        user.setDOB(dtpik1txt.getDate());
        user.setGender((String) comboxgend.getSelectedItem());
        user.setEmergencyPhoneNumber(emerconttxt.getText());
        user.setRelationShip(namreltxt.getText());
        user.setState(txtstat.getText());
        user.setZip(txtzcode.getText());
        user.setLimbs(chkbxlimb.isSelected());
        user.setLiver(chkbxliv.isSelected());
        user.setdP(tempdP);
        JOptionPane.showMessageDialog(null, "Profile Updated Sucessfully"); 
        user.setCompleteProfile(true);
        txtaddr.setEditable(false);
        txtcity.setEditable(false);
        txtcont.setEditable(false);
        dtpik1txt.setEnabled(false);
        comboxgend.setEnabled(false);
        emerconttxt.setEditable(false);
        txtstat.setEditable(false);
        namreltxt.setEditable(false);
        txtzcode.setEditable(false); 
        chkbxlimb.setEnabled(false);
        chkbxliv.setEnabled(false);
        btnupdt.setEnabled(true);
        btnsvc.setEnabled(false);
        btnupld.setEnabled(false);
            
          }
          else{
          JOptionPane.showMessageDialog(null, "Please select organ to donate", "Error", JOptionPane.ERROR_MESSAGE);
             return;
          }
        
        
    }//GEN-LAST:event_btnsvcActionPerformed

    private void btnupdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdtActionPerformed
        // TODO add your handling code here:
        btnupdt.setEnabled(false);
        btnsvc.setEnabled(true);
        btnupld.setEnabled(true);
        txtaddr.setEditable(true);
        txtcity.setEditable(true);
        txtcont.setEditable(true);
        dtpik1txt.setEditable(true);
        comboxgend.setEnabled(true);
        emerconttxt.setEditable(true);
        txtstat.setEditable(true);
        namreltxt.setEditable(true);
        txtzcode.setEditable(true); 
        chkbxlimb.setEnabled(true);
        chkbxliv.setEnabled(true);
    }//GEN-LAST:event_btnupdtActionPerformed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        // TODO add your handling code here:
 
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseClicked

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MousePressed

    private void chkbxlimbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkbxlimbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkbxlimbActionPerformed
    
    public ImageIcon ResizeImage(String ImagePath)
    {
        ImageIcon MyImage = new ImageIcon(ImagePath);
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(lblpicture.getWidth(), lblpicture.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addrlabel;
    private javax.swing.JLabel bgdimg;
    private javax.swing.JButton btnsvc;
    private javax.swing.JButton btnupdt;
    private javax.swing.JButton btnupld;
    private javax.swing.JCheckBox chkbxlimb;
    private javax.swing.JCheckBox chkbxliv;
    private javax.swing.JLabel citylabel;
    private javax.swing.JComboBox comboxgend;
    private javax.swing.JLabel contlabel;
    private javax.swing.JLabel doblbl;
    private org.jdesktop.swingx.JXDatePicker dtpik1txt;
    private javax.swing.JLabel emercontlabel;
    private javax.swing.JTextField emerconttxt;
    private javax.swing.JLabel gendlabel;
    private javax.swing.JLabel headerlabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelstat;
    private javax.swing.JLabel labelzcode;
    private javax.swing.JLabel lblpicture;
    private javax.swing.JLabel namecontlbl;
    private javax.swing.JLabel namelabel;
    private javax.swing.JTextField namreltxt;
    private javax.swing.JLabel orgnlookinglbl;
    private javax.swing.JLabel rellabel;
    private javax.swing.JTextField relnametxt;
    private javax.swing.JTextField txtaddr;
    private javax.swing.JTextField txtcity;
    private javax.swing.JTextField txtcont;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtstat;
    private javax.swing.JTextField txtzcode;
    // End of variables declaration//GEN-END:variables

}
