/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Advocate;

import Backend.Connection.Connection;
import Backend.EcoSystem;
import Backend.Enterprise.Enterprise;
import static Backend.Enterprise.Enterprise.EnterpriseType.DeliveryDepartment;
import static Backend.Enterprise.Enterprise.EnterpriseType.LegalDepartment;
import static Backend.Enterprise.Enterprise.EnterpriseType.OrganBank;
import Backend.NGO.NGO;
import Backend.Organization.AdvocateOrganization;
import Backend.Organization.DeliveryOrganization;
import Backend.Organization.DoctorOrganization;
import Backend.Organization.Organization;
import Backend.UserAccount.UserAccount;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author harish
 */
public class AdvocateDocumentsJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private EcoSystem business;
    private UserAccount userAccount;
    private AdvocateOrganization coordinator;
    private Enterprise enterprise;
    private Connection connection;
    int flag =0; 
        private NGO ngo;

    /**
     * Creates new form ManageUsersJPanel
     */
    public AdvocateDocumentsJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, EcoSystem business, Enterprise enterprise,Connection connection, NGO ngo) {
        initComponents();
         this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.business = business;
        this.connection = connection;
        this.coordinator = (AdvocateOrganization)organization;
        this.enterprise = enterprise ;
        nameadvtxt.setText(userAccount.getEmployee().getName());
        namednrtxt.setText(connection.getDonorReq().getUser().getName());
        namercrtxt.setText(connection.getReceiverReq().getUser().getName());
        btnaprv.setEnabled(false);
        signrjct.setEnabled(false);
        this.ngo = ngo;
              
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        recDocumentBtn = new javax.swing.JButton();
        signdnr = new javax.swing.JButton();
        lbl = new javax.swing.JLabel();
        signrcr = new javax.swing.JButton();
        signadv = new javax.swing.JButton();
        signrjct = new javax.swing.JButton();
        docnamelbl = new javax.swing.JLabel();
        namednrtxt = new javax.swing.JTextField();
        recnamelbl = new javax.swing.JLabel();
        namercrtxt = new javax.swing.JTextField();
        nameadvlbl = new javax.swing.JLabel();
        nameadvtxt = new javax.swing.JTextField();
        btnaprv = new javax.swing.JButton();
        signnotclr = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        bgdimg = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        recDocumentBtn.setFont(new java.awt.Font("Dubai Medium", 0, 12)); // NOI18N
        recDocumentBtn.setText("Get Document");
        recDocumentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recDocumentBtnActionPerformed(evt);
            }
        });
        add(recDocumentBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 200, -1));

        signdnr.setFont(new java.awt.Font("Dubai Medium", 0, 12)); // NOI18N
        signdnr.setText("Donor");
        signdnr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signdnrActionPerformed(evt);
            }
        });
        add(signdnr, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 140, -1));
        add(lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 71, 401, 580));

        signrcr.setFont(new java.awt.Font("Dubai Medium", 0, 12)); // NOI18N
        signrcr.setText("Receiver");
        signrcr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signrcrActionPerformed(evt);
            }
        });
        add(signrcr, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 140, -1));

        signadv.setFont(new java.awt.Font("Dubai Medium", 0, 12)); // NOI18N
        signadv.setText("Clear");
        signadv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signadvActionPerformed(evt);
            }
        });
        add(signadv, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, 93, -1));

        signrjct.setFont(new java.awt.Font("Dubai Medium", 0, 12)); // NOI18N
        signrjct.setText("Reject");
        signrjct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signrjctActionPerformed(evt);
            }
        });
        add(signrjct, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, 200, -1));

        docnamelbl.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        docnamelbl.setText("Donor Name");
        add(docnamelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 200, -1));

        namednrtxt.setBorder(null);
        namednrtxt.setCaretColor(new java.awt.Color(30, 59, 92));
        namednrtxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                namednrtxtFocusGained(evt);
            }
        });
        namednrtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namednrtxtActionPerformed(evt);
            }
        });
        add(namednrtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 140, 22));

        recnamelbl.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        recnamelbl.setText("Recipient Name");
        add(recnamelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 200, -1));

        namercrtxt.setBorder(null);
        namercrtxt.setCaretColor(new java.awt.Color(30, 59, 92));
        namercrtxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                namercrtxtFocusGained(evt);
            }
        });
        namercrtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namercrtxtActionPerformed(evt);
            }
        });
        add(namercrtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 140, 22));

        nameadvlbl.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        nameadvlbl.setText("Advocate Name");
        add(nameadvlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 200, -1));

        nameadvtxt.setBorder(null);
        nameadvtxt.setCaretColor(new java.awt.Color(30, 59, 92));
        nameadvtxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameadvtxtFocusGained(evt);
            }
        });
        nameadvtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameadvtxtActionPerformed(evt);
            }
        });
        add(nameadvtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 140, 22));

        btnaprv.setFont(new java.awt.Font("Dubai Medium", 0, 12)); // NOI18N
        btnaprv.setText("Approve");
        btnaprv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaprvActionPerformed(evt);
            }
        });
        add(btnaprv, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, 200, -1));

        signnotclr.setFont(new java.awt.Font("Dubai Medium", 0, 12)); // NOI18N
        signnotclr.setText("Not Clear");
        signnotclr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signnotclrActionPerformed(evt);
            }
        });
        add(signnotclr, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, 93, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Document Signatures");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 54));

        bgdimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MedTech.png"))); // NOI18N
        add(bgdimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 800));
    }// </editor-fold>//GEN-END:initComponents

    boolean preparedDoc = false;
    private void recDocumentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recDocumentBtnActionPerformed

        if (preparedDoc) {
            return;
        }
        preparedDoc = true;

       // ImageIcon image = new ImageIcon(getClass().getResource("/Images/organ_Agreement.jpg"));
        flag++;
        BufferedImage img = null;
        try {
            img = ImageIO.read(new File("organ_Agreement.jpg"));
        } catch (IOException e) {
            e.printStackTrace();
        }
        Image dimg = img.getScaledInstance(lbl.getWidth(), lbl.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon imageIcon = new ImageIcon(dimg);
        lbl.setIcon(imageIcon);
    }//GEN-LAST:event_recDocumentBtnActionPerformed

   boolean donarDone = false;

    private void signdnrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signdnrActionPerformed

        if (!preparedDoc) {
            JOptionPane.showMessageDialog(null, "Please get Doc first", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (donarDone) {
            return;
        }
        donarDone = true;

        // TODO add your handling code here:
        //tLabel.removeAll();
        flag++;
         BufferedImage img1 = null;
        try {
            img1 = ImageIO.read(new File("organ_Agreement_Donor.jpg"));
        } catch (IOException e) {
            e.printStackTrace();
        }
        Image dimg = img1.getScaledInstance(lbl.getWidth(), lbl.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon imageIcon = new ImageIcon(dimg);
        lbl.setIcon(imageIcon);
    }//GEN-LAST:event_signdnrActionPerformed

    boolean rcrDone = false;

    private void signrcrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signrcrActionPerformed
            // TODO add your handling code here:
         if (!preparedDoc) {
            JOptionPane.showMessageDialog(null, "Please get Doc first", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (rcrDone) {
            return;
        }
        rcrDone = true;

        flag++;
          BufferedImage img1 = null;
        try {
            img1 = ImageIO.read(new File("organ_Agreement_DonorReceiver.jpg"));
        } catch (IOException e) {
            e.printStackTrace();
        }
        Image dimg = img1.getScaledInstance(lbl.getWidth(), lbl.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon imageIcon = new ImageIcon(dimg);
        lbl.setIcon(imageIcon);
    }//GEN-LAST:event_signrcrActionPerformed

           boolean signedDone = false;

    private void signadvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signadvActionPerformed
        // TODO add your handling code here:
        
        if (!preparedDoc) {
            JOptionPane.showMessageDialog(null, "Please get Doc first", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        
        if (signedDone) {
            return;
        }
        signedDone = true;

        flag++;
        if(flag==4){
            btnaprv.setEnabled(true);
            signnotclr.setEnabled(false);
        }
        else{
            signrjct.setEnabled(false);
        }
          BufferedImage img1 = null;
        try {
            img1 = ImageIO.read(new File("organ_Agreement_DonorReceiverAdvocate.jpg"));
        } catch (IOException e) {
            e.printStackTrace();
        }
        Image dimg = img1.getScaledInstance(lbl.getWidth(), lbl.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon imageIcon = new ImageIcon(dimg);
        lbl.setIcon(imageIcon);
    }//GEN-LAST:event_signadvActionPerformed

    private void signrjctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signrjctActionPerformed
        // TODO add your handling code here:
        
          BufferedImage img1 = null;
        try {
            img1 = ImageIO.read(new File("organ_Agreement_Rejected.jpg"));
        } catch (IOException e) {
            e.printStackTrace();
        }
        Image dimg = img1.getScaledInstance(lbl.getWidth(), lbl.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon imageIcon = new ImageIcon(dimg);
        lbl.setIcon(imageIcon);
        
            connection.setAdvStatus("Completed");
            connection.getReceiverReq().setOverallStatus("Rejected by Advocate.");
            connection.getDonorReq().setOverallStatus("Rejected by Advocate." );
            connection.setInventStatus("Rejected by Advocate.");
            JOptionPane.showMessageDialog(null, "Rejected  Successfully");
    }//GEN-LAST:event_signrjctActionPerformed

    private void namednrtxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_namednrtxtFocusGained
        // TODO add your handling code here:
        namednrtxt.setText("");
    }//GEN-LAST:event_namednrtxtFocusGained

    private void namednrtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namednrtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namednrtxtActionPerformed

    private void namercrtxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_namercrtxtFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_namercrtxtFocusGained

    private void namercrtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namercrtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namercrtxtActionPerformed

    private void nameadvtxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameadvtxtFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_nameadvtxtFocusGained

    private void nameadvtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameadvtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameadvtxtActionPerformed

    private void btnaprvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaprvActionPerformed
        // TODO add your handling code here:
        btnaprv.setEnabled(false);
        
        Enterprise DelEnt = null;
        Organization org = null;

        for (Enterprise allenterprise : ngo.getEnterpriseDirectory().getEnterpList()) {
            System.out.print(allenterprise.getName() + '\n');
            System.out.print(allenterprise.getEnterpriseType());
            System.out.print(allenterprise.getEnterpriseType().equals(LegalDepartment));
            if (allenterprise.getEnterpriseType().equals(DeliveryDepartment)) {
                DelEnt = allenterprise;
                for (Organization organization : DelEnt.getOrganizationDirectory().getOrganizationList()) {
                    System.out.print(organization.getName());
                    if (organization instanceof DeliveryOrganization) {
                        org = organization;
                        break;
                    }
                }

            }
        }


        
            if (org != null) {
            
            org.getConnectionDirectory().getconnecList().add(connection);
            System.out.println("Ikkada unna delivery");
            connection.setAdvStatus("Completed");
            connection.setDelStatus("Requested to Delivery");
            connection.getReceiverReq().setOverallStatus("Approved by Advocate, Now will be taken care by Delivery");
            connection.getDonorReq().setOverallStatus("Approved by Advocate, Now will be taken care by Delivery " );
            connection.setInventStatus("Approved By Advocate, Now will be taken cre by Delivery");
            JOptionPane.showMessageDialog(null, "Request Sent Successfully");
            } else {
            
                JOptionPane.showMessageDialog(null, "Delivery organization not present", "Error", JOptionPane.ERROR_MESSAGE);
            
            }
    }//GEN-LAST:event_btnaprvActionPerformed

    private void signnotclrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signnotclrActionPerformed
        // TODO add your handling code here:
        signrjct.setEnabled(true);
    }//GEN-LAST:event_signnotclrActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgdimg;
    private javax.swing.JButton btnaprv;
    private javax.swing.JLabel docnamelbl;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lbl;
    private javax.swing.JLabel nameadvlbl;
    private javax.swing.JTextField nameadvtxt;
    private javax.swing.JTextField namednrtxt;
    private javax.swing.JTextField namercrtxt;
    private javax.swing.JButton recDocumentBtn;
    private javax.swing.JLabel recnamelbl;
    private javax.swing.JButton signadv;
    private javax.swing.JButton signdnr;
    private javax.swing.JButton signnotclr;
    private javax.swing.JButton signrcr;
    private javax.swing.JButton signrjct;
    // End of variables declaration//GEN-END:variables
}
