/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Advocate;

import UI.Doctor.*;
import Backend.EcoSystem;
import Backend.Enterprise.Enterprise;
import Backend.Organization.AdvocateOrganization;
import Backend.Organization.Organization;
import Backend.UserAccount.UserAccount;
import UI.Donor.ManageDonorDetailsJPanel;
import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRootPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author harish
 */
public class ManageAdvocateDetailsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form UserDetailsJPanel
     */
    private EcoSystem system;
    private UserAccount userAccount;
     private Enterprise enterprise ;
     private AdvocateOrganization advocateOrg;
 private byte[] tempdP;
    public ManageAdvocateDetailsJPanel(UserAccount userAccount, EcoSystem system,Organization organization,Enterprise enterprise) {
        initComponents();
        this.system = system;
        this.userAccount = userAccount;
        this.enterprise=enterprise;
        this.advocateOrg = (AdvocateOrganization)organization;
        populateDefault();
       
       
    }
private ImageIcon setPicturebyte(byte[] byteArrayImage){

        ImageIcon imageCar;
        imageCar = new ImageIcon(byteArrayImage);
        Image picCar = imageCar.getImage();
        JLabel pictureLabel1 = new JLabel();
        pictureLabel1.setSize(107, 133);
        Image resizedImage = picCar.getScaledInstance(pictureLabel1.getWidth(), pictureLabel1.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon selectedCarPicture = new ImageIcon(resizedImage);
        return selectedCarPicture;  
}
    private void populateDefault() {
        btnsve.setEnabled(false);
        upldbtn.setEnabled(false);
        cmboxgen.removeAllItems();
        cmboxgen.addItem("Male");
        cmboxgen.addItem("Female");
        nametxt.setText(userAccount.getEmployee().getName());
        addrtxt.setText(userAccount.getEmployee().getAddr());
        txtcity.setText(userAccount.getEmployee().getUrban());
        conttxt.setText(userAccount.getEmployee().getPhoneNumber());
        dtpick1.setDate(userAccount.getEmployee().getDOB());
        cmboxgen.setSelectedItem(userAccount.getEmployee().getGender());
//        lgldepttxt.setText(enterprise.getName());
        txtstate.setText(userAccount.getEmployee().getState());
        zipcodetxt.setText(userAccount.getEmployee().getZip());
        txtorganization.setText(advocateOrg.getOrgName());
         if(userAccount.getEmployee().getdP() !=null){
        //Working line
         byte[] JLabelpictureLabel = userAccount.getEmployee().getdP();
        ImageIcon i = setPicturebyte(JLabelpictureLabel);
        phptolbl.setIcon(i);
        }
        else{
            System.err.println("No Image");
        }
        addrtxt.setEditable(false);
        txtcity.setEditable(false);
        conttxt.setEditable(false);
        dtpick1.setEditable(false);
        cmboxgen.setEnabled(false);
//        lgldepttxt.setEditable(false);
        txtstate.setEditable(false);
        txtorganization.setEditable(false);
        zipcodetxt.setEditable(false); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titlelabel = new javax.swing.JLabel();
        addresslabel = new javax.swing.JLabel();
        nametxt = new javax.swing.JTextField();
        txtcity = new javax.swing.JTextField();
        citylbl = new javax.swing.JLabel();
        addrtxt = new javax.swing.JTextField();
        contactlabel = new javax.swing.JLabel();
        conttxt = new javax.swing.JTextField();
        namelbl = new javax.swing.JLabel();
        txtstate = new javax.swing.JTextField();
        statelbl = new javax.swing.JLabel();
        zipcodelbl = new javax.swing.JLabel();
        zipcodetxt = new javax.swing.JTextField();
        phptolbl = new javax.swing.JLabel();
        genderlbl = new javax.swing.JLabel();
        cmboxgen = new javax.swing.JComboBox();
        doblbl = new javax.swing.JLabel();
        dtpick1 = new org.jdesktop.swingx.JXDatePicker();
        txtorganization = new javax.swing.JTextField();
        orglbl = new javax.swing.JLabel();
        upldbtn = new javax.swing.JButton();
        btnsve = new javax.swing.JButton();
        updbtn = new javax.swing.JButton();
        bgdimg = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titlelabel.setBackground(new java.awt.Color(255, 255, 255));
        titlelabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        titlelabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlelabel.setText("Advocate Details");
        add(titlelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 70));

        addresslabel.setBackground(new java.awt.Color(255, 255, 255));
        addresslabel.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        addresslabel.setText("Address");
        add(addresslabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, 65, -1));

        nametxt.setEditable(false);
        nametxt.setBorder(null);
        nametxt.setCaretColor(new java.awt.Color(30, 59, 92));
        nametxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nametxtFocusGained(evt);
            }
        });
        nametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nametxtActionPerformed(evt);
            }
        });
        add(nametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, 140, 22));

        txtcity.setBorder(null);
        txtcity.setCaretColor(new java.awt.Color(30, 59, 92));
        txtcity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtcityFocusGained(evt);
            }
        });
        txtcity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcityActionPerformed(evt);
            }
        });
        add(txtcity, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, 140, -1));

        citylbl.setBackground(new java.awt.Color(255, 255, 255));
        citylbl.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        citylbl.setText("City");
        add(citylbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, -1, -1));

        addrtxt.setBorder(null);
        addrtxt.setCaretColor(new java.awt.Color(30, 59, 92));
        addrtxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                addrtxtFocusGained(evt);
            }
        });
        addrtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addrtxtActionPerformed(evt);
            }
        });
        add(addrtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 270, 140, 17));

        contactlabel.setBackground(new java.awt.Color(255, 255, 255));
        contactlabel.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        contactlabel.setText("Contact");
        add(contactlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, -1, -1));

        conttxt.setBorder(null);
        conttxt.setCaretColor(new java.awt.Color(30, 59, 92));
        conttxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                conttxtFocusGained(evt);
            }
        });
        conttxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conttxtActionPerformed(evt);
            }
        });
        add(conttxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 140, 19));

        namelbl.setBackground(new java.awt.Color(255, 255, 255));
        namelbl.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        namelbl.setText("Name");
        add(namelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, -1, -1));

        txtstate.setBorder(null);
        txtstate.setCaretColor(new java.awt.Color(30, 59, 92));
        txtstate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtstateFocusGained(evt);
            }
        });
        txtstate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstateActionPerformed(evt);
            }
        });
        add(txtstate, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, 140, -1));

        statelbl.setBackground(new java.awt.Color(255, 255, 255));
        statelbl.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        statelbl.setText("State");
        add(statelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 310, -1, -1));

        zipcodelbl.setBackground(new java.awt.Color(255, 255, 255));
        zipcodelbl.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        zipcodelbl.setText("Zip Code");
        add(zipcodelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 310, -1, -1));

        zipcodetxt.setBorder(null);
        zipcodetxt.setCaretColor(new java.awt.Color(30, 59, 92));
        zipcodetxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                zipcodetxtFocusGained(evt);
            }
        });
        zipcodetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zipcodetxtActionPerformed(evt);
            }
        });
        add(zipcodetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 330, 140, -1));

        phptolbl.setBackground(new java.awt.Color(255, 255, 255));
        phptolbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        phptolbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(phptolbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 107, 133));

        genderlbl.setBackground(new java.awt.Color(255, 255, 255));
        genderlbl.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        genderlbl.setText("Gender");
        add(genderlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, -1, -1));

        cmboxgen.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(cmboxgen, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, -1, -1));

        doblbl.setBackground(new java.awt.Color(255, 255, 255));
        doblbl.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        doblbl.setText("Birth Date");
        add(doblbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 190, -1, -1));

        dtpick1.setBackground(new java.awt.Color(255, 255, 255));
        add(dtpick1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 210, -1, -1));

        txtorganization.setEditable(false);
        txtorganization.setBorder(null);
        txtorganization.setCaretColor(new java.awt.Color(30, 59, 92));
        txtorganization.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtorganizationFocusGained(evt);
            }
        });
        txtorganization.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtorganizationActionPerformed(evt);
            }
        });
        add(txtorganization, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 270, 140, -1));

        orglbl.setBackground(new java.awt.Color(255, 255, 255));
        orglbl.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        orglbl.setText("Organization");
        add(orglbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 250, -1, -1));

        upldbtn.setBackground(new java.awt.Color(32, 93, 122));
        upldbtn.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        upldbtn.setForeground(new java.awt.Color(255, 255, 255));
        upldbtn.setText("Upload");
        upldbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upldbtnActionPerformed(evt);
            }
        });
        add(upldbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, -1, -1));

        btnsve.setBackground(new java.awt.Color(32, 93, 122));
        btnsve.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        btnsve.setForeground(new java.awt.Color(255, 255, 255));
        btnsve.setText("Save");
        btnsve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsveActionPerformed(evt);
            }
        });
        add(btnsve, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 430, 117, -1));

        updbtn.setBackground(new java.awt.Color(32, 93, 122));
        updbtn.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        updbtn.setForeground(new java.awt.Color(255, 255, 255));
        updbtn.setText("Update");
        updbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updbtnActionPerformed(evt);
            }
        });
        add(updbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 430, 117, -1));

        bgdimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/advacate_employe.jpg"))); // NOI18N
        bgdimg.setMaximumSize(null);
        bgdimg.setMinimumSize(null);
        bgdimg.setPreferredSize(null);
        add(bgdimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void nametxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nametxtFocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_nametxtFocusGained

    private void nametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nametxtActionPerformed

    private void conttxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_conttxtFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_conttxtFocusGained

    private void conttxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conttxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_conttxtActionPerformed

    private void addrtxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addrtxtFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_addrtxtFocusGained

    private void addrtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addrtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addrtxtActionPerformed

    private void txtcityFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcityFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcityFocusGained

    private void txtcityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcityActionPerformed

    private void txtstateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtstateFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstateFocusGained

    private void txtstateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstateActionPerformed

    private void zipcodetxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_zipcodetxtFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_zipcodetxtFocusGained

    private void zipcodetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zipcodetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zipcodetxtActionPerformed

    private void txtorganizationFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtorganizationFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtorganizationFocusGained

    private void txtorganizationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtorganizationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtorganizationActionPerformed

    private void upldbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upldbtnActionPerformed
        // TODO add your handling code here:
        JFileChooser file = new JFileChooser();
          file.setCurrentDirectory(new File(System.getProperty("user.dir")));
          //filter the files
          FileNameExtensionFilter filter = new FileNameExtensionFilter("*.Images", "jpg","gif","png");
          file.addChoosableFileFilter(filter);
          int result = file.showSaveDialog(null);
           //if the user click on save in Jfilechooser
          if(result == JFileChooser.APPROVE_OPTION){
              File selectedFile = file.getSelectedFile();
              tempdP = new byte[(int) selectedFile.length()]; 
                FileInputStream fis;
             try {
                 fis = new FileInputStream(selectedFile);
                 fis.read(tempdP);
                 fis.close();
             } catch (IOException ex) {
                 Logger.getLogger(ManageDonorDetailsJPanel.class.getName()).log(Level.SEVERE, null, ex);
             }             
              phptolbl.setIcon(ResizeImage(selectedFile.getAbsolutePath()));
              phptolbl.setIcon(setPicture(selectedFile.getAbsolutePath(),phptolbl));
          }

          else if(result == JFileChooser.CANCEL_OPTION){
              System.out.println("No File Select");
          }
    }//GEN-LAST:event_upldbtnActionPerformed
private ImageIcon setPicture(String carImageLocation, JLabel carImage){

        ImageIcon imageCar;
        imageCar = new ImageIcon(carImageLocation);
        Image picCar = imageCar.getImage();
        Image resizedImage = picCar.getScaledInstance(carImage.getWidth(), carImage.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon selectedCarPicture = new ImageIcon(resizedImage);
        return selectedCarPicture;  
}
     
    private void btnsveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsveActionPerformed
        // TODO add your handling code here:
        
        
           if (addrtxt.getText().isEmpty()           || txtcity.getText().isEmpty()     ||
            conttxt.getText().isEmpty()           || txtstate.getText().isEmpty()    ||
            zipcodetxt.getText().isEmpty()               || nametxt.getText().isEmpty() )
            
        { 
    
         JOptionPane.showMessageDialog(null, "All fields are mandatory", "Error", JOptionPane.ERROR_MESSAGE);
         return ;
        }
        
          Date currentDate = new Date();
          
          if (currentDate.equals(dtpick1.getDate()) || dtpick1.getDate().after(currentDate)) {
          
             JOptionPane.showMessageDialog(null, "Date should be past date", "Error", JOptionPane.ERROR_MESSAGE);
             return;
          }
          
          if (conttxt.getText().length() != 10 ) {
             JOptionPane.showMessageDialog(null, "Contact information should be 10 number", "Error", JOptionPane.ERROR_MESSAGE);
             return;   
          }
          
          if (zipcodetxt.getText().length() != 5) {
             JOptionPane.showMessageDialog(null, "Zip code should be 5 digit", "Error", JOptionPane.ERROR_MESSAGE);
             return;   
          }
        
        
        
        userAccount.getEmployee().setAddr(addrtxt.getText());
        userAccount.getEmployee().setUrban(txtcity.getText());
        userAccount.getEmployee().setPhoneNumber(conttxt.getText());
        userAccount.getEmployee().setDOB(dtpick1.getDate());
        userAccount.getEmployee().setGender((String) cmboxgen.getSelectedItem());
//        userAccount.getEmployee().setEmergencyPhoneNumber(lgldepttxt.getText());
        userAccount.getEmployee().setRelationShip(txtorganization.getText());
        userAccount.getEmployee().setState(txtstate.getText());
       userAccount.getEmployee().setZip(zipcodetxt.getText());
         userAccount.getEmployee().setPhotoLabel(phptolbl);
         userAccount.getEmployee().setdP(tempdP);
        JOptionPane.showMessageDialog(null, "Profile Updated Sucessfully");   
        addrtxt.setEditable(false);
        txtcity.setEditable(false);
        conttxt.setEditable(false);
        dtpick1.setEnabled(false);
        cmboxgen.setEnabled(false);
//        lgldepttxt.setEditable(false);
        txtstate.setEditable(false);
        txtorganization.setEditable(false);
        zipcodetxt.setEditable(false);      
        updbtn.setEnabled(true);
        btnsve.setEnabled(false);
        upldbtn.setEnabled(false);
        
       
    }//GEN-LAST:event_btnsveActionPerformed

    private void updbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updbtnActionPerformed
        // TODO add your handling code here:
        updbtn.setEnabled(false);
        btnsve.setEnabled(true);
        upldbtn.setEnabled(true);
        addrtxt.setEditable(true);
        txtcity.setEditable(true);
        conttxt.setEditable(true);
        dtpick1.setEditable(true);
        cmboxgen.setEnabled(true);
//        lgldepttxt.setEditable(true);
        txtstate.setEditable(true);
        txtorganization.setEditable(true);
        zipcodetxt.setEditable(true); 
    }//GEN-LAST:event_updbtnActionPerformed
    
    public ImageIcon ResizeImage(String ImagePath)
    {
        ImageIcon MyImage = new ImageIcon(ImagePath);
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(phptolbl.getWidth(), phptolbl.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addresslabel;
    private javax.swing.JTextField addrtxt;
    private javax.swing.JLabel bgdimg;
    private javax.swing.JButton btnsve;
    private javax.swing.JLabel citylbl;
    private javax.swing.JComboBox cmboxgen;
    private javax.swing.JLabel contactlabel;
    private javax.swing.JTextField conttxt;
    private javax.swing.JLabel doblbl;
    private org.jdesktop.swingx.JXDatePicker dtpick1;
    private javax.swing.JLabel genderlbl;
    private javax.swing.JLabel namelbl;
    private javax.swing.JTextField nametxt;
    private javax.swing.JLabel orglbl;
    private javax.swing.JLabel phptolbl;
    private javax.swing.JLabel statelbl;
    private javax.swing.JLabel titlelabel;
    private javax.swing.JTextField txtcity;
    private javax.swing.JTextField txtorganization;
    private javax.swing.JTextField txtstate;
    private javax.swing.JButton updbtn;
    private javax.swing.JButton upldbtn;
    private javax.swing.JLabel zipcodelbl;
    private javax.swing.JTextField zipcodetxt;
    // End of variables declaration//GEN-END:variables

}
