/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Delivery;

import Backend.DB4OUtil.DB4OUtil;
import Backend.EcoSystem;
import Backend.Enterprise.Enterprise;
import Backend.Organization.DeliveryOrganization;
import Backend.Organization.Organization;
import Backend.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JPanel;
import static javax.swing.SwingUtilities.getWindowAncestor;
import org.jdesktop.swingx.JXFrame;

/**
 *
 * @author nehar
 */
public class DeliveryDashBoardJPanel extends javax.swing.JFrame {

    /**
     * Creates new form DeliveryDashBoardJPanel
     */
    private EcoSystem system;
    private Enterprise enterprise ;
    private DB4OUtil dB4OUtil;
    private UserAccount userAccount;
    private DeliveryOrganization delOrganization;
    public DeliveryDashBoardJPanel(UserAccount account, Organization organization, EcoSystem system,DB4OUtil dB4OUtil,Enterprise enterprise) {
        initComponents();
        this.dB4OUtil = dB4OUtil;
        this.system = system;
         this.enterprise = enterprise ;
        this.dB4OUtil = dB4OUtil;
        this.system = system;
        this.userAccount =account;
        this.delOrganization = (DeliveryOrganization)organization;
                           this.setExtendedState(JXFrame.MAXIMIZED_BOTH);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane4 = new javax.swing.JSplitPane();
        mngadmn = new javax.swing.JPanel();
        reqmng = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        btnprf = new javax.swing.JPanel();
        lblprofile = new javax.swing.JLabel();
        usrproccont = new javax.swing.JPanel();

        setMaximumSize(null);
        setMinimumSize(null);
        setUndecorated(true);
        setPreferredSize(null);
        getContentPane().setLayout(new java.awt.GridLayout(1, 1));

        jSplitPane4.setBackground(new java.awt.Color(55, 96, 128));
        jSplitPane4.setDividerSize(0);

        mngadmn.setBackground(new java.awt.Color(18, 74, 111));

        reqmng.setBackground(new java.awt.Color(18, 74, 111));
        reqmng.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                reqmngMousePressed(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/request x 32.png"))); // NOI18N
        jLabel8.setText(" Request");

        javax.swing.GroupLayout reqmngLayout = new javax.swing.GroupLayout(reqmng);
        reqmng.setLayout(reqmngLayout);
        reqmngLayout.setHorizontalGroup(
            reqmngLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reqmngLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        reqmngLayout.setVerticalGroup(
            reqmngLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reqmngLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        back.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logoutx32.png"))); // NOI18N
        back.setToolTipText("");
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                backMousePressed(evt);
            }
        });

        btnprf.setBackground(new java.awt.Color(18, 74, 111));
        btnprf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnprfMousePressed(evt);
            }
        });

        lblprofile.setBackground(new java.awt.Color(0, 0, 0));
        lblprofile.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        lblprofile.setForeground(new java.awt.Color(255, 255, 255));
        lblprofile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblprofile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/account x 32.png"))); // NOI18N
        lblprofile.setText("Profile");

        javax.swing.GroupLayout btnprfLayout = new javax.swing.GroupLayout(btnprf);
        btnprf.setLayout(btnprfLayout);
        btnprfLayout.setHorizontalGroup(
            btnprfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnprfLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(lblprofile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnprfLayout.setVerticalGroup(
            btnprfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnprfLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblprofile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout mngadmnLayout = new javax.swing.GroupLayout(mngadmn);
        mngadmn.setLayout(mngadmnLayout);
        mngadmnLayout.setHorizontalGroup(
            mngadmnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(reqmng, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnprf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mngadmnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        mngadmnLayout.setVerticalGroup(
            mngadmnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mngadmnLayout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(btnprf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(reqmng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(back)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPane4.setLeftComponent(mngadmn);

        usrproccont.setBackground(new java.awt.Color(18, 74, 111));
        usrproccont.setLayout(new java.awt.CardLayout());
        jSplitPane4.setRightComponent(usrproccont);

        getContentPane().add(jSplitPane4);
    }// </editor-fold>//GEN-END:initComponents

    private void reqmngMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reqmngMousePressed
        // TODO add your handling code here:
        setColor(reqmng);
        resetColor(new JPanel[]{btnprf});
        DeliveryAssistantWorkAreaJPanel deliveryJpanel = new DeliveryAssistantWorkAreaJPanel(usrproccont, userAccount, delOrganization, system ,enterprise);
        usrproccont.add("DeliveryAssistantWorkAreaJPanel",deliveryJpanel);
        CardLayout layout = (CardLayout) usrproccont.getLayout();
        layout.next(usrproccont);
    }//GEN-LAST:event_reqmngMousePressed

    private void backMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMousePressed
        // TODO add your handling code here:
        this.dispose();
        dB4OUtil.storeSystem(system);
    }//GEN-LAST:event_backMousePressed

    private void btnprfMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnprfMousePressed
        // TODO add your handling code here:
        setColor(btnprf);
        resetColor(new JPanel[]{reqmng});
        ManageDeliveryDetailsJPanel coUserPanel = new ManageDeliveryDetailsJPanel(userAccount,system,delOrganization,enterprise);
        usrproccont.add("ManageDeliveryDetailsJPanel",coUserPanel);
        CardLayout layout = (CardLayout) usrproccont.getLayout();
        layout.next(usrproccont);
        
    }//GEN-LAST:event_btnprfMousePressed
private void setColor(JPanel pane)
    {
        pane.setBackground(new Color(50, 62, 168));
    }
    
    private void resetColor(JPanel [] pane)
    {
        for(int i=0;i<pane.length;i++){
           pane[i].setBackground(new Color(23,35,51));
           
        } 
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JPanel btnprf;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSplitPane jSplitPane4;
    private javax.swing.JLabel lblprofile;
    private javax.swing.JPanel mngadmn;
    private javax.swing.JPanel reqmng;
    private javax.swing.JPanel usrproccont;
    // End of variables declaration//GEN-END:variables
}
