/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.SystemAdmin;

import Backend.EcoSystem;
import Backend.Enterprise.Enterprise;
import Backend.NGO.NGO;
import Backend.UserAccount.UserAccount;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nehar
 */
public class ManageEnterpriseJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageEnterpriseJPanel
     */
     private JPanel userProcessContainer;
     private EcoSystem ecosystem ;
     private UserAccount useraccount;
    public ManageEnterpriseJPanel(JPanel userProcessContainer, EcoSystem ecosystem, UserAccount UA) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem ;
        this.useraccount = UA;
        clearfields();
        populateDefault();
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerlabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblentp = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        entplabel = new javax.swing.JLabel();
        btncreateentp = new javax.swing.JButton();
        lblname = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        lblcont = new javax.swing.JLabel();
        lblzcode = new javax.swing.JLabel();
        lblnetw = new javax.swing.JLabel();
        comboxntw = new javax.swing.JComboBox();
        labelentptype = new javax.swing.JLabel();
        comboxentptype = new javax.swing.JComboBox();
        txtcont = new javax.swing.JTextField();
        txtzcode = new javax.swing.JTextField();
        bgdimg = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headerlabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        headerlabel.setForeground(new java.awt.Color(255, 255, 255));
        headerlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerlabel.setText("Manage Enterprise");
        add(headerlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 60));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tblentp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "NGO", "Enterprise Type", "Name", "Phone Number", "Zip code"
            }
        ));
        tblentp.setEnabled(false);
        tblentp.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tblentp);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 560, 100));

        jPanel2.setBackground(new java.awt.Color(8, 21, 49));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel2.setPreferredSize(new java.awt.Dimension(250, 400));
        jPanel2.setRequestFocusEnabled(false);
        jPanel2.setVerifyInputWhenFocusTarget(false);

        entplabel.setFont(new java.awt.Font("Dubai Medium", 1, 14)); // NOI18N
        entplabel.setForeground(new java.awt.Color(255, 255, 255));
        entplabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        entplabel.setText("Enterprise");

        btncreateentp.setFont(new java.awt.Font("Dubai Medium", 0, 13)); // NOI18N
        btncreateentp.setText("CREATE");
        btncreateentp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncreateentpActionPerformed(evt);
            }
        });

        lblname.setFont(new java.awt.Font("Dubai Medium", 0, 12)); // NOI18N
        lblname.setForeground(new java.awt.Color(255, 255, 255));
        lblname.setText("Name");

        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });

        lblcont.setFont(new java.awt.Font("Dubai Medium", 0, 12)); // NOI18N
        lblcont.setForeground(new java.awt.Color(255, 255, 255));
        lblcont.setText("Phone Num");

        lblzcode.setFont(new java.awt.Font("Dubai Medium", 0, 12)); // NOI18N
        lblzcode.setForeground(new java.awt.Color(255, 255, 255));
        lblzcode.setText("Zip code");

        lblnetw.setFont(new java.awt.Font("Dubai Medium", 0, 12)); // NOI18N
        lblnetw.setForeground(new java.awt.Color(255, 255, 255));
        lblnetw.setText("NGO ");

        comboxntw.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboxntw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboxntwActionPerformed(evt);
            }
        });

        labelentptype.setFont(new java.awt.Font("Dubai Medium", 0, 12)); // NOI18N
        labelentptype.setForeground(new java.awt.Color(255, 255, 255));
        labelentptype.setText("Enterprise Type");

        comboxentptype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboxentptype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboxentptypeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(entplabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btncreateentp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelentptype)
                            .addComponent(lblnetw, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblname, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblcont, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblzcode, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtname)
                            .addComponent(comboxntw, 0, 161, Short.MAX_VALUE)
                            .addComponent(comboxentptype, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtcont)
                            .addComponent(txtzcode, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(entplabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnetw, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboxntw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelentptype, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboxentptype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblname, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcont, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcont, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblzcode, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtzcode, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btncreateentp, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 260, 340));

        bgdimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/enterprise_employe.png"))); // NOI18N
        bgdimg.setMaximumSize(null);
        bgdimg.setMinimumSize(null);
        bgdimg.setPreferredSize(null);
        add(bgdimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btncreateentpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncreateentpActionPerformed
        // TODO add your handling code here:
        NGO ngo = (NGO) comboxntw.getSelectedItem();
        Enterprise.EnterpriseType type = (Enterprise.EnterpriseType) comboxentptype.getSelectedItem();
        
        if (ngo == null || type == null) {
            JOptionPane.showMessageDialog(null, "Invalid Input!");
            return;
        }
        
        for (Enterprise enterprise : ngo.getEnterpriseDirectory().getEnterpList()) {
            if (enterprise.getEnterpriseType() == type ) {
                JOptionPane.showMessageDialog(null, "Enterbrise type alreday exist in organization!");
                return;
            }
        }
        
//        try {
            //contactField.getText();
            //zipCode.getText();

//        } catch (NumberFormatException e) {
//            JOptionPane.showMessageDialog(null, "Contact Number and Zip code should be numeric", "Error", 0);
//            return;
//        }
        String pattern = ".*\\D.*";
        Pattern patternForZip = Pattern.compile(pattern);
        String zipCode1 = txtzcode.getText();
        String contact = txtcont.getText();
        Matcher matcherForZip = patternForZip.matcher(zipCode1);
         Matcher matcherForContact = patternForZip.matcher(contact);
        if (matcherForZip.matches() == true || matcherForContact.matches() == true) {
            JOptionPane.showMessageDialog(null, "Contact Number and Zip code should be numeric", "Error", 0);
			return;
        }
        
        
        if (txtcont.getText().length() != 10 || txtzcode.getText().length() != 5){
           JOptionPane.showMessageDialog(null, "Contact number should be 10 digit and Zip should be 5 digit" , "Error", JOptionPane.ERROR_MESSAGE);
           return;
        }
       System.out.println(ngo.getEnterpriseDirectory().getEnterpList());
       System.out.println(1);
       for (Enterprise ent : ngo.getEnterpriseDirectory().getEnterpList()) {
       System.out.println(ent.getName());
       if (ent.getName() != null && ent.getName().equals(txtname.getText())) {
           JOptionPane.showMessageDialog(null, "Enterprise name cannot be same" , "Error", JOptionPane.ERROR_MESSAGE);
           return;
       
       }
       
       }

        String name = txtname.getText();

        Enterprise enterprise = ngo.getEnterpriseDirectory().createAndAddEnterprise(name, type);
        enterprise.setAddress(txtzcode.getText());
        enterprise.setPhoneNumber(txtcont.getText());
        
        enterprise.setName(name);
        JOptionPane.showMessageDialog(null, "Enterprise " + name + " is created sucessfully");
        clearfields();

        populateTable();
    }//GEN-LAST:event_btncreateentpActionPerformed

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void comboxentptypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboxentptypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboxentptypeActionPerformed

    private void comboxntwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboxntwActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboxntwActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgdimg;
    private javax.swing.JButton btncreateentp;
    private javax.swing.JComboBox comboxentptype;
    private javax.swing.JComboBox comboxntw;
    private javax.swing.JLabel entplabel;
    private javax.swing.JLabel headerlabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelentptype;
    private javax.swing.JLabel lblcont;
    private javax.swing.JLabel lblname;
    private javax.swing.JLabel lblnetw;
    private javax.swing.JLabel lblzcode;
    private javax.swing.JTable tblentp;
    private javax.swing.JTextField txtcont;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtzcode;
    // End of variables declaration//GEN-END:variables

    private void populateDefault() {

        comboxntw.removeAllItems();
        comboxentptype.removeAllItems();
        for (NGO ngo : ecosystem.getngoList()) {
            if (useraccount.getUsername().equals(ngo.getName()) || useraccount.getUsername().equals("sysadmin")) {
                comboxntw.addItem(ngo);
            }
        }

        for (Enterprise.EnterpriseType type : Enterprise.EnterpriseType.values()) {

            comboxentptype.addItem(type);
        }
    }

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblentp.getModel();

        model.setRowCount(0);
        for (NGO ngo : ecosystem.getngoList()) {
            System.out.println(ngo);
            System.out.println(ngo.getEnterpriseDirectory().getEnterpList());
            if (useraccount.getUsername().equals(ngo.getName()) || useraccount.getUsername().equals("sysadmin")) {
                if (ngo.getEnterpriseDirectory().getEnterpList() != null) {
                    for (Enterprise enterprise : ngo.getEnterpriseDirectory().getEnterpList()) {
                        Object[] row = new Object[5];
                        row[0] = ngo.getName();
                        row[1] = enterprise.getEnterpriseType().getValue();
                        row[2] = enterprise;
                        row[3] = enterprise.getPhoneNumber();
                        row[4] = enterprise.getAddress();

                        model.addRow(row);
                    }
                }
            }
        }
    }

    private void clearfields() {
//       nameTextField.setText("");
//       zipCode.setText("");
//       contactField.setText("");
    }
}
