/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.SystemAdmin;

import Backend.DB4OUtil.DB4OUtil;
import Backend.EcoSystem;
import Backend.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JPanel;
import static javax.swing.SwingUtilities.getWindowAncestor;
import org.jdesktop.swingx.JXFrame;

/**
 *
 * @author nehar
 */
public class SysAdminDashboardJPanel extends javax.swing.JFrame
{

    /**
     * Creates new form SysAdminDashboardJPanel
     */private EcoSystem ecosystem;
    private UserAccount UA;
    private DB4OUtil dB4OUtil;
    public SysAdminDashboardJPanel(EcoSystem ecosystem,DB4OUtil dB4OUtil,UserAccount UA) {
        initComponents();
         this.ecosystem=ecosystem;
         this.dB4OUtil = dB4OUtil;
         this.UA = UA;
         this.setExtendedState(JXFrame.MAXIMIZED_BOTH);
         entpmanagebuttonMousePressed(null);

    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane4 = new javax.swing.JSplitPane();
        admnmng = new javax.swing.JPanel();
        btnmngauth = new javax.swing.JPanel();
        accmangbtn = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        entpmanagebutton = new javax.swing.JPanel();
        mngemntlbl = new javax.swing.JLabel();
        userProcessContainer1 = new javax.swing.JPanel();

        setForeground(new java.awt.Color(30, 50, 71));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridLayout(1, 1));

        jSplitPane4.setDividerSize(0);
        jSplitPane4.setForeground(new java.awt.Color(55, 96, 128));

        admnmng.setBackground(new java.awt.Color(8, 21, 49));

        btnmngauth.setBackground(new java.awt.Color(8, 21, 49));
        btnmngauth.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnmngauthMousePressed(evt);
            }
        });

        accmangbtn.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        accmangbtn.setForeground(new java.awt.Color(255, 255, 255));
        accmangbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        accmangbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/authx32.png"))); // NOI18N
        accmangbtn.setText("Manage Access");
        accmangbtn.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                accmangbtnVetoableChange(evt);
            }
        });

        javax.swing.GroupLayout btnmngauthLayout = new javax.swing.GroupLayout(btnmngauth);
        btnmngauth.setLayout(btnmngauthLayout);
        btnmngauthLayout.setHorizontalGroup(
            btnmngauthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnmngauthLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(accmangbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnmngauthLayout.setVerticalGroup(
            btnmngauthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnmngauthLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(accmangbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        back.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logoutx32.png"))); // NOI18N
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                backMousePressed(evt);
            }
        });

        entpmanagebutton.setBackground(new java.awt.Color(8, 21, 49));
        entpmanagebutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                entpmanagebuttonMousePressed(evt);
            }
        });

        mngemntlbl.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        mngemntlbl.setForeground(new java.awt.Color(255, 255, 255));
        mngemntlbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mngemntlbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/enterprisex32.png"))); // NOI18N
        mngemntlbl.setText("Manage Enterprise");
        mngemntlbl.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                mngemntlblVetoableChange(evt);
            }
        });

        javax.swing.GroupLayout entpmanagebuttonLayout = new javax.swing.GroupLayout(entpmanagebutton);
        entpmanagebutton.setLayout(entpmanagebuttonLayout);
        entpmanagebuttonLayout.setHorizontalGroup(
            entpmanagebuttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(entpmanagebuttonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mngemntlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(7, 7, 7))
        );
        entpmanagebuttonLayout.setVerticalGroup(
            entpmanagebuttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, entpmanagebuttonLayout.createSequentialGroup()
                .addComponent(mngemntlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout admnmngLayout = new javax.swing.GroupLayout(admnmng);
        admnmng.setLayout(admnmngLayout);
        admnmngLayout.setHorizontalGroup(
            admnmngLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnmngauth, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(entpmanagebutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(admnmngLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        admnmngLayout.setVerticalGroup(
            admnmngLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(admnmngLayout.createSequentialGroup()
                .addGap(245, 245, 245)
                .addComponent(entpmanagebutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnmngauth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(329, Short.MAX_VALUE))
        );

        jSplitPane4.setLeftComponent(admnmng);

        userProcessContainer1.setBackground(new java.awt.Color(8, 21, 49));
        userProcessContainer1.setForeground(new java.awt.Color(30, 50, 71));
        userProcessContainer1.setLayout(new java.awt.CardLayout());
        jSplitPane4.setRightComponent(userProcessContainer1);

        getContentPane().add(jSplitPane4);
    }// </editor-fold>//GEN-END:initComponents

    private void btnmngauthMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmngauthMousePressed
        // TODO add your handling code here:
        setColor(btnmngauth);
        JPanel [] paneels = {entpmanagebutton};
        resetColor(paneels);

        ManageEnterpriseAdminJPanel manageEntA = new ManageEnterpriseAdminJPanel(userProcessContainer1,ecosystem,UA);
        userProcessContainer1.add("ManageEnterpriseAdminJPanel",manageEntA);
        CardLayout layout = (CardLayout) userProcessContainer1.getLayout();
        layout.next(userProcessContainer1);
    }//GEN-LAST:event_btnmngauthMousePressed

    private void backMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMousePressed
        // TODO add your handling code here:
        this.dispose();
        dB4OUtil.storeSystem(ecosystem);
    }//GEN-LAST:event_backMousePressed

    private void entpmanagebuttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entpmanagebuttonMousePressed
        // TODO add your handling code here:
        setColor(entpmanagebutton);
        JPanel [] paneels = {btnmngauth};
        resetColor(paneels);

        ManageEnterpriseJPanel manageEnt = new ManageEnterpriseJPanel(userProcessContainer1,ecosystem,UA);
        userProcessContainer1.add("ManageEnterpriseJPanel",manageEnt);
        CardLayout layout = (CardLayout) userProcessContainer1.getLayout();
        layout.next(userProcessContainer1);
    }//GEN-LAST:event_entpmanagebuttonMousePressed

    private void mngemntlblVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_mngemntlblVetoableChange
        // TODO add your handling code here:
    }//GEN-LAST:event_mngemntlblVetoableChange

    private void accmangbtnVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_accmangbtnVetoableChange
        // TODO add your handling code here:
    }//GEN-LAST:event_accmangbtnVetoableChange
int xx,xy;    
    private void setColor(JPanel pane)
    {
        pane.setBackground(new Color(50, 62, 168));
    }
    private void resetColor(JPanel [] pane)
    {
        for(int i=0;i<pane.length;i++){
           pane[i].setBackground(new Color(23,35,51));
           
        } 
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accmangbtn;
    private javax.swing.JPanel admnmng;
    private javax.swing.JLabel back;
    private javax.swing.JPanel btnmngauth;
    private javax.swing.JPanel entpmanagebutton;
    private javax.swing.JSplitPane jSplitPane4;
    private javax.swing.JLabel mngemntlbl;
    private javax.swing.JPanel userProcessContainer1;
    // End of variables declaration//GEN-END:variables
}
